Repository concourse/concourse, pull requests merged in 2019-11, with the labels that each got.

#4696 [Fly] refactor fly builds commands
  fly/commands/builds.go
Labels: release/no-impact

#4657 feat: make RBAC configurable.
  atc/api/accessor/accessor.go
  atc/api/accessor/accessor_factory.go
  atc/api/accessor/accessor_factory_test.go
  atc/api/accessor/accessor_test.go
  atc/api/accessor/accessorfakes/fake_access_factory.go
  atc/api/accessor/accessorfakes/fake_action_role_map.go
  atc/api/accessor/accessorfakes/fake_action_role_map_modifier.go
  atc/api/accessor/role_action_map.go
  atc/atccmd/command.go
Labels: auth, enhancement

#4736 Avoid infinite loop in web ui when pipeline has loops
  web/public/graph.js
Labels: release/undocumented

#4763 [release/5.7.x] Allow topgun to run all tests suites
  topgun/common/common.go
  topgun/deployments/concourse.yml
Labels: release/no-impact

#4764 Allow topgun to run all tests suites
  topgun/common/common.go
  topgun/deployments/concourse.yml
Labels: release/no-impact

#4757 Don't redact single-char secret. mitigate #4749.
  atc/engine/builder/delegate_factory.go
  atc/engine/builder/delegate_factory_test.go
Labels: logging

#4737 atc: eliminate unused `tagsMatch` method
  atc/db/worker_factory.go
Labels: release/no-impact

#4808 bug: fixed a lidar bug that caused ATC crash.
  atc/lidar/scanner.go
Labels: bug

#4817 fix(atc): when secret redaction is not enabled, should not buffer build log lines
  atc/engine/builder/delegate_factory.go
  atc/engine/builder/delegate_factory_test.go
  vars/vars_tracker.go
Labels: bug, regression
