Repository concourse/concourse, pull requests merged in 2019-12, with the labels that each got.

#4708 feat(atc): add set_pipeline step.
  atc/api/config_test.go
  atc/api/configserver/get.go
  atc/api/configserver/save.go
  atc/atccmd/command.go
  atc/config.go
  atc/config_diff.go
  atc/configvalidate/validate.go
  atc/configvalidate/validate_test.go
  atc/db/dbfakes/fake_pipeline.go
  atc/db/job_test.go
  atc/db/pipeline.go
  atc/db/pipeline_test.go
  atc/db/team_test.go
  atc/engine/builder/builder.go
  atc/engine/builder/builder_test.go
  atc/engine/builder/builderfakes/fake_delegate_factory.go
  atc/engine/builder/builderfakes/fake_step_factory.go
  atc/engine/builder/delegate_factory.go
  atc/engine/builder/delegate_factory_test.go
  atc/engine/builder/step_factory.go
  atc/event/events.go
  atc/event/types.go
  atc/exec/artifact/error.go
  atc/exec/artifact/repository.go
  atc/exec/artifact/repository_test.go
  atc/exec/build_step_delegate.go
  atc/exec/execfakes/fake_build_step_delegate.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/exec/get_step.go
  atc/exec/log_error_step.go
  atc/exec/put_step.go
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
  atc/exec/step.go
  atc/exec/task_step.go
  atc/plan.go
  atc/plan_factory.go
  atc/public_plan.go
  atc/public_plan_test.go
  atc/scheduler/factory/build_factory.go
  atc/scheduler/factory/factory_set_pipeline_test.go
  atc/scheduler/inputmapper/inputmapper_test.go
  fly/commands/internal/setpipelinehelpers/atc_config.go
  testflight/set-pipeline-step_test.go
  web/elm/src/Build/Models.elm
  web/elm/src/Build/Output/Output.elm
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Build/Styles.elm
  web/elm/src/Concourse.elm
  web/elm/src/Concourse/BuildEvents.elm
  web/elm/tests/BuildStepTests.elm
  web/elm/tests/StepTreeTests.elm
Labels: enhancement

#4816 #4566: removed register-worker command from tsa
  tsa/README.md
  tsa/commands.go
  tsa/tsacmd/remote_cli.go
  tsa/tsacmd/server.go
Labels: release/no-impact

#4874 Add release notes for #4816
  release-notes/latest.md
Labels: release/no-impact

#4858 fix(fly): set-team discards roles with no user and group from team config file.
  fly/integration/fixtures/team_config_empty_users.yml
  fly/integration/set_team_test.go
  skymarshal/skycmd/flags.go
Labels: bug, fly

#4777 feat(atc): support named var.
  atc/config.go
  atc/config_test.go
  atc/configvalidate/validate.go
  atc/configvalidate/validate_test.go
  atc/db/pipeline.go
  atc/db/pipeline_test.go
  atc/radar/resource_scanner.go
  testflight/fixtures/var-sources.yml
  vars/named_vars.go
  vars/named_vars_test.go
  vars/template.go
  vars/template_test.go
Labels: core/creds, enhancement

#4912 backport let's encrypt bump + default fix to 5.5.x
  atc/atccmd/command.go
  atc/atccmd/command_test.go
  go.mod
  go.sum
  release-notes/v5.5.7.md
Labels: backport

#4911 backport Let's Encrypt default fix to 5.7.x
  atc/atccmd/command.go
  atc/atccmd/command_test.go
  release-notes/v5.7.3.md
Labels: backport

#4927 atc: rename auth_param config to auth_params
  atc/creds/vault/manager.go
Labels: release/no-impact

#4937 redo vault var source config flow
  atc/api/info_test.go
  atc/creds/vault/api_client.go
  atc/creds/vault/manager.go
  atc/creds/vault/manager_factory.go
  atc/creds/vault/manager_test.go
  atc/creds/vault/reauther_test.go
  go.mod
  go.sum
Labels: release/no-impact
