Repository concourse/concourse, pull requests merged in 2019-10, with the labels that each got.

#4518 feat: avoid to renew Vault lease every second if Vault server doesn't accept renew.
  atc/creds/vault/api_client.go
Labels: enhancement

#4555 Adding release notes for v5.6.1
  release-notes/v5.6.1.md
Labels: release/no-impact

#4558 Added release note for fly workers age fix
  release-notes/v5.6.1.md
Labels: release/no-impact

#4565 Clean up v5.6.1 release notes
  release-notes/latest.md
  release-notes/v5.6.1.md
Labels: release/no-impact

#4573 Notify scanner when pipeline set
  atc/api/config_test.go
  atc/api/configserver/save.go
  atc/api/pipelines_test.go
  atc/api/pipelineserver/unpause.go
  atc/db/dbfakes/fake_team_factory.go
  atc/db/team_factory.go
Labels: release/no-impact

#4441 web: refactor build header
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Application/Application.elm
  web/elm/src/Build/Build.elm
  web/elm/src/Build/Header/Header.elm
  web/elm/src/Build/Header/Models.elm
  web/elm/src/Build/Header/Views.elm
  web/elm/src/Build/Models.elm
  web/elm/src/Build/Output/Output.elm
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Build/Styles.elm
  web/elm/src/Colors.elm
  web/elm/src/Concourse.elm
  web/elm/src/Concourse/BuildEvents.elm
  web/elm/src/Concourse/BuildStatus.elm
  web/elm/src/Dashboard/DashboardPreview.elm
  web/elm/src/Dashboard/Group.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Job/Styles.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Routes.elm
  web/elm/src/SubPage/SubPage.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/BuildStepTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/Common.elm
  web/elm/tests/DashboardPreviewTests.elm
  web/elm/tests/DashboardSearchTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/UserStateTests.elm
Labels: web-ui

#4188 feat[gc/build-log-collector]: Added minimum_succeeded_builds to build_log_retention
  atc/gc/build_log_collector.go
  atc/gc/build_log_collector_test.go
  atc/gc/build_log_retention_calculator.go
  atc/gc/build_log_retention_calculator_test.go
  atc/job_config.go
  atc/validate.go
Labels: core/api

#4614 Regenerate counterfeit fakes and fix failing test.
  atc/worker/image/image_resource_fetcher_test.go
  atc/worker/workerfakes/fake_worker.go
Labels: release/no-impact

#4608 Add release note for log change #4606
  release-notes/latest.md
Labels: release/no-impact

#4620 web: upgrade dependencies
  package.json
  web/elm/elm.json
  yarn.lock
Labels: chore, release/no-impact, web-ui

#4648 atc, fly, topgun: run goimports
  atc/db/container_repository.go
  atc/db/migration/bindata.go
  atc/gc/gc_suite_test.go
  atc/metric/emitter/newrelic.go
  fly/commands/login.go
  fly/commands/unpin_resource.go
  fly/integration/workers_test.go
  topgun/k8s/container_limits_test.go
  topgun/runtime/build_artifact_transfer_test.go
Labels: refactor, release/no-impact

#4502 atc: add a dummy credential manager
  atc/atccmd/command.go
  atc/creds/dummy/flags.go
  atc/creds/dummy/manager.go
  atc/creds/dummy/manager_factory.go
  atc/creds/dummy/secrets.go
  atc/creds/dummy/secrets_factory.go
Labels: release/undocumented

#4655 fix: (creds/vault) fixed a bug when "vault-shared" is not configured, secrets under prefix can be fetched.
  atc/creds/vault/vault.go
  atc/creds/vault/vault_test.go
Labels: bug, core/creds

#4667 hack/trace: ensure dlv server port is forwarded
  hack/trace
Labels: chore, release/no-impact

#4668 fix: fixed of bug of secret redaction. issue #4656
  atc/engine/builder/delegate_factory.go
  atc/engine/builder/delegate_factory_test.go
  release-notes/latest.md
Labels: bug, logging

#4682 fix(db): fixed a bug where if query builds with a date that newer than all builds, it should return nothing but it actually returned all builds.
  atc/db/build_factory.go
  atc/db/build_factory_test.go
Labels: bug

#4688 web: pin menu polish
  release-notes/latest.md
  web/elm/src/Colors.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Pipeline/PinMenu/PinMenu.elm
  web/elm/src/Pipeline/PinMenu/Styles.elm
  web/elm/src/Pipeline/PinMenu/Views.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Pipeline/Styles.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/tests/PinMenu/PinMenuTests.elm
  web/elm/tests/PipelineTests.elm
Labels: web-ui
