Repository concourse/concourse, pull requests merged in 2019-01, with the labels that each got.

#2933 fly: add check to see if pipeline exists
  fly/commands/get_pipeline.go
  fly/integration/get_pipeline_test.go
Labels: enhancement

#3059 Revert role sorting
  atc/api/accessor/accessor.go
  atc/api/accessor/accessor_test.go
  fly/commands/teams.go
  fly/integration/teams_test.go
  skymarshal/token/issuer.go
  skymarshal/token/issuer_test.go
Labels: regression

#3051 Force resource check from web UI
  web/elm/src/Colors.elm
  web/elm/src/Concourse/Resource.elm
  web/elm/src/Effects.elm
  web/elm/src/Layout.elm
  web/elm/src/Resource.elm
  web/elm/src/Resource/Effects.elm
  web/elm/src/Resource/Models.elm
  web/elm/src/Resource/Msgs.elm
  web/elm/src/SubPage.elm
  web/elm/src/TopBar.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/LayoutTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/SubPageTests.elm
  web/public/images/baseline-refresh-24px.svg
Labels: enhancement, web-ui

#3041 atc: remove objectId from locks held metric [#2980]
  atc/metric/emitter/prometheus.go
  atc/metric/metrics.go
Labels: enhancement, metrics

#3032 web: disable ascii art interaction
  web/elm/src/Dashboard.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/tests/DashboardTests.elm
Labels: enhancement, web-ui

#3082 atc: ports the changes from the security fix in 4.2.2
  skymarshal/skyserver/skyserver.go
  skymarshal/skyserver/skyserver_test.go
Labels: bug, security

#3084 Revert "Add new endpoint to get token for manual fly login"
  skymarshal/skyserver/skyserver.go
  skymarshal/skyserver/skyserver_test.go
Labels: security

#3101 Web: Refactoring effects from each separate screen into a single datatype
  go.mod
  web/elm/src/Autoscroll.elm
  web/elm/src/Build.elm
  web/elm/src/Build/Effects.elm
  web/elm/src/Build/Msgs.elm
  web/elm/src/Build/Output.elm
  web/elm/src/Build/StepTree.elm
  web/elm/src/Dashboard.elm
  web/elm/src/Dashboard/Group.elm
  web/elm/src/Dashboard/Msgs.elm
  web/elm/src/Effects.elm
  web/elm/src/FlySuccess.elm
  web/elm/src/FlySuccess/Msgs.elm
  web/elm/src/Job.elm
  web/elm/src/Job/Msgs.elm
  web/elm/src/Layout.elm
  web/elm/src/LoginRedirect.elm
  web/elm/src/Main.elm
  web/elm/src/NewTopBar.elm
  web/elm/src/NotAuthorized.elm
  web/elm/src/NotFound.elm
  web/elm/src/Pipeline.elm
  web/elm/src/Pipeline/Msgs.elm
  web/elm/src/Resource.elm
  web/elm/src/Resource/Effects.elm
  web/elm/src/Resource/Msgs.elm
  web/elm/src/Routes.elm
  web/elm/src/SubPage.elm
  web/elm/src/SubPage/Msgs.elm
  web/elm/src/TopBar.elm
  web/elm/src/UpdateMsg.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/FlySuccessTests.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/NewTopBarTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/StepTreeTests.elm
  web/elm/tests/SubPageTests.elm
  web/elm/tests/TopBarTests.elm
Labels: web-ui

#3119 bump hashicorp/go-msgpack to avoid bzr deps
  go.mod
  go.sum
Labels: dependency

#3031 Add httponly and secure attributes to skyserver calls
  skymarshal/skyserver/skyserver.go
  skymarshal/skyserver/skyserver_test.go
Labels: enhancement, security

#3130 web: merge Autoscroll and Build
  web/elm/src/Autoscroll.elm
  web/elm/src/Build.elm
  web/elm/src/Build/Msgs.elm
  web/elm/src/Effects.elm
  web/elm/src/SubPage.elm
  web/elm/src/SubPage/Msgs.elm
Labels: refactor

#2759 Support for cc.xml
  atc/api/accessor/accessor.go
  atc/api/accessor/accessor_test.go
  atc/api/cc_test.go
  atc/api/ccserver/get.go
  atc/api/ccserver/server.go
  atc/api/handler.go
  atc/routes.go
  atc/wrappa/api_auth_wrappa.go
  atc/wrappa/api_auth_wrappa_test.go
Labels: enhancement

#3150 web: extract Subscription data type
  web/elm/src/Build.elm
  web/elm/src/Build/Models.elm
  web/elm/src/Build/Msgs.elm
  web/elm/src/Build/Output.elm
  web/elm/src/Concourse/BuildEvents.elm
  web/elm/src/Concourse/Pagination.elm
  web/elm/src/Dashboard.elm
  web/elm/src/Job.elm
  web/elm/src/Layout.elm
  web/elm/src/Main.elm
  web/elm/src/Msgs.elm
  web/elm/src/Pipeline.elm
  web/elm/src/Pipeline/Msgs.elm
  web/elm/src/Resource.elm
  web/elm/src/Resource/Msgs.elm
  web/elm/src/SubPage.elm
  web/elm/src/Subscription.elm
  web/elm/src/TopBar.elm
  web/elm/src/TopBar/Msgs.elm
  web/elm/tests/FlySuccessTests.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/MainTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/TopBarTests.elm
Labels: refactor
