Repository concourse/concourse, pull requests merged in 2020-10, with the labels that each got.

#6101 Fix: ignore unknown keys in garden ini
  worker/workercmd/guardian.go
Labels: release/no-impact

#6034 Update k8s-topgun for Helm v3
  topgun/k8s/external_postgres_test.go
  topgun/k8s/k8s_suite_test.go
  topgun/k8s/prometheus_test.go
Labels: release/no-impact

#6099 Fix fly integration tests on windows
  fly/integration/archive_pipeline_test.go
  fly/integration/checklist_test.go
  fly/integration/destroy_pipeline_test.go
  fly/integration/expose_pipeline_test.go
  fly/integration/get_pipeline_test.go
  fly/integration/hide_pipeline_test.go
  fly/integration/ordering_pipelines_test.go
  fly/integration/pause_pipeline_test.go
  fly/integration/rename_pipeline_test.go
  fly/integration/unpause_pipeline_test.go
Labels: release/no-impact

#6102 Fix pipeline cards being rendered off-screen when sidebar was open
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/tests/PipelineGridTests.elm
Labels: bug

#6096 switch back to upstream go-flags
  go.mod
  go.sum
Labels: release/no-impact

#6086 Add flag to concourse worker to overwrite init binary path
  worker/runtime/backend.go
  worker/runtime/spec/mounts.go
  worker/runtime/spec/spec.go
  worker/runtime/spec/spec_test.go
  worker/workercmd/containerd.go
  worker/workercmd/worker_linux.go
Labels: enhancement

#6119 Emit start/finish metrics from check step
  atc/exec/check_step.go
  atc/metric/emit.go
  atc/metric/periodic.go
Labels: release/no-impact

#6106 update go module dependencies [go.opentelemetry.io/otel]
  .gitignore
  atc/creds/kubernetes/kubernetes_test.go
  atc/creds/kubernetes/secrets.go
  atc/db/build.go
  atc/db/dbfakes/fake_build.go
  atc/db/dbfakes/fake_check_factory.go
  atc/db/dbfakes/fake_resource_config_version.go
  atc/db/job_factory_test.go
  atc/db/job_test.go
  atc/db/pipeline_test.go
  atc/db/resource_config_version.go
  atc/db/resource_test.go
  atc/db/resource_type_test.go
  atc/db/team_test.go
  atc/db/versions_db.go
  atc/db/volume_test.go
  atc/exec/artifact_input_step_test.go
  atc/exec/artifact_output_step_test.go
  atc/exec/check_step_test.go
  atc/exec/exec_suite_test.go
  atc/exec/get_step_test.go
  atc/exec/put_step_test.go
  atc/exec/retry_error_step_test.go
  atc/exec/task_step_test.go
  atc/gc/build_log_retention_calculator.go
  atc/scheduler/algorithm/group_resolver.go
  atc/scheduler/algorithm/individual_resolver.go
  atc/scheduler/algorithm/pinned_resolver.go
  atc/scheduler/algorithm/suite_test.go
  atc/scheduler/algorithm/table_helpers_test.go
  atc/scheduler/runner.go
  atc/scheduler/scheduler_test.go
  atc/worker/client_test.go
  atc/worker/container_spec.go
  atc/worker/fetch_source_test.go
  atc/worker/image/image_resource_fetcher_test.go
  atc/worker/worker_test.go
  fly/eventstream/render_test.go
  go-concourse/concourse/internal/connection_test.go
  go.mod
  go.sum
  topgun/k8s/baggageclaim_drivers_test.go
  topgun/k8s/dns_proxy_test.go
  topgun/k8s/k8s_suite_test.go
  tracing/attrs.go
  tracing/jaeger.go
  tracing/stackdriver.go
  tracing/tracer.go
  tracing/tracer_test.go
  tracing/tracingfakes/fake_provider.go
  tracing/tracingfakes/fake_span.go
  tracing/tracingfakes/fake_tracer.go
  worker/runtime/integration/sample/main.go
Labels: enhancement

#6108 Fix quoting for var subkeys
  vars/template.go
  vars/template_test.go
Labels: bug

#6120 make CNI plugins directory configurable
  worker/runtime/cni_network.go
  worker/workercmd/containerd.go
  worker/workercmd/worker_linux.go
Labels: enhancement

#6129 allow @ sign in var
  vars/template.go
  vars/template_test.go
Labels: release/no-impact

#6136 Convert a few failing TopGun tests to Testflight
  testflight/containers_scoped_to_team_test.go
  testflight/fixtures/resource-gc-get-and-task.yml
  testflight/fixtures/resource-gc-removed.yml
  testflight/fixtures/wait-for-intercept.yml
  testflight/list_builds_test.go
  testflight/resource_containers_gc_test.go
  testflight/suite_test.go
  topgun/both/resource_containers_gc_test.go
  topgun/core/containers_scoped_to_team_test.go
Labels: misc

#6143 Use custom types for CPU/Memory limits
  atc/atccmd/command.go
  atc/container_limits.go
  atc/container_limits_marshaller.go
  atc/container_limits_marshaller_test.go
  atc/exec/task_step.go
  atc/exec/task_step_test.go
  atc/task.go
  atc/task_test.go
Labels: misc

#6142 containerd: use default uid:gid if passwd file does not exist and username is "root"
  worker/runtime/rootfs_manager.go
  worker/runtime/rootfs_manager_test.go
Labels: bug

#6131 cleanup k8s topgun releases if failure outside of `It` block
  topgun/k8s/baggageclaim_drivers_test.go
  topgun/k8s/container_limits_test.go
  topgun/k8s/dns_proxy_test.go
  topgun/k8s/ephemeral_worker_test.go
  topgun/k8s/external_postgres_test.go
  topgun/k8s/external_worker_test.go
  topgun/k8s/garden_config_test.go
  topgun/k8s/https_web_tls_termination_test.go
  topgun/k8s/k8s_suite_test.go
  topgun/k8s/kubernetes_creds_mgmt_test.go
  topgun/k8s/mainteam_role_test.go
  topgun/k8s/prometheus_test.go
  topgun/k8s/tsa_node_port_test.go
  topgun/k8s/web_scaling_test.go
  topgun/k8s/worker_lifecycle_test.go
Labels: misc

#6079 feat(atc): add "defaults" to resource type.
  atc/atccmd/command.go
  atc/base_resource_type_defaults.go
  atc/base_resource_type_defaults_test.go
  atc/builds/planner.go
  atc/config.go
  atc/db/check_factory.go
  atc/db/check_factory_test.go
  atc/db/dbfakes/fake_checkable.go
  atc/db/dbfakes/fake_resource.go
  atc/db/dbfakes/fake_resource_type.go
  atc/db/job_factory.go
  atc/db/job_factory_test.go
  atc/db/resource.go
  atc/db/resource_test.go
  atc/db/resource_type.go
  atc/db/resource_type_test.go
  atc/exec/task_config_source.go
  atc/exec/task_config_source_test.go
  atc/exec/task_step.go
  atc/resource_types.go
  atc/task.go
  atc/task_test.go
Labels: enhancement

#6152 Minor refactoring around Variables
  atc/creds/conjur/conjur_test.go
  atc/creds/dummy/secrets.go
  atc/creds/retryable_secrets_test.go
  atc/creds/secret_var_lookup.go
  atc/creds/secret_var_lookup_rules.go
  atc/creds/secret_var_lookup_test.go
  atc/creds/secretsmanager/secretsmanager_test.go
  atc/creds/ssm/ssm_test.go
  atc/creds/vault/vault_test.go
  atc/db/build_test.go
  atc/db/pipeline_test.go
  atc/engine/builder/build_step_delegate_test.go
  atc/engine/engine_test.go
  atc/exec/across_step.go
  atc/exec/across_step_test.go
  atc/exec/build_vars.go
  atc/exec/execfakes/fake_run_state.go
  atc/exec/run_state.go
  atc/exec/run_state_test.go
  vars/multi_vars.go
  vars/multi_vars_test.go
  vars/named_vars.go
  vars/named_vars_test.go
  vars/reference_test.go
  vars/static_vars.go
  vars/static_vars_test.go
  vars/suite_test.go
  vars/template.go
  vars/tracker.go
  vars/variables.go
  vars/varsfakes/fake_variables.go
Labels: misc, refactor

#6144 fly: add --team option to get-pipeline command
  fly/commands/get_pipeline.go
  fly/integration/error_handling_test.go
  fly/integration/get_pipeline_test.go
Labels: enhancement, fly

#6157 Preserve whitespace within build output
  web/assets/css/build.less
Labels: bug

#6116 Prevent set_pipeline runtime error
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
Labels: bug

#6132 fly: add --team flag to order-pipelines
  fly/commands/ordering_pipeline.go
  fly/integration/error_handling_test.go
Labels: enhancement

#6159 Check that a pipeline contains at least one job
  atc/api/config_test.go
  atc/configvalidate/validate.go
  atc/configvalidate/validate_test.go
  atc/exec/set_pipeline_step_test.go
Labels: enhancement

#6167 k8s topgun: fix panic
  topgun/k8s/k8s_suite_test.go
Labels: misc

#6164 set_pipeline prints 'no changes to apply'
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
Labels: enhancement

#6156 Introduce dbtest package for higher-level test setup
  atc/db/build.go
  atc/db/build_test.go
  atc/db/check_factory.go
  atc/db/db_suite_test.go
  atc/db/dbfakes/fake_checkable.go
  atc/db/dbfakes/fake_resource.go
  atc/db/dbfakes/fake_resource_config_version.go
  atc/db/dbfakes/fake_resource_type.go
  atc/db/dbtest/builder.go
  atc/db/dbtest/scenario.go
  atc/db/job_test.go
  atc/db/pipeline_test.go
  atc/db/resource.go
  atc/db/resource_cache_lifecycle_test.go
  atc/db/resource_config_check_session_lifecycle_test.go
  atc/db/resource_config_scope.go
  atc/db/resource_config_scope_test.go
  atc/db/resource_config_version.go
  atc/db/resource_test.go
  atc/db/resource_type.go
  atc/db/resource_type_test.go
  atc/db/team_test.go
  atc/db/versions_db_test.go
  atc/db/volume_test.go
  atc/db/worker_factory_test.go
  atc/gc/gc_suite_test.go
  atc/gc/resource_cache_collector_test.go
  atc/gc/resource_config_check_session_collector_test.go
  atc/gc/resource_config_collector_test.go
Labels: misc, refactor

#6181 containerd does not grant access to /dev/console
  worker/runtime/spec/devices.go
Labels: bug

#6103 Add Honeycomb.io as optional tracing backend
  go.mod
  go.sum
  tracing/honeycomb.go
  tracing/tracer.go
Labels: enhancement

#6184 Respect tags when fetching images, send public plans in fetching events
  atc/engine/builder/build_step_delegate.go
  atc/engine/builder/build_step_delegate_test.go
  atc/event/events.go
  atc/exec/check_step.go
  atc/exec/check_step_test.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/exec/put_step.go
  atc/exec/put_step_test.go
  atc/exec/task_step.go
  atc/exec/task_step_test.go
  atc/public_plan.go
  atc/task.go
  atc/worker/choose_task_worker_test.go
  atc/worker/client.go
  atc/worker/client_test.go
  atc/worker/container_spec.go
  atc/worker/fetch_source_test.go
  topgun/runtime/resource_certs_test.go
Labels: bug, misc, release/no-impact

#6188 Enhanced some logs to add worker name.
  atc/worker/client.go
  atc/worker/worker.go
  atc/worker/worker_test.go
Labels: enhancement, logging

#6122 add support for exporting traces via OTLP
  atc/exec/exec_suite_test.go
  atc/scheduler/algorithm/suite_test.go
  go.mod
  go.sum
  hack/oc-agent/config.yml
  hack/otel-collector/otel-collector-config.yml
  hack/overrides/jaeger.yml
  tracing/otlp.go
  tracing/tracer.go
  tracing/tracer_test.go
Labels: enhancement

#6204 topgun: use busybox for http proxy... for now
  topgun/tasks/http-proxy.yml
Labels: misc, release/no-impact

#6202 Fix pipeline UI non-trigger input edges showing up as trigger
  web/public/index.mjs
Labels: misc, release/no-impact

#6192 Update last check end time on check failure/error
  atc/exec/check_step.go
  atc/exec/check_step_test.go
Labels: misc, release/no-impact

#6185 Fix topgun/k8s tests
  topgun/k8s/baggageclaim_drivers_test.go
  topgun/k8s/container_limits_test.go
  topgun/k8s/external_postgres_test.go
  topgun/k8s/garden_config_test.go
  topgun/k8s/k8s_suite_test.go
  topgun/k8s/prometheus_test.go
  topgun/k8s/worker_lifecycle_test.go
  topgun/pipelines/task-waiting.yml
Labels: misc, release/no-impact

#6205 Fix race condition with check build creation + starting
  atc/db/build.go
  atc/db/build_test.go
  atc/db/check_factory.go
  atc/db/check_factory_test.go
  atc/db/dbfakes/fake_checkable.go
  atc/db/dbfakes/fake_resource.go
  atc/db/dbfakes/fake_resource_type.go
  atc/db/resource.go
  atc/db/resource_test.go
  atc/db/resource_type.go
  atc/db/resource_type_test.go
Labels: misc

#6174 Rename engine/builder types, merge into engine/ package
  atc/atccmd/command.go
  atc/component/cmocks/Component.go
  atc/component/cmocks/Drainable.go
  atc/component/cmocks/NotificationsBus.go
  atc/component/cmocks/RunFunc.go
  atc/component/cmocks/Schedulable.go
  atc/component/mocks.go
  atc/engine/build_step_delegate.go
  atc/engine/build_step_delegate_test.go
  atc/engine/builder.go
  atc/engine/builder/builder.go
  atc/engine/builder/builder_suite_test.go
  atc/engine/builder_test.go
  atc/engine/check_delegate.go
  atc/engine/check_delegate_test.go
  atc/engine/delegate_factory.go
  atc/engine/engine.go
  atc/engine/engine_suite_test.go
  atc/engine/engine_test.go
  atc/engine/enginefakes/fake_core_step_factory.go
  atc/engine/enginefakes/fake_rate_limiter.go
  atc/engine/enginefakes/fake_step_builder.go
  atc/engine/enginefakes/fake_stepper_factory.go
  atc/engine/get_delegate.go
  atc/engine/get_delegate_test.go
  atc/engine/log_event_writer.go
  atc/engine/put_delegate.go
  atc/engine/put_delegate_test.go
  atc/engine/set_pipeline_delegate.go
  atc/engine/set_pipeline_delegate_test.go
  atc/engine/step_factory.go
  atc/engine/task_delegate.go
  atc/engine/task_delegate_test.go
  atc/exec/execfakes/fake_build_step_delegate.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/exec/execfakes/fake_set_pipeline_step_delegate.go
Labels: misc, refactor

#6200 Determine `across` step's `max_in_flight` at runtime
  atc/builds/planner.go
  atc/builds/planner_test.go
  atc/exec/across_step_test.go
  atc/exec/in_parallel.go
  atc/plan.go
  atc/public_plan_test.go
  atc/steps.go
Labels: misc

#6170 Fix regression preventing the use of nested fields with `fly set-pipeline --var`
  atc/pipeline.go
  atc/pipeline_test.go
  fly/commands/execute.go
  fly/commands/internal/executehelpers/inputs.go
  fly/commands/internal/flaghelpers/input_mapping_pair_flag.go
  fly/commands/internal/flaghelpers/input_pair_flag.go
  fly/commands/internal/flaghelpers/instance_var_pair_flag.go
  fly/commands/internal/flaghelpers/instance_var_pair_flag_test.go
  fly/commands/internal/flaghelpers/job_flag.go
  fly/commands/internal/flaghelpers/job_flag_test.go
  fly/commands/internal/flaghelpers/output_pair_flag.go
  fly/commands/internal/flaghelpers/pipeline_flag.go
  fly/commands/internal/flaghelpers/pipeline_flag_test.go
  fly/commands/internal/flaghelpers/resource_flag.go
  fly/commands/internal/flaghelpers/resource_flag_test.go
  fly/commands/internal/flaghelpers/variable_pair_flag.go
  fly/commands/internal/flaghelpers/yaml_variable_pair_flag.go
  fly/commands/internal/flaghelpers/yaml_variable_pair_flag_test.go
  fly/commands/internal/setpipelinehelpers/atc_config.go
  fly/commands/internal/setpipelinehelpers/atc_config_test.go
  fly/commands/internal/templatehelpers/yaml_template.go
  fly/commands/internal/templatehelpers/yaml_template_test.go
  fly/commands/set_pipeline.go
  fly/commands/validate_pipeline.go
  fly/integration/fixtures/nested-vars-pipeline.yml
  fly/integration/fixtures/vars-pipeline-params-types.yml
  fly/integration/fixtures/vars-pipeline.yml
  fly/integration/set_pipeline_test.go
  vars/reference_test.go
  vars/static_vars.go
  vars/static_vars_test.go
  vars/template.go
  vars/template_test.go
  vars/variables.go
Labels: bug

#6203 Migrate build_id references to bigint, batch event migration
  atc/atccmd/command.go
  atc/component.go
  atc/db/migration/batch/build_events_bigint.go
  atc/db/migration/batch/build_events_bigint_test.go
  atc/db/migration/batch/runner.go
  atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.down.sql
  atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.up.sql
  atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.down.sql
  atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.up.sql
  atc/db/open.go
Labels: misc

#6211 Clear build events from previous resource/resource type check
  atc/db/resource.go
  atc/db/resource_test.go
  atc/db/resource_type.go
  atc/db/resource_type_test.go
Labels: misc

#6212 fast forward release branch
  atc/atccmd/command.go
  atc/component.go
  atc/db/migration/batch/build_events_bigint.go
  atc/db/migration/batch/build_events_bigint_test.go
  atc/db/migration/batch/runner.go
  atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.down.sql
  atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.up.sql
  atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.down.sql
  atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.up.sql
  atc/db/open.go
  atc/db/resource.go
  atc/db/resource_test.go
  atc/db/resource_type.go
  atc/db/resource_type_test.go
Labels: misc

#6169 fly: add --team option to expose-pipeline command
  fly/commands/expose_pipeline.go
  fly/integration/error_handling_test.go
  fly/integration/expose_pipeline_test.go
Labels: enhancement, release/undocumented

#6187 feat(atc): add a new metrics "volumes streamd"
  atc/metric/emit.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/prometheus.go
  atc/metric/periodic.go
  atc/worker/artifact_source.go
Labels: enhancement

#6219 Acquire lock on `builds` table in `build_id` migrations
  atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.down.sql
  atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.up.sql
Labels: misc

#6214 Use proper types for jobs and resources on pipeline page
  atc/api/resources_test.go
  atc/api/resourceserver/list.go
  web/elm/src/Concourse.elm
  web/elm/src/Message/Callback.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Pipeline/PinMenu/PinMenu.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/tests/PinMenu/PinMenuTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/SerializationTests.elm
Labels: misc

#6220 Revert "migration: acquire lock on builds table in build_id migrations"
  atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.down.sql
  atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.up.sql
Labels: misc

#6221 Use proper types for jobs and resources on pipeline page
  atc/api/resources_test.go
  atc/api/resourceserver/list.go
  web/elm/src/Concourse.elm
  web/elm/src/Message/Callback.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Pipeline/PinMenu/PinMenu.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/tests/PinMenu/PinMenuTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/SerializationTests.elm
Labels: misc

#6227 [topgun/k8s] Stop leaking namespaces in test env
  topgun/k8s/k8s_suite_test.go
Labels: misc, release/no-impact

#6224 Use base resource type defaults in `get`/`put` steps
  atc/builds/planner_test.go
  atc/db/job_factory.go
  atc/db/job_factory_test.go
Labels: misc

#6230 containerd does not grant access to /dev/console
  worker/runtime/spec/devices.go
Labels: bug

#6229 back-porting baggageclaim test change
  topgun/k8s/baggageclaim_drivers_test.go
Labels: misc, release/no-impact

#6109 Add an example for the release note section in the pr template
  .github/pull_request_template.md
Labels: misc

#6095 `fly pin-resource` requires a version if the resource is unpinned
  fly/commands/pin_resource.go
  fly/integration/pin_resource_test.go
Labels: bug, release/undocumented
