Repository concourse/concourse, pull requests merged in 2020-09, with the labels that each got.

#6023 Request schedule when cancelling a pending build
  atc/db/build.go
  atc/db/build_test.go
Labels: bug

#5998 Support SAML 2.0 as an auth backend
  skymarshal/skycmd/saml_flags.go
Labels: enhancement

#6021 fly: admins can login to any team that exists
  atc/api/config_test.go
  atc/api/configserver/save.go
  fly/commands/login.go
  fly/integration/login_test.go
Labels: bug

#6030 deflake k8s topgun
  topgun/k8s/https_web_tls_termination_test.go
  topgun/k8s/rebalance_test.go
Labels: release/no-impact

#6001 use the configured resolv.conf for containerd
  topgun/k8s/dns_proxy_test.go
  worker/runtime/cni_network.go
  worker/runtime/cni_network_test.go
  worker/runtime/integration/integration_test.go
  worker/runtime/resolvconf_parser.go
  worker/runtime/resolvconf_parser_test.go
  worker/runtime/suite_test.go
  worker/workercmd/containerd.go
Labels: enhancement, release/undocumented

#5980 Allow rotating the encryption key via `concourse migrate`
  atc/atccmd/command.go
  atc/db/encryption/fallback_strategy.go
  atc/db/encryption/fallback_strategy_test.go
  atc/db/migration/encryption.go
  atc/db/migration/encryption_test.go
  atc/db/migration/migration.go
  atc/db/migration/migration_test.go
  atc/db/migration/open_helper_test.go
  atc/db/open.go
  atc/postgresrunner/postgresrunner.go
Labels: enhancement, release/undocumented

#6045 worker: allow statx in containerd
  worker/runtime/spec/seccomp.go
Labels: enhancement

#6011 set_pipeline step header indicates whether changes were applied
  atc/engine/builder/builder.go
  atc/engine/builder/builderfakes/fake_delegate_factory.go
  atc/engine/builder/builderfakes/fake_step_factory.go
  atc/engine/builder/delegate_factory.go
  atc/engine/builder/step_factory.go
  atc/event/events.go
  atc/event/parser.go
  atc/event/parser_test.go
  atc/event/types.go
  atc/exec/build_step_delegate.go
  atc/exec/execfakes/fake_set_pipeline_step_delegate.go
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Build/Build.elm
  web/elm/src/Build/Models.elm
  web/elm/src/Build/Output/Output.elm
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Build/Styles.elm
  web/elm/src/Concourse/BuildEvents.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/StepTreeTests.elm
Labels: enhancement

#6053 Custom background image
  atc/api/pipelines_test.go
  atc/api/present/pipeline.go
  atc/config.go
  atc/config_diff.go
  atc/config_diff_test.go
  atc/configvalidate/validate.go
  atc/configvalidate/validate_test.go
  atc/db/dbfakes/fake_pipeline.go
  atc/db/migration/migrations/1599738693_add_pipeline_display_info.down.sql
  atc/db/migration/migrations/1599738693_add_pipeline_display_info.up.sql
  atc/db/pipeline.go
  atc/db/pipeline_test.go
  atc/db/team.go
  atc/pipeline.go
  web/elm/src/Concourse.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Pipeline/Styles.elm
  web/elm/tests/Data.elm
  web/elm/tests/PipelineTests.elm
Labels: enhancement, web-ui

#6017 Allow the fly http transport to use client certificates
  fly/commands/login.go
  fly/commands/sync.go
  fly/rc/rcfakes/fake_target.go
  fly/rc/target.go
  fly/rc/target_test.go
  fly/rc/targets.go
  fly/rc/targets_test.go
Labels: enhancement, release/documented

#6068 Make `--client-cert` flag name consistent between `fly login` and `fly sync`
  fly/commands/sync.go
Labels: release/no-impact

#6051 Fix build reaper missing builds due to pagination
  atc/api/builds_test.go
  atc/api/buildserver/list.go
  atc/api/jobs_test.go
  atc/api/jobserver/list_builds.go
  atc/api/pipelines_test.go
  atc/api/pipelineserver/list_builds.go
  atc/api/resourceserver/versionserver/list.go
  atc/api/teams_test.go
  atc/api/teamserver/list_builds.go
  atc/api/versions_test.go
  atc/db/build_factory.go
  atc/db/build_factory_test.go
  atc/db/job_test.go
  atc/db/pagination.go
  atc/db/pipeline_test.go
  atc/db/resource.go
  atc/db/resource_test.go
  atc/db/team_test.go
  atc/gc/build_log_collector.go
  atc/gc/build_log_collector_test.go
  atc/pagination.go
  fly/commands/builds.go
  fly/commands/helpers_test.go
  fly/integration/builds_test.go
  go-concourse/concourse/builds_test.go
  go-concourse/concourse/jobs_test.go
  go-concourse/concourse/pagination.go
  go-concourse/concourse/pipelines_test.go
  go-concourse/concourse/resourceversions_test.go
  web/elm/src/Api/Pagination.elm
  web/elm/src/Concourse/Pagination.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Message/Callback.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Resource/Models.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/Routes.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/PaginationTests.elm
  web/elm/tests/ResourceFeature.elm
  web/elm/tests/ResourceTests.elm
Labels: bug

#6046 Enable secret cache for var_source.
  atc/atccmd/command.go
  atc/creds/manager.go
  atc/creds/pool.go
  atc/creds/pool_test.go
  atc/db/pipeline_test.go
Labels: enhancement

#6066 Use atc.TaskEnv type in task step
  atc/api/configserver/save.go
  atc/builds/planner_test.go
  atc/creds/task_validation.go
  atc/exec/task_config_source.go
  atc/exec/task_config_source_test.go
  atc/plan.go
  atc/steps.go
  atc/steps_test.go
Labels: refactor, release/no-impact

#6078 Skip yarn benchmark until dependency is fixed
  package.json
  web/elm/elm.json
Labels: release/no-impact

#6031 Add new default values Guardian network-pool and max-containers
  worker/workercmd/guardian.go
  worker/workercmd/worker_linux.go
Labels: enhancement

#6059 Fly execute: pass worker tags to input.
  atc/api/artifactserver/create.go
  fly/commands/execute.go
  fly/commands/internal/executehelpers/inputs.go
  fly/commands/internal/executehelpers/uploads.go
  go-concourse/concourse/artifacts.go
  go-concourse/concourse/artifacts_test.go
  go-concourse/concourse/concoursefakes/fake_team.go
  go-concourse/concourse/team.go
Labels: bug, fly

#6065 Remind people they need JS to run the browser app
  web/public/index.html
Labels: enhancement, release/no-impact, web-ui

#6083 web: fix horizontal scrolling on build page
  web/assets/css/build.less
Labels: bug, web-ui

#5996 Return real JSON from "fly get-team --json"
  fly/commands/get_team.go
  fly/integration/get_team_test.go
  go-concourse/concourse/build_inputs.go
  go-concourse/concourse/build_outputs_of.go
  go-concourse/concourse/builds.go
  go-concourse/concourse/check_resource.go
  go-concourse/concourse/check_resource_type.go
  go-concourse/concourse/concoursefakes/fake_team.go
  go-concourse/concourse/configs.go
  go-concourse/concourse/containers.go
  go-concourse/concourse/jobs.go
  go-concourse/concourse/pipelines.go
  go-concourse/concourse/resource.go
  go-concourse/concourse/resourceversions.go
  go-concourse/concourse/team.go
  go-concourse/concourse/teams.go
  go-concourse/concourse/version_resource_types.go
  go-concourse/concourse/volumes.go
Labels: bug

#6087 Only set Guardian flag default when flag not provided by user
  worker/workercmd/guardian.go
  worker/workercmd/worker_linux.go
Labels: bug

#6100 Parse `--garden-max-containers` as a string
  worker/workercmd/guardian.go
Labels: release/no-impact
