Repository concourse/concourse, pull requests merged in 2020-06, with the labels that each got.

#5659 atc: trace check & build creation
  atc/db/build.go
  atc/db/build_test.go
  atc/db/check.go
  atc/db/check_factory_test.go
  atc/db/check_test.go
  atc/db/dbfakes/fake_build.go
  atc/db/dbfakes/fake_check.go
  atc/db/dbfakes/fake_job.go
  atc/db/dbfakes/fake_resource_config_scope.go
  atc/db/dbfakes/fake_resource_config_version.go
  atc/db/job.go
  atc/db/job_test.go
  atc/db/migration/migrations/1590417946_add_span_context_to_resource_config_versions.down.sql
  atc/db/migration/migrations/1590417946_add_span_context_to_resource_config_versions.up.sql
  atc/db/migration/migrations/1590517222_add_span_context_to_builds.down.sql
  atc/db/migration/migrations/1590517222_add_span_context_to_builds.up.sql
  atc/db/pipeline_test.go
  atc/db/resource.go
  atc/db/resource_cache_lifecycle_test.go
  atc/db/resource_config_scope.go
  atc/db/resource_config_scope_test.go
  atc/db/resource_config_version.go
  atc/db/resource_test.go
  atc/db/resource_type_test.go
  atc/db/team_test.go
  atc/db/volume_test.go
  atc/engine/builder/delegate_factory.go
  atc/engine/builder/delegate_factory_test.go
  atc/engine/engine.go
  atc/exec/check_step.go
  atc/exec/check_step_test.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/lidar/checker.go
  atc/lidar/checker_test.go
  atc/scheduler/runner.go
  atc/scheduler/scheduler.go
  atc/scheduler/scheduler_test.go
  release-notes/latest.md
  tracing/tracer.go
Labels: core/scheduling, domain/operations, enhancement, release/documented

#5277 atc(feat): set_pipeline step to support var.
  atc/creds/set_pipeline_plan.go
  atc/creds/set_pipeline_plan_test.go
  atc/exec/set_pipeline_step.go
Labels: enhancement

#5767 go-concourse: add client.ListAllJobs
  go-concourse/concourse/client.go
  go-concourse/concourse/concoursefakes/fake_client.go
  go-concourse/concourse/jobs.go
  go-concourse/concourse/jobs_test.go
Labels: release/undocumented

#5778 web: archived pipelines in sidebar
  web/assets/css/globals.less
  web/assets/css/typography.less
  web/elm/src/Assets.elm
  web/elm/src/Build/Styles.elm
  web/elm/src/Colors.elm
  web/elm/src/Dashboard/Group.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/FlySuccess/Styles.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Job/Styles.elm
  web/elm/src/Pipeline/PinMenu/PinMenu.elm
  web/elm/src/Pipeline/PinMenu/Styles.elm
  web/elm/src/Resource/Styles.elm
  web/elm/src/SideBar/Pipeline.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/src/SideBar/Team.elm
  web/elm/src/SideBar/Views.elm
  web/elm/src/Views/Styles.elm
  web/elm/tests/ApplicationTests.elm
  web/elm/tests/AssetsTests.elm
  web/elm/tests/BuildStepTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/FlySuccessFeature.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/PinMenu/PinMenuTests.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/SideBar/PipelineTests.elm
  web/elm/tests/SideBar/TeamTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/TopBarTests.elm
  web/elm/tests/WelcomeCardTests.elm
  web/public/fonts/Inconsolata-Black.ttf
  web/public/images/baseline-people.svg
  web/public/images/ic-archived-pipeline.svg
  web/public/images/ic-breadcrumb-pipeline.svg
  web/public/images/ic-minus.svg
  web/public/images/ic-plus.svg
Labels: archive-pipelines

#5760 web: archived pipelines UI beyond Dashboard
  web/assets/css/utils.less
  web/elm/src/Build/Header/Header.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/Resource/Styles.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/TopBarTests.elm
Labels: archive-pipelines

#5824 fly: behaviour: fix manual token input on zero-column terminals
  fly/commands/login.go
Labels: release/no-impact

#5828 fixed a bad lidar log.
  atc/lidar/scanner.go
Labels: logging

#5789 atc/exec & atc/db: track set pipelines
  atc/atccmd/command.go
  atc/db/build.go
  atc/db/build_test.go
  atc/db/db_suite_test.go
  atc/db/dbfakes/fake_build.go
  atc/db/dbfakes/fake_pipeline.go
  atc/db/dbfakes/fake_tx.go
  atc/db/migration/migrations/1591737494_add_parent_job_id.down.sql
  atc/db/migration/migrations/1591737494_add_parent_job_id.up.sql
  atc/db/open.go
  atc/db/pipeline.go
  atc/db/pipeline_test.go
  atc/db/team.go
  atc/engine/builder/step_factory.go
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
Labels: archive-pipelines
