Repository concourse/concourse, pull requests merged in 2020-07, with the labels that each got.

#5777 web: archived pipeline toggle switch
  release-notes/latest.md
  web/elm/src/Application/Application.elm
  web/elm/src/Assets.elm
  web/elm/src/Colors.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Drag.elm
  web/elm/src/Dashboard/Filter.elm
  web/elm/src/Dashboard/Footer.elm
  web/elm/src/Dashboard/Group.elm
  web/elm/src/Dashboard/Models.elm
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/src/Dashboard/PipelineGrid.elm
  web/elm/src/Dashboard/SearchBar.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Routes.elm
  web/elm/src/SubPage/SubPage.elm
  web/elm/src/Views/Styles.elm
  web/elm/src/Views/Toggle.elm
  web/elm/src/Views/TopBar.elm
  web/elm/tests/AssetsTests.elm
  web/elm/tests/DashboardArchiveTests.elm
  web/elm/tests/DashboardCacheTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/DashboardTooltipTests.elm
  web/elm/tests/DragAndDropTests.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/RoutesTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/TopBarTests.elm
  web/public/images/ic-toggle-off.svg
  web/public/images/ic-toggle-on.svg
Labels: archive-pipelines

#5849 cmd: structure: increase timeout for system claim error test
  cmd/concourse/concourse_test.go
Labels: release/no-impact

#5838 Refactor Artifact Source - remove logger
  atc/worker/artifact_source.go
  atc/worker/artifact_source_test.go
  atc/worker/client.go
  atc/worker/image/image.go
  atc/worker/image/image_test.go
  atc/worker/worker.go
  atc/worker/worker_test.go
  atc/worker/workerfakes/fake_image_fetching_delegate.go
  atc/worker/workerfakes/fake_streamable_artifact_source.go
Labels: release/no-impact

#5883 fly: always warn on set-pipeline if pipeline is paused
  fly/commands/internal/setpipelinehelpers/atc_config.go
  fly/integration/set_pipeline_test.go
Labels: enhancement

#5836 5226 max container limit
  worker/runtime/backend.go
  worker/runtime/backend_test.go
  worker/runtime/integration/integration_test.go
  worker/runtime/suite_test.go
  worker/runtime/timeout_lock.go
  worker/runtime/timeout_lock_test.go
  worker/workercmd/containerd.go
  worker/workercmd/guardian.go
  worker/workercmd/worker_linux.go
Labels: enhancement

#5737 feat(atc): support "set-pipeline: self"
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
  testflight/set-pipeline-step_test.go
Labels: enhancement

#4951 Add the token text to the fly_success page.
  web/elm/src/FlySuccess/FlySuccess.elm
  web/elm/src/FlySuccess/Models.elm
  web/elm/src/FlySuccess/Styles.elm
  web/elm/src/FlySuccess/Text.elm
  web/elm/src/Message/Message.elm
  web/elm/tests/FlySuccessFeature.elm
Labels: enhancement

#5864 valid identifiers
  atc/api/config_test.go
  atc/api/configserver/save.go
  atc/api/pipelines_test.go
  atc/api/pipelineserver/rename.go
  atc/api/teams_test.go
  atc/api/teamserver/rename.go
  atc/api/teamserver/set.go
  atc/configvalidate/validate.go
  atc/configvalidate/validate_test.go
  atc/configwarning.go
  atc/configwarning_test.go
  atc/integration/integration_suite_test.go
  atc/integration/rbac_test.go
  atc/step_validator.go
  fly/commands/archive_pipeline.go
  fly/commands/builds.go
  fly/commands/checklist.go
  fly/commands/destroy_pipeline.go
  fly/commands/expose_pipeline.go
  fly/commands/get_pipeline.go
  fly/commands/hide_pipeline.go
  fly/commands/internal/displayhelpers/error_handling.go
  fly/commands/internal/flaghelpers/pipeline_flag.go
  fly/commands/internal/setpipelinehelpers/atc_config.go
  fly/commands/ordering_pipeline.go
  fly/commands/pause_pipeline.go
  fly/commands/rename_pipeline.go
  fly/commands/rename_team.go
  fly/commands/set_pipeline.go
  fly/commands/set_team.go
  fly/commands/unpause_pipeline.go
  go-concourse/concourse/concoursefakes/fake_team.go
  go-concourse/concourse/pipelines.go
  go-concourse/concourse/pipelines_test.go
  go-concourse/concourse/team.go
  go-concourse/concourse/teams.go
  go-concourse/concourse/teams_test.go
  release-notes/latest.md
Labels: enhancement

#5866 Allow usage of images from custom resource types
  atc/testhelpers/match_plan_matcher.go
  fly/commands/execute.go
  fly/commands/internal/executehelpers/builds.go
  fly/commands/internal/executehelpers/inputs.go
  fly/integration/execute_test.go
Labels: bug

#5860 Favoriting Pipelines in SideBar
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Application/Application.elm
  web/elm/src/Assets.elm
  web/elm/src/Concourse.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Message/Storage.elm
  web/elm/src/Message/Subscription.elm
  web/elm/src/SideBar/Pipeline.elm
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/src/SideBar/Team.elm
  web/elm/src/SideBar/Views.elm
  web/elm/src/StrictEvents.elm
  web/elm/src/Tooltip.elm
  web/elm/tests/ApplicationTests.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/Data.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/SideBar/PipelineTests.elm
  web/elm/tests/SideBar/TeamTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/SideBarTests.elm
  web/elm/tests/TooltipTests.elm
  web/public/images/star-filled.svg
  web/public/images/star-unfilled.svg
Labels: enhancement, favorite-pipelines, web-ui

#5652 tsa: handling of SIGHUP to reload workers keys
  go.mod
  go.sum
  tsa/tsacmd/command.go
Labels: enhancement

#5894 feat(load_var): add format trim and make it default
  atc/exec/load_var_step.go
  atc/exec/load_var_step_test.go
Labels: breaking, enhancement

#5916 upgrade to baggageclaim 1.7.0
  go.mod
  go.sum
Labels: enhancement

#5917 Add --team to fly commands
  fly/commands/hide_pipeline.go
  fly/commands/pause_pipeline.go
  fly/integration/error_handling_test.go
  fly/integration/hide_pipeline_test.go
  fly/integration/pause_pipeline_test.go
  release-notes/latest.md
Labels: enhancement

#5898 Allow dot and colon in variable path
  atc/creds/conjur/conjur_test.go
  atc/creds/dummy/secrets.go
  atc/creds/kubernetes/kubernetes_test.go
  atc/creds/kubernetes/secrets.go
  atc/creds/retryable_secrets_test.go
  atc/creds/secret_var_lookup.go
  atc/creds/secret_var_lookup_rules.go
  atc/creds/secretsmanager/secretsmanager.go
  atc/creds/secretsmanager/secretsmanager_test.go
  atc/creds/ssm/ssm.go
  atc/creds/ssm/ssm_test.go
  atc/creds/vault/vault_test.go
  atc/db/pipeline_test.go
  atc/engine/builder/delegate_factory_test.go
  testflight/fixtures/load-var-step.yml
  testflight/fixtures/var-sources.yml
  vars/errors.go
  vars/multi_vars_test.go
  vars/named_vars.go
  vars/named_vars_test.go
  vars/static_vars.go
  vars/static_vars_test.go
  vars/template.go
  vars/template_test.go
  vars/variables.go
  vars/vars_tracker.go
  vars/vars_tracker_test.go
Labels: enhancement

#5854 Automatically archive pipelines
  atc/api/api_suite_test.go
  atc/api/handler.go
  atc/api/pipelineserver/archive.go
  atc/api/pipelineserver/archive_test.go
  atc/api/pipelineserver/server.go
  atc/api/pipelineserver/unpause_test.go
  atc/atccmd/command.go
  atc/component.go
  atc/db/build.go
  atc/db/build_test.go
  atc/db/db_suite_test.go
  atc/db/dbfakes/fake_created_container.go
  atc/db/dbfakes/fake_destroying_container.go
  atc/db/dbfakes/fake_pipeline_lifecycle.go
  atc/db/dbfakes/fake_resource_cache_factory.go
  atc/db/migration/migrations/1595261696_add_parent_job_id_index.down.sql
  atc/db/migration/migrations/1595261696_add_parent_job_id_index.up.sql
  atc/db/pipeline.go
  atc/db/pipeline_lifecycle.go
  atc/db/pipeline_lifecycle_test.go
  atc/gc/pipeline_collector.go
  atc/gc/pipeline_collector_test.go
  atc/integration/archiving_test.go
  docker-compose.yml
  release-notes/latest.md
  testflight/automatic_archiving_test.go
  testflight/fixtures/archive-pipeline-1.yml
  testflight/fixtures/archive-pipeline-2.yml
  testflight/fixtures/archive-pipeline-3.yml
  testflight/image_resource_test.go
  testflight/suite_test.go
Labels: enhancement

#5902 Speed up querying for unencrypted builds
  atc/db/migration/migrations/1595347367_add_index_for_unencrypted_private_plans_to_builds.down.sql
  atc/db/migration/migrations/1595347367_add_index_for_unencrypted_private_plans_to_builds.up.sql
Labels: enhancement

#5908 db: behaviour: save disable_manual_trigger on job
  atc/db/job_test.go
  atc/db/team.go
Labels: bug

#5923 worker: Fix flakey container sweeper test
  worker/container_sweeper_test.go
Labels: release/no-impact

#5927 6.3.x - Update go mod with latest changes in concourse/dex
  go.mod
  go.sum
Labels: breaking, bug

#5926 6.4.x - Update go mod with latest changes in concourse/dex
  go.mod
  go.sum
Labels: breaking, bug

#5934 topgun: Fix regex to support bosh 6.x
  topgun/common/common.go
Labels: release/no-impact, release/undocumented

#5924 fly: add team option to destroy-pipeline command
  fly/commands/destroy_pipeline.go
  fly/integration/destroy_pipeline_test.go
  fly/integration/error_handling_test.go
Labels: enhancement

#5846 feat: added a new event type SelectedWorker
  atc/engine/builder/delegate_factory.go
  atc/event/events.go
  atc/event/parser.go
  atc/event/parser_test.go
  atc/event/types.go
  atc/exec/build_step_delegate.go
  atc/exec/execfakes/fake_build_step_delegate.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/exec/execfakes/fake_get_delegate.go
  atc/exec/execfakes/fake_put_delegate.go
  atc/exec/execfakes/fake_task_delegate.go
  atc/exec/get_step.go
  atc/exec/put_step.go
  atc/exec/task_step.go
  atc/runtime/runtimefakes/fake_starting_event_delegate.go
  atc/runtime/types.go
  atc/worker/client.go
  atc/worker/client_test.go
  fly/eventstream/render.go
  fly/eventstream/render_test.go
  release-notes/latest.md
  web/elm/src/Build/Output/Output.elm
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Concourse/BuildEvents.elm
Labels: enhancement

#5925 Update go mod with latest changes in concourse/dex
  go.mod
  go.sum
Labels: breaking, bug
