Repository concourse/concourse, pull requests merged in 2020-02, with the labels that each got.

#5105 nit: fix a typo.
  atc/api/accessor/handler_test.go
Labels: bug, release/no-impact

#5069 add release note for (un)pausing all pipelines
  release-notes/latest.md
Labels: release/no-impact

#5100 Remove unused CLI option resource-type-checking-interval.
  atc/atccmd/command.go
Labels: breaking, bug

#5108 web: fix dashboard filtering
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Filter.elm
  web/elm/src/Dashboard/Group.elm
  web/elm/tests/DashboardSearchTests.elm
Labels: bug, release/no-impact, web-ui

#5149 feat(atc): skip resource check for put-only resources.
  atc/db/check_factory.go
  atc/db/check_factory_test.go
Labels: enhancement

#5204 containerd: mention that it's experimental
  worker/workercmd/worker_linux.go
Labels: release/no-impact

#5208 containerd: implement getter/setter for grace time
  worker/backend/backend.go
  worker/backend/backend_test.go
  worker/backend/container.go
  worker/backend/container_test.go
Labels: release/no-impact

#5200 topgun/k8s: test GARDEN_DENY_NETWORK
  topgun/k8s/garden_config_test.go
  topgun/tasks/garden-deny-network.yml
Labels: chore, release/no-impact

#5248 testflight: download fly instead of building
  testflight/suite_test.go
Labels: chore, release/no-impact
