Repository concourse/concourse, pull requests merged in 2020-11, with the labels that each got.

#6098 Fallback hijack to sh when bash is missing
  atc/api/containerserver/hijack.go
  atc/hijack_payload.go
  atc/worker/transport/hijack_streamer.go
  atc/worker/transport/hijack_streamer_test.go
  fly/commands/hijack.go
  fly/commands/internal/hijacker/hijacker.go
  fly/commands/internal/hijacker/hijacker_test.go
  fly/integration/hijack_test.go
Labels: enhancement

#6197 Prevent retrying on worker error when build is aborted
  atc/exec/retry_error_step.go
  atc/exec/retry_error_step_test.go
Labels: bug

#6216 limit-active-task:structural: limit configured by limit-active-tasks is not respected and more tasks can land on a worker
  atc/worker/client.go
Labels: bug

#6235 Check step only acquires lock for periodic pipeline resource checks
  atc/builds/tracker.go
  atc/builds/tracker_test.go
  atc/db/lock/lock.go
  atc/engine/check_delegate.go
  atc/engine/check_delegate_test.go
  atc/engine/engine.go
  atc/engine/engine_suite_test.go
  atc/exec/aggregate.go
  atc/exec/check_step.go
  atc/exec/exec_suite_test.go
  atc/exec/in_parallel.go
  atc/lidar/lidar_suite_test.go
  atc/lidar/scanner.go
  atc/scheduler/runner.go
  atc/scheduler/scheduler_suite_test.go
  atc/util/panic_dump.go
Labels: misc, release/no-impact

#6254 Fix up test data race for build tracker
  atc/builds/tracker_test.go
Labels: misc

#6195 Bump dex module to v0.2.0
  atc/api/accessor/accessor.go
  atc/api/accessor/accessor_factory_test.go
  atc/api/accessor/accessor_test.go
  atc/api/users_test.go
  atc/api/usersserver/get.go
  atc/db/access_token.go
  atc/db/access_token_factory_test.go
  atc/integration/integration_suite_test.go
  cmd/concourse/main.go
  go.mod
  go.sum
  pkged.go
  skymarshal/dexserver/dexserver.go
  skymarshal/skycmd/oauth_flags.go
  skymarshal/skycmd/oidc_flags.go
  skymarshal/storage/storage.go
  skymarshal/token/access_token.go
  skymarshal/web/templates/device.html
  skymarshal/web/templates/device_success.html
Labels: enhancement

#6257 Remove any existing guardian assets
  worker/workercmd/guardian.go
Labels: bug

#6264 fly: give more leeway for slow test
  fly/integration/builds_test.go
Labels: flake, misc

#6186 feat: P2P Volume Streaming
  atc/atccmd/command.go
  atc/worker/artifact_destination.go
  atc/worker/artifact_source.go
  atc/worker/artifact_source_test.go
  atc/worker/choose_task_worker_test.go
  atc/worker/client.go
  atc/worker/client_test.go
  atc/worker/image/image.go
  atc/worker/volume.go
  atc/worker/workerfakes/fake_artifact_destination.go
  atc/worker/workerfakes/fake_volume.go
  go.mod
  go.sum
  versions.go
Labels: enhancement

#6272 atc(bug): checks-enqueued should only be inc when a check is created
  atc/lidar/scanner.go
Labels: bug

#6265 atc: abort a rerun build if input version gone
  atc/db/build.go
  atc/db/build_test.go
Labels: bug

#6273 atc: behavior: add index to improve build deletion
  atc/db/migration/migrations/1601993582_add_successful_build_outputs_rerun_of_index.down.sql
  atc/db/migration/migrations/1601993582_add_successful_build_outputs_rerun_of_index.up.sql
Labels: enhancement

#6271 feat(atc 6.7.x): skip checking put-only resources.
  .deepsource.toml
  atc/atccmd/command.go
  atc/db/check_factory.go
  atc/db/check_factory_test.go
  atc/db/db_suite_test.go
Labels: enhancement

#6282 act(bug): 6.7.x: only inc `checks-enqueued` when a check is created.
  atc/lidar/scanner.go
Labels: bug

#6287 [topgun] skip failing topgun/k8s test
  topgun/k8s/worker_lifecycle_test.go
Labels: misc, release/no-impact

#6299 Optimize fly tests
  fly/integration/login_test.go
  fly/integration/suite_test.go
  fly/integration/sync_test.go
  fly/integration/version_test.go
Labels: release/no-impact

#6060 Allow globs in groups
  atc/configvalidate/validate.go
  atc/configvalidate/validate_test.go
  atc/db/team.go
  atc/db/team_test.go
  go.mod
  go.sum
Labels: enhancement

#6307 Backport #6116 to 6.7.x: Prevent set_pipeline runtime error
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
Labels: bug

#6310 Backport #6159: Ensure pipelines contain at least one job
  atc/api/config_test.go
  atc/configvalidate/validate.go
  atc/configvalidate/validate_test.go
  atc/exec/set_pipeline_step_test.go
Labels: enhancement

#6270 Ignore paused jobs when determining pipeline status
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/tests/PipelineCardTests.elm
Labels: enhancement, web-ui

#6280 Fix regression preventing the use of nested fields with `fly set-pipeline --var`
  atc/creds/retryable_secrets_test.go
  atc/creds/secret_var_lookup_rules.go
  fly/commands/execute.go
  fly/commands/internal/executehelpers/inputs.go
  fly/commands/internal/flaghelpers/input_mapping_pair_flag.go
  fly/commands/internal/flaghelpers/input_pair_flag.go
  fly/commands/internal/flaghelpers/output_pair_flag.go
  fly/commands/internal/flaghelpers/variable_pair_flag.go
  fly/commands/internal/flaghelpers/yaml_variable_pair_flag.go
  fly/commands/internal/flaghelpers/yaml_variable_pair_flag_test.go
  fly/commands/internal/templatehelpers/yaml_template.go
  fly/commands/internal/templatehelpers/yaml_template_test.go
  fly/commands/set_pipeline.go
  fly/commands/validate_pipeline.go
  fly/integration/fixtures/nested-vars-pipeline.yml
  fly/integration/fixtures/vars-pipeline-params-types.yml
  fly/integration/fixtures/vars-pipeline.yml
  fly/integration/set_pipeline_test.go
  vars/named_vars.go
  vars/named_vars_test.go
  vars/reference_test.go
  vars/static_vars.go
  vars/static_vars_test.go
  vars/template.go
  vars/template_test.go
  vars/variables.go
Labels: bug

#6300 `fly set-pipeline` prints pipeline name and instance vars
  fly/commands/internal/setpipelinehelpers/atc_config.go
  fly/integration/set_pipeline_test.go
Labels: enhancement

#6304 `fly intercept` falls back to `sh` when `bash` is missing (containerd runtime)
  testflight/intercept_shell_test.go
  testflight/suite_test.go
  worker/runtime/cni_network_test.go
  worker/runtime/container.go
  worker/runtime/container_test.go
Labels: bug, misc

#5932 Enforce SetPipeline policy check in set_pipeline step
  atc/engine/step_factory.go
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
Labels: enhancement

#6281 atc(feat): master - skip checking put-only resources
  atc/db/build.go
  atc/db/build_test.go
  atc/db/check_factory.go
  atc/db/check_factory_test.go
  atc/db/pipeline_test.go
  atc/db/resource.go
Labels: enhancement

#6320 Fix 'fly sync' Windows tests
  fly/integration/execute_with_outputs_test.go
  fly/integration/sync_test.go
Labels: misc

#6208 feat(atc): support chained container placement strategies.
  atc/atccmd/command.go
  atc/worker/placement.go
  atc/worker/placement_test.go
Labels: enhancement
