Repository concourse/concourse, pull requests merged in 2020-05, with the labels that each got.

#5429 atc/api: limit concurrent requests
  atc/atccmd/command.go
  atc/atccmd/command_test.go
  atc/integration/concurrent_request_limits_test.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/prometheus.go
  atc/metric/metrics.go
  atc/metric/periodic.go
  atc/metric/periodic_test.go
  atc/routes.go
  atc/wrappa/concurrent_request_limits_wrappa.go
  atc/wrappa/concurrent_request_limits_wrappa_test.go
  atc/wrappa/concurrent_request_policy.go
  atc/wrappa/concurrent_request_policy_test.go
  atc/wrappa/pool.go
  atc/wrappa/pool_test.go
  atc/wrappa/wrappafakes/fake_concurrent_request_policy.go
  atc/wrappa/wrappafakes/fake_pool.go
  cmd/concourse/concourse_test.go
  go.mod
  go.sum
  release-notes/latest.md
  topgun/k8s/external_worker_test.go
  topgun/k8s/kubernetes_creds_mgmt_test.go
Labels: core/api, enhancement, release/documented

#5546 atc/db: less cryptic error message
  atc/db/check_factory.go
  testflight/custom_resource_check_test.go
  testflight/resource_type_test.go
Labels: release/no-impact, release/undocumented

#5529 web: improve dashboard UX when ListAllJobs is disabled
  release-notes/latest.md
  web/elm/src/Assets.elm
  web/elm/src/Colors.elm
  web/elm/src/Concourse/PipelineStatus.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Filter.elm
  web/elm/src/Dashboard/Footer.elm
  web/elm/src/Dashboard/Group.elm
  web/elm/src/Dashboard/Group/Models.elm
  web/elm/src/Dashboard/Models.elm
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/src/Dashboard/SearchBar.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/tests/AssetsTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/Data.elm
  web/elm/tests/DragAndDropTests.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/SubPageTests.elm
  web/elm/tests/TopBarTests.elm
  web/public/images/ic-sync.svg
Labels: enhancement, web-ui

#5575 Lidar tracing
  CONTRIBUTING.md
  atc/api/jobserver/create_build.go
  atc/api/resourceserver/check.go
  atc/api/resourceserver/check_resource_type.go
  atc/api/resourceserver/check_webhook.go
  atc/db/check.go
  atc/db/check_factory.go
  atc/db/check_factory_test.go
  atc/db/check_test.go
  atc/db/dbfakes/fake_check.go
  atc/db/dbfakes/fake_check_factory.go
  atc/db/migration/migrations/1588860260_add_span_context_to_checks.down.sql
  atc/db/migration/migrations/1588860260_add_span_context_to_checks.up.sql
  atc/db/span_context.go
  atc/lidar/checker.go
  atc/lidar/lidar.go
  atc/lidar/scanner.go
  tracing/tracer.go
Labels: 6.0-feedback

#5517 Redundant Volume Streaming
  atc/db/dbfakes/fake_created_volume.go
  atc/db/dbfakes/fake_resource_cache_factory.go
  atc/db/resource_cache_factory.go
  atc/db/resource_cache_factory_test.go
  atc/db/volume.go
  atc/worker/artifact_source.go
  atc/worker/artifact_source_test.go
  atc/worker/client.go
  atc/worker/container_test.go
  atc/worker/db_worker_provider.go
  atc/worker/image/image.go
  atc/worker/pool.go
  atc/worker/volume.go
  atc/worker/worker.go
  atc/worker/worker_test.go
  atc/worker/workerfakes/fake_pool.go
  atc/worker/workerfakes/fake_volume.go
  atc/worker/workerfakes/fake_worker.go
  release-notes/latest.md
Labels: 6.0-feedback

#5192 feat(atc): retry build upon worker missing.
  atc/atccmd/command.go
  atc/db/dbfakes/fake_created_container.go
  atc/db/dbfakes/fake_destroying_container.go
  atc/engine/builder/step_factory.go
  atc/engine/engine.go
  atc/exec/put_step.go
  atc/exec/put_step_test.go
  atc/exec/retry_error_step.go
  atc/exec/retry_error_step_test.go
Labels: enhancement, resiliency

#5615 Retry on 503 when concurrent request control enabled
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Models.elm
  web/elm/tests/DashboardTests.elm
Labels: release/documented

#5622 Sort team by name on the UI.
  atc/db/pipeline_factory.go
  atc/db/team.go
  atc/db/team_factory.go
  atc/db/team_factory_test.go
  release-notes/latest.md
Labels: enhancement, web-ui

#5645 atc,tf: structure: robustify active users test
  atc/atccmd/command.go
  atc/integration/active_users_test.go
  testflight/active_users_test.go
Labels: release/no-impact

#5620 Make task vars to be interpolated from var_sources and load_var.
  atc/exec/task_step.go
  release-notes/latest.md
  testflight/fixtures/task_vars.yml
  testflight/task_vars_test.go
Labels: enhancement

#5666 atc: structure: check step runs in the same context as checker
  atc/atccmd/command.go
  atc/builds/tracker.go
  atc/engine/engine.go
  atc/engine/engine_test.go
  atc/engine/enginefakes/fake_runnable.go
  atc/lidar/checker.go
  atc/lidar/checker_test.go
  atc/scheduler/algorithm/suite_test.go
  tracing/tracer.go
  tracing/tracer_test.go
Labels: core/scheduling, refactor, release/no-impact

#5603 web: behaviour: add tooltip to sync icon
  web/elm/src/Application/Application.elm
  web/elm/src/Build/Build.elm
  web/elm/src/Build/Styles.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Models.elm
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/FlySuccess/FlySuccess.elm
  web/elm/src/HoverState.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Message/Callback.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/NotFound/NotFound.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/src/SubPage/SubPage.elm
  web/elm/src/Tooltip.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/DashboardTooltipTests.elm
  web/elm/tests/Data.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/PipelineGridTests.elm
  web/elm/tests/SideBarTests.elm
  web/elm/tests/TooltipTests.elm
Labels: 5.5.11-feedback, enhancement, release/documented, web-ui

#5689 web: behaviour: fresh data over stale
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/tests/DashboardCacheTests.elm
Labels: bug, release/no-impact, web-ui
