Repository concourse/concourse, pull requests merged in 2020-12, with the labels that each got.

#6305 Apply bigint migrations to build_events partitions, remove batch events migrator and read from old/new columns instead, simplify SQL migrations handling
  atc/atccmd/command.go
  atc/component.go
  atc/db/build.go
  atc/db/build_event_source.go
  atc/db/build_test.go
  atc/db/migration/batch/build_events_bigint.go
  atc/db/migration/batch/build_events_bigint_test.go
  atc/db/migration/batch/runner.go
  atc/db/migration/build_events_bigint_test.go
  atc/db/migration/encryption_test.go
  atc/db/migration/migration.go
  atc/db/migration/migration_test.go
  atc/db/migration/migrations/1606068653_build_events_partitions_bigint.down.sql
  atc/db/migration/migrations/1606068653_build_events_partitions_bigint.up.sql
  atc/db/migration/parser.go
  atc/db/migration/parser_test.go
  atc/db/resource.go
  atc/db/resource_test.go
Labels: bug, release/no-impact

#6328 Merge v6.7.2 into master [skip-migrations-check]
  atc/db/build.go
  atc/db/build_test.go
  atc/db/migration/migrations/1601993583_add_instancevars_to_pipelines.down.sql
  atc/db/migration/migrations/1601993583_add_instancevars_to_pipelines.up.sql
  atc/db/migration/migrations/1601993584_add_resource_id_to_builds.down.sql
  atc/db/migration/migrations/1601993584_add_resource_id_to_builds.up.sql
  atc/db/migration/migrations/1601993585_drop_checks.down.sql
  atc/db/migration/migrations/1601993585_drop_checks.up.sql
  atc/db/migration/migrations/1601993586_add_last_referenced_to_resource_configs.down.sql
  atc/db/migration/migrations/1601993586_add_last_referenced_to_resource_configs.up.sql
  atc/db/migration/migrations/1601993587_alter_id_on_builds_bigint.down.sql
  atc/db/migration/migrations/1601993587_alter_id_on_builds_bigint.up.sql
  atc/lidar/scanner.go
  fly/integration/login_test.go
  fly/integration/suite_test.go
  fly/integration/sync_test.go
  fly/integration/version_test.go
  worker/workercmd/guardian.go
Labels: misc

#6332 atc: give worker registration its own dbConn pool
  atc/api/api_suite_test.go
  atc/api/handler.go
  atc/api/workers_test.go
  atc/atccmd/command.go
Labels: enhancement

#6262 Add docker-compose overrides for SAML, LDAP, OAuth, and OIDC
  hack/dc
  hack/ldap/config.ldif
  hack/oidc/config.json
  hack/oidc/users.json
  hack/overrides/ldap.yml
  hack/overrides/oauth.yml
  hack/overrides/oidc.yml
  hack/overrides/saml.yml
Labels: misc, release/no-impact

#6339 atc(feat): add new container placement strategies: limit-max-containers and limit-max-volumes.
  atc/worker/placement.go
  atc/worker/placement_test.go
  atc/worker/worker.go
  atc/worker/workerfakes/fake_worker.go
Labels: enhancement

#6330 start containerd with low oom_score
  worker/runtime/integration/integration_test.go
  worker/workercmd/containerd.go
Labels: bug

#6348 Fix mount issues on containerd
  worker/runtime/spec/mounts.go
  worker/runtime/spec/spec.go
  worker/runtime/spec/spec_test.go
Labels: bug

#6359 atc/worker: fix limit-active-tasks
  atc/worker/client.go
  atc/worker/client_test.go
Labels: bug

#6368 atc(fix): fix an authorization bug, when a user has multiple roles in a team, then it may randomly hit "forbidden" error.
  atc/api/accessor/accessor.go
  atc/api/accessor/accessor_test.go
Labels: bug
