Repository concourse/concourse, pull requests merged in 2020-08, with the labels that each got.

#5861 Allow `fly set-pipeline` to take configuration from stdin
  atc/path_flag.go
  fly/commands/set_pipeline.go
  fly/integration/set_pipeline_test.go
Labels: enhancement, fly

#5946 Remove ignored windows fly test case
  fly/integration/set_pipeline_test.go
Labels: release/no-impact

#5845 TSA uses concourse's gclient with a configurable timeout instead of the cloudfoundry/gardent/client
  release-notes/latest.md
  tsa/cmd/tsa/register_test.go
  tsa/cmd/tsa/suite_test.go
  tsa/heartbeater.go
  tsa/heartbeater_test.go
  tsa/tsacmd/command.go
  tsa/tsacmd/remote_cli.go
  tsa/tsacmd/server.go
Labels: enhancement

#5903 Edit pr template to include new release note generation process
  .github/pull_request_template.md
Labels: release/no-impact

#5951 testflight: prevent pipeline from getting GC'd
  testflight/fixtures/set-pipeline.yml
Labels: release/no-impact

#5950 Remove private_plan from index
  atc/db/migration/migrations/1595347367_add_index_for_unencrypted_private_plans_to_builds.up.sql
Labels: release/no-impact

#5910 Return error when a step only contains modifiers
  atc/steps.go
  atc/steps_test.go
Labels: bug, release/undocumented

#5904 web: favorites pipelines on dashboard pipeline cards
  web/elm/src/Assets.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Group.elm
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Message/Subscription.elm
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/src/SideBar/Views.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/SideBarFeature.elm
Labels: enhancement, favorite-pipelines, web-ui

#5928 Elm tests use Data module for identifiers
  web/elm/tests/ApiEndpointsTests.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/Common.elm
  web/elm/tests/DashboardPreviewTests.elm
  web/elm/tests/DashboardSearchTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/DashboardTooltipTests.elm
  web/elm/tests/Data.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/PauseToggleTests.elm
  web/elm/tests/PinMenu/PinMenuTests.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/PipelineGridTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/ResourceFeature.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/SideBar/PipelineTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/SideBarTests.elm
  web/elm/tests/SubPageTests.elm
  web/elm/tests/TooltipTests.elm
  web/elm/tests/TopBarTests.elm
Labels: release/no-impact

#5961 Bump baggageclaim to v1.8.0 to fix deeply-nested volumes with overlay driver
  go.mod
  go.sum
Labels: bug

#5911 worker: prefix containerd specific flags with CONCOURSE_CONTAINERD
  hack/overrides/containerd.yml
  topgun/k8s/dns_proxy_test.go
  worker/integration/integration_test.go
  worker/workercmd/containerd.go
  worker/workercmd/guardian.go
  worker/workercmd/worker.go
  worker/workercmd/worker_linux.go
  worker/workercmd/worker_nonlinux.go
Labels: breaking

#5965 Use access token for Concourse API in topgun
  topgun/fly.go
Labels: release/no-impact

#5955 Fly commands don't assume tokens are JWTs
  fly/commands/logout.go
  fly/commands/status.go
  fly/commands/targets.go
  fly/integration/delete_target_test.go
  fly/integration/edit_target_test.go
  fly/integration/fixtures/flyrc-badtoken.yml
  fly/integration/fixtures/flyrc.yml
  fly/integration/login_insecure_test.go
  fly/integration/login_test.go
  fly/integration/logout_test.go
  fly/integration/status_test.go
  fly/integration/suite_test.go
  fly/integration/targets_test.go
  fly/rc/target.go
  fly/rc/target_name.go
  fly/rc/targets.go
  fly/rc/targets_test.go
  go-concourse/concourse/teams.go
  go-concourse/concourse/user.go
  go.mod
Labels: release/no-impact

#5958 Rerun builds with baggageclaim network errors
  atc/atccmd/command.go
  atc/engine/engine.go
  atc/exec/aggregate.go
  atc/exec/in_parallel.go
  atc/exec/on_abort.go
  atc/exec/on_error.go
  atc/exec/retry_error_step.go
  atc/exec/retry_error_step_test.go
  atc/exec/timeout_step.go
  atc/exec/try_step.go
Labels: enhancement

#5957 Add flag ` --ignore-event-parsing-errors` to `fly watch` to ignore event parsing errors when an unknown event type or version is encountered.
  fly/commands/watch.go
  fly/eventstream/render.go
  fly/eventstream/render_test.go
Labels: enhancement

#5976 Skip failing k8s topgun tests for containerd without a dns proxy or dns servers configured
  topgun/k8s/dns_proxy_test.go
Labels: bug, release/no-impact

#5983 fix go 1.15 int-to-string conversion warning in tests
  atc/api/auth/check_build_read_access_handler_test.go
  atc/db/worker_lifecycle_test.go
  atc/exec/get_step_test.go
  atc/exec/load_var_step_test.go
  atc/exec/set_pipeline_step_test.go
  atc/exec/task_step_test.go
  atc/scheduler/job_scheduling_test.go
  atc/worker/choose_task_worker_test.go
  atc/worker/client_test.go
Labels: release/no-impact

#5989 fix go 1.15 int-to-string conversion warning
  atc/api/auth/check_build_read_access_handler_test.go
  atc/db/worker_lifecycle_test.go
  atc/exec/get_step_test.go
  atc/exec/load_var_step_test.go
  atc/exec/set_pipeline_step_test.go
  atc/exec/task_step_test.go
  atc/scheduler/job_scheduling_test.go
  atc/worker/choose_task_worker_test.go
  atc/worker/client_test.go
Labels: release/no-impact

#5922 web: favorite pipelines section on dashboard
  web/assets/css/dashboard.less
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Build/Output/Output.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/DashboardPreview.elm
  web/elm/src/Dashboard/Group.elm
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/src/Dashboard/PipelineGrid.elm
  web/elm/src/Dashboard/PipelineGrid/Constants.elm
  web/elm/src/Dashboard/PipelineGrid/Layout.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/SideBar/Pipeline.elm
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/src/SideBar/Team.elm
  web/elm/src/Views/PauseToggle.elm
  web/elm/src/Views/Styles.elm
  web/elm/tests/DashboardPreviewTests.elm
  web/elm/tests/DashboardSearchTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/DashboardTooltipTests.elm
  web/elm/tests/PauseToggleTests.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/PipelineGridLayoutTests.elm
  web/elm/tests/PipelineGridTests.elm
  web/elm/tests/SideBar/PipelineTests.elm
  web/elm/tests/SideBar/TeamTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/SideBarTests.elm
  web/elm/tests/TooltipTests.elm
  web/elm/tests/TopBarTests.elm
Labels: enhancement, favorite-pipelines, web-ui

#5981 tasks scheduling: metrics: enhance TasksWaiting metric.
  atc/metric/emitter/prometheus.go
  atc/metric/emitter/prometheus_test.go
  atc/metric/metrics.go
  atc/metric/periodic.go
  atc/metric/periodic_test.go
  atc/worker/choose_task_worker_test.go
  atc/worker/client.go
  release-notes/latest.md
Labels: enhancement

#5887 Add experimental `across` step for running build plans across a matrix of values
  atc/atccmd/command.go
  atc/builds/planner.go
  atc/builds/planner_test.go
  atc/configvalidate/validate_test.go
  atc/engine/builder/builder.go
  atc/engine/builder/builder_test.go
  atc/engine/builder/builderfakes/fake_delegate_factory.go
  atc/engine/builder/delegate_factory.go
  atc/engine/builder/delegate_factory_test.go
  atc/engine/builder/step_factory.go
  atc/exec/across_step.go
  atc/exec/across_step_test.go
  atc/exec/build_step_delegate.go
  atc/exec/check_step_test.go
  atc/exec/execfakes/fake_build_step_delegate.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/exec/execfakes/fake_get_delegate.go
  atc/exec/execfakes/fake_put_delegate.go
  atc/exec/execfakes/fake_task_delegate.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/exec/load_var_step_test.go
  atc/exec/put_step.go
  atc/exec/put_step_test.go
  atc/exec/set_pipeline_step_test.go
  atc/exec/task_step.go
  atc/exec/task_step_test.go
  atc/feature_flags.go
  atc/plan.go
  atc/plan_factory.go
  atc/public_plan.go
  atc/public_plan_test.go
  atc/resource.go
  atc/step_recursor.go
  atc/step_validator.go
  atc/steps.go
  atc/steps_test.go
  docker-compose.yml
  vars/build_vars.go
  vars/build_vars_test.go
  vars/tracker.go
  vars/variables.go
  vars/vars_tracker.go
  vars/vars_tracker_test.go
  vars/varsfakes/fake_cred_vars_tracker.go
  vars/varsfakes/fake_variables.go
  web/assets/css/production.less
  web/elm/src/Build/Build.elm
  web/elm/src/Build/Models.elm
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Build/Styles.elm
  web/elm/src/Concourse.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Views/LoadingIndicator.elm
  web/elm/tests/BuildStepTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/StepTreeTests.elm
  web/public/elm-setup.js
Labels: enhancement, experiment

#5979 Users can favorite pipelines from pipeline page
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Build/Build.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Filter.elm
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/FlySuccess/FlySuccess.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Login/Login.elm
  web/elm/src/Login/Styles.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/NotFound/NotFound.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Pipeline/Styles.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/SideBar/Pipeline.elm
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/src/Views/FavoritedIcon.elm
  web/elm/tests/DashboardArchiveTests.elm
  web/elm/tests/DashboardCacheTests.elm
  web/elm/tests/DashboardSearchTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/DragAndDropTests.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/PipelineGridTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/SideBar/PipelineTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/TopBarTests.elm
  web/public/elm-setup.js
  web/public/images/baseline-visibility-off.svg
  web/public/images/baseline-visibility.svg
  web/public/images/star-unfilled.svg
Labels: enhancement, favorite-pipelines, web-ui

#5975 Deflake metrics tests
  atc/atccmd/command.go
  atc/builds/tracker.go
  atc/engine/engine.go
  atc/gc/checks_collector.go
  atc/gc/destroyer.go
  atc/gc/worker_collector.go
  atc/lidar/checker.go
  atc/lidar/scanner.go
  atc/metric/emit.go
  atc/metric/emitter/dogstatsd.go
  atc/metric/emitter/influxdb.go
  atc/metric/emitter/lager.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/prometheus.go
  atc/metric/error_sink_collector.go
  atc/metric/error_sink_collector_test.go
  atc/metric/http.go
  atc/metric/http_test.go
  atc/metric/metrics.go
  atc/metric/metrics_test.go
  atc/metric/periodic.go
  atc/metric/periodic_test.go
  atc/metric/query_counter.go
  atc/metric/query_counter_test.go
  atc/scheduler/buildstarter.go
  atc/scheduler/runner.go
  atc/worker/choose_task_worker_test.go
  atc/worker/client.go
  atc/worker/volume_client.go
  atc/worker/worker.go
  atc/wrappa/api_metrics_wrappa.go
  atc/wrappa/concurrent_request_limits_wrappa.go
  atc/wrappa/concurrent_request_limits_wrappa_test.go
Labels: flake, release/no-impact

#5990 Remove unnecessary updates to the resource's `check_error` value
  atc/db/resource.go
Labels: enhancement

#5987 Prevent potential deadlock after pipeline deletion
  atc/atccmd/command.go
  atc/db/db_suite_test.go
  atc/db/dbfakes/fake_pipeline_lifecycle.go
  atc/db/migration/migrations/1597342429_add_deleted_pipelines_table.down.sql
  atc/db/migration/migrations/1597342429_add_deleted_pipelines_table.up.sql
  atc/db/pipeline.go
  atc/db/pipeline_lifecycle.go
  atc/db/pipeline_lifecycle_test.go
  atc/db/pipeline_test.go
  atc/db/team_test.go
  atc/gc/build_log_collector.go
  atc/gc/build_log_collector_test.go
Labels: bug

#6005 Archived pipelines are hidden from sidebar if not favorited
  web/elm/src/SideBar/SideBar.elm
  web/elm/tests/SideBarFeature.elm
Labels: release/no-impact

#6003 Pass user roles to policy checker for API calls
  atc/api/policychecker/checker.go
  atc/api/policychecker/checker_test.go
  atc/policy/checker.go
Labels: enhancement

#5995 atc: Allow OPA integration to return reasons for failures (breaking change)
  atc/api/api_suite_test.go
  atc/api/policychecker/checker.go
  atc/api/policychecker/checker_test.go
  atc/api/policychecker/handler.go
  atc/api/policychecker/handler_test.go
  atc/api/policychecker/policycheckerfakes/fake_policy_checker.go
  atc/policy/checker.go
  atc/policy/checker_test.go
  atc/policy/opa/opa.go
  atc/policy/opa/opa_test.go
  atc/policy/policyfakes/fake_agent.go
  atc/worker/worker.go
  hack/opa/policy.rego
  hack/overrides/opa.yml
Labels: breaking

#6016 atc/db/migration: changd type of id column in resource_config_version…
  atc/db/migration/migrations/1598284990_alter_id_on_resource_config_versions_bigint.down.sql
  atc/db/migration/migrations/1598284990_alter_id_on_resource_config_versions_bigint.up.sql
Labels: release/no-impact

#6002 fly/exec: only upload current directory if it's an input
  fly/commands/internal/executehelpers/inputs.go
  fly/integration/execute_test.go
Labels: bug

#6019 atc: ensure claims LRU cache is safe for concurrent use
  atc/api/accessor/claims_cacher.go
  atc/api/accessor/claims_cacher_test.go
Labels: bug

#6027 Enable fly validate-pipeline to accept "--enable-across-step"
  fly/commands/internal/validatepipelinehelpers/validate.go
  fly/commands/internal/validatepipelinehelpers/validate_test.go
  fly/commands/validate_pipeline.go
Labels: bug
