Repository concourse/concourse, pull requests merged in 2021-02, with the labels that each got.

#6487 hide "group:" dropdown suggestion in search
  web/elm/src/Dashboard/Filter.elm
  web/elm/tests/DashboardSearchBarTests.elm
Labels: misc

#6478 Add additional parameter to oidc SkipEmailVerified to translate it to the dex
  skymarshal/skycmd/oidc_flags.go
Labels: bug

#6497 rename OIDC skip email verified flag
  skymarshal/skycmd/oidc_flags.go
Labels: misc

#6369 feat(atc): expose username of who manually triggered build to build metadata.
  atc/api/accessor/accessor.go
  atc/api/accessor/accessor_factory.go
  atc/api/accessor/accessor_factory_test.go
  atc/api/accessor/accessor_test.go
  atc/api/accessor/accessorfakes/fake_access.go
  atc/api/accessor/handler_test.go
  atc/api/jobserver/create_build.go
  atc/api/jobserver/rerun_build.go
  atc/api/present/build.go
  atc/api/users_test.go
  atc/api/usersserver/get.go
  atc/atccmd/command.go
  atc/atcfakes/fake_display_user_id_generator.go
  atc/build.go
  atc/builds/planner.go
  atc/config.go
  atc/db/access_token.go
  atc/db/build.go
  atc/db/build_factory_test.go
  atc/db/build_test.go
  atc/db/container_repository_test.go
  atc/db/db_suite_test.go
  atc/db/dbfakes/fake_build.go
  atc/db/dbfakes/fake_job.go
  atc/db/dbtest/builder.go
  atc/db/job.go
  atc/db/job_factory.go
  atc/db/job_factory_test.go
  atc/db/job_test.go
  atc/db/migration/migrations/1609959123_add_created_by_to_builds.down.sql
  atc/db/migration/migrations/1609959123_add_created_by_to_builds.up.sql
  atc/db/pipeline_lifecycle_test.go
  atc/db/pipeline_test.go
  atc/db/resource_cache_lifecycle_test.go
  atc/db/resource_config_factory_test.go
  atc/db/team_test.go
  atc/db/versions_db_test.go
  atc/db/worker_lifecycle_test.go
  atc/engine/builder.go
  atc/engine/builder_test.go
  atc/exec/step_metadata.go
  atc/exec/step_metadata_test.go
  atc/gc/resource_cache_collector_test.go
  atc/gc/resource_cache_use_collector_test.go
  atc/plan.go
  atc/user.go
  fly/commands/builds.go
  fly/commands/userinfo.go
  fly/integration/builds_test.go
  fly/integration/userinfo_test.go
  skymarshal/skycmd/flags.go
  skymarshal/skycmd/flags_test.go
  skymarshal/skycmd/skycmd_suite_test.go
  skymarshal/token/access_token.go
  skymarshal/token/access_token_test.go
  testflight/rerun_build_test.go
Labels: enhancement

#6496 Backport https://github.com/concourse/concourse/pull/6478 to 6.7.x branch
  skymarshal/skycmd/oidc_flags.go
Labels: bug

#6489 Optimize postgres runner for db tests
  atc/db/db_suite_test.go
  atc/db/lock/lock_suite_test.go
  atc/db/lock/lock_test.go
  atc/db/migration/migration_suite_test.go
  atc/gc/gc_suite_test.go
  atc/integration/integration_suite_test.go
  atc/integration/team_migration_test.go
  atc/postgresrunner/ginkgo.go
  atc/postgresrunner/postgresrunner.go
  atc/scheduler/algorithm/suite_test.go
  cmd/concourse/concourse_test.go
  skymarshal/dexserver/dexserver_suite_test.go
Labels: misc

#6511 Optimize check deletion
  atc/atccmd/command.go
  atc/db/build.go
  atc/db/check_lifecycle.go
  atc/db/check_lifecycle_test.go
  atc/db/dbfakes/fake_build.go
  atc/db/dbfakes/fake_check_lifecycle.go
  atc/db/migration/migrations/1609958558_add_job_id_to_build_image_resource_caches.down.sql
  atc/db/migration/migrations/1609958558_add_job_id_to_build_image_resource_caches.up.sql
  atc/db/migration/migrations/1612453794_add_builds_resource_type_id_idx.down.sql
  atc/db/migration/migrations/1612453794_add_builds_resource_type_id_idx.up.sql
  atc/db/migration/migrations/1612457776_add_check_build_events_partition.down.sql
  atc/db/migration/migrations/1612457776_add_check_build_events_partition.up.sql
  atc/db/resource.go
  atc/db/resource_test.go
  atc/db/resource_type.go
  atc/db/resource_type_test.go
  atc/gc/check_collector.go
  atc/gc/check_collector_test.go
Labels: misc

#6491 Ignore archived pipelines for instance group count in top bar
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/Views/TopBar.elm
  web/elm/tests/TopBarTests.elm
Labels: bug, misc

#6510 add lock for concourse migrate to latest version cmd
  atc/atccmd/command.go
Labels: bug, enhancement

#6506 metrics: make tasks_wait_duration histogram record up to 1h
  atc/metric/emitter/prometheus.go
Labels: enhancement

#6517 Add index and mini refactor to the check lifecycle query
  atc/db/check_lifecycle.go
  atc/db/migration/migrations/1612565824_add_index_on_build_ids_to_resources.down.sql
  atc/db/migration/migrations/1612565824_add_index_on_build_ids_to_resources.up.sql
Labels: enhancement, misc

#6522 Removes unnecessary indexes from build events tables
  atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.down.sql
  atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.up.sql
  atc/db/migration/migrations/1606068653_build_events_partitions_bigint.down.sql
  atc/db/migration/migrations/1606068653_build_events_partitions_bigint.up.sql
  atc/db/migration/migrations/1612457776_add_check_build_events_partition.down.sql
  atc/db/migration/migrations/1612457776_add_check_build_events_partition.up.sql
Labels: enhancement

#6453 Add more tooltips for action buttons
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Build/Build.elm
  web/elm/src/Build/Header/Header.elm
  web/elm/src/Build/Header/Views.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Build/Styles.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Job/Styles.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Pinned.elm
  web/elm/src/Pipeline/PinMenu/PinMenu.elm
  web/elm/src/Pipeline/PinMenu/Styles.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Resource/Models.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/Resource/Styles.elm
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/src/Tooltip.elm
  web/elm/src/Views/FavoritedIcon.elm
  web/elm/src/Views/Icon.elm
  web/elm/src/Views/PauseToggle.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/Common.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/DashboardTooltipTests.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/PauseToggleTests.elm
  web/elm/tests/PinMenu/PinMenuTests.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/TopBarTests.elm
  web/wats/test/build.js
Labels: enhancement

#6507 worker/runtime: remove no-op device rule
  worker/runtime/spec/devices.go
  worker/runtime/spec/spec.go
  worker/runtime/spec/spec_test.go
Labels: misc

#6516 Change SideBar "menu" icon
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Assets.elm
  web/elm/src/Build/Build.elm
  web/elm/src/Colors.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/NotFound/NotFound.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/tests/AssetsTests.elm
  web/elm/tests/DashboardGridTests.elm
  web/elm/tests/SideBarFeature.elm
  web/public/images/baseline-menu.svg
  web/public/images/baseline-sidebar-closed-grey.svg
  web/public/images/baseline-sidebar-closed-white.svg
  web/public/images/baseline-sidebar-opened-grey.svg
  web/public/images/baseline-sidebar-opened-white.svg
Labels: blocked, enhancement

#6465 Allow favoriting instance groups
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Application/Application.elm
  web/elm/src/Build/Build.elm
  web/elm/src/Concourse.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Drag.elm
  web/elm/src/Dashboard/Filter.elm
  web/elm/src/Dashboard/Grid.elm
  web/elm/src/Dashboard/Group.elm
  web/elm/src/Dashboard/Group/Models.elm
  web/elm/src/Dashboard/InstanceGroup.elm
  web/elm/src/Dashboard/Models.elm
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/Favorites.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Message/Storage.elm
  web/elm/src/Message/Subscription.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/SideBar/InstanceGroup.elm
  web/elm/src/SideBar/Pipeline.elm
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/src/SideBar/Team.elm
  web/elm/src/SideBar/Views.elm
  web/elm/src/Tooltip.elm
  web/elm/tests/ApplicationTests.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/DashboardCacheTests.elm
  web/elm/tests/DashboardInstanceGroupTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/DashboardTooltipTests.elm
  web/elm/tests/DragAndDropTests.elm
  web/elm/tests/InstanceGroupCardTests.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/SideBar/InstanceGroupTests.elm
  web/elm/tests/SideBar/PipelineTests.elm
  web/elm/tests/SideBar/TeamTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/TooltipTests.elm
  web/public/elm-setup.js
Labels: enhancement

#6545 Fix unit test after go 1.16
  fly/rc/target_test.go
Labels: misc

#6553 [Backport 6.7.x] Fix unit test after go 1.16
  fly/rc/target_test.go
Labels: misc

#6554 [Backport 7.0.x] Fix unit test after go 1.16
  fly/rc/target_test.go
Labels: misc

#6573 Skip build log reaping process for paused jobs
  atc/gc/build_log_collector.go
  atc/gc/build_log_collector_test.go
Labels: bug

#6580 default to containerd in docker-compose.yml
  docker-compose.yml
  hack/overrides/containerd.yml
  hack/overrides/guardian.yml
Labels: misc

#6579 Fix "reaped" link in UI
  web/elm/src/Build/Build.elm
Labels: bug
