Repository concourse/concourse, pull requests merged in 2021-04, with the labels that each got.

#6776 Fix race condition in `containerd` runtime resulting in lost output for quickly printing-then-exiting processes
  worker/runtime/integration/testdata/rootfs/.gitignore
  worker/runtime/process.go
  worker/runtime/process_test.go
Labels: bug

#6818 remov --force in k8s topgun test set up
  topgun/k8s/k8s_suite_test.go
Labels: misc, release/no-impact

#6829 Avoid task specific error in `load_var` `file` artifact look-up
  atc/exec/load_var_step.go
  atc/exec/load_var_step_test.go
Labels: misc, release/no-impact

#6841 remove accidentally committed sql in migration
  atc/db/migration/migrations/1606068653_build_events_partitions_bigint.down.sql
  atc/db/migration/migrations/1606068653_build_events_partitions_bigint.up.sql
Labels: misc

#6842 add `release/undocumented` labels to dependabot
  .github/dependabot.yml
Labels: misc, release/no-impact

#6844 .github: add template for rfc tracking issue
  .github/ISSUE_TEMPLATE/release-major-minor.md
  .github/ISSUE_TEMPLATE/release-patch.md
  .github/ISSUE_TEMPLATE/rfc-tracking.md
Labels: misc

#6057 Fix empty worker tags
  atc/worker/worker.go
  atc/worker/worker_test.go
Labels: bug

#6845 Optimize check creation in DB
  atc/db/build.go
  atc/db/resource.go
  atc/db/resource_type.go
Labels: enhancement

#6858 update check metrics comments.
  atc/exec/check_step.go
  atc/metric/emit.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/prometheus.go
Labels: bug

#6870 Remove unused ci folders
  atc/ci/pr
  atc/ci/pr.yml
  fly/ci/build-release
  fly/ci/build-release.yml
  fly/ci/pr
  fly/ci/pr.yml
  go-concourse/ci/pr
  go-concourse/ci/pr.yml
  worker/ci/pr
  worker/ci/pr.yml
Labels: misc, release/no-impact

#6871 Add DB index to optimize paginating job builds
  atc/db/migration/migrations/1618262692_add_order_job_builds_index.down.sql
  atc/db/migration/migrations/1618262692_add_order_job_builds_index.up.sql
Labels: enhancement

#6877 [release/7.2.x] add help text for password connector flag
  skymarshal/skycmd/flags.go
Labels: misc

#6876 add help text for password connector flag
  skymarshal/skycmd/flags.go
Labels: misc

#6878 skip DNS proxy test with extra DNS server
  topgun/k8s/dns_proxy_test.go
Labels: misc

#6848 Add exception handling in bigint migration
  atc/db/migration/migrations/1606068653_build_events_partitions_bigint.up.sql
Labels: misc

#6880 Add trigger for deleting pipeline
  atc/db/migration/migrations/1618347806_add_pipeline_on_delete_trigger.down.sql
  atc/db/migration/migrations/1618347806_add_pipeline_on_delete_trigger.up.sql
  atc/db/pipeline.go
Labels: bug, release/documented

#6885 Optimise fake generation
  atc/db/encryption/strategy.go
  atc/db/lock/lock.go
Labels: misc

#6787 Bump opentelemetry to 0.19.0
  atc/db/build.go
  atc/db/dbfakes/fake_build.go
  atc/db/dbfakes/fake_resource_config_version.go
  atc/db/job_test.go
  atc/db/resource_config_version.go
  atc/db/resource_test.go
  atc/db/resource_type_test.go
  atc/db/span_context.go
  atc/db/versions_db.go
  atc/engine/build_step_delegate.go
  atc/exec/build_step_delegate.go
  atc/exec/check_step_test.go
  atc/exec/execfakes/fake_build_step_delegate.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/exec/execfakes/fake_get_delegate.go
  atc/exec/execfakes/fake_put_delegate.go
  atc/exec/execfakes/fake_set_pipeline_step_delegate.go
  atc/exec/execfakes/fake_task_delegate.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/exec/load_var_step_test.go
  atc/exec/put_step.go
  atc/exec/put_step_test.go
  atc/exec/set_pipeline_step_test.go
  atc/exec/task_step.go
  atc/exec/task_step_test.go
  atc/scheduler/algorithm/group_resolver.go
  atc/scheduler/algorithm/individual_resolver.go
  atc/scheduler/algorithm/pinned_resolver.go
  atc/scheduler/algorithm/table_helpers_test.go
  atc/scheduler/runner.go
  atc/scheduler/scheduler_test.go
  atc/worker/container_spec.go
  go.mod
  go.sum
  hack/otel-collector/otel-collector-config.yml
  hack/overrides/jaeger.yml
  tracing/attrs.go
  tracing/honeycomb.go
  tracing/jaeger.go
  tracing/noop.go
  tracing/otlp.go
  tracing/stackdriver.go
  tracing/tracer.go
  tracing/tracer_test.go
  tracing/tracingfakes/fake_provider.go
  tracing/tracingfakes/fake_span.go
  tracing/tracingfakes/fake_tracer.go
Labels: breaking, misc

#6867 Allow override of container limits in task config
  atc/builds/planner.go
  atc/builds/planner_test.go
  atc/configwarning.go
  atc/exec/task_config_source.go
  atc/exec/task_config_source_test.go
  atc/exec/task_step.go
  atc/exec/task_step_test.go
  atc/plan.go
  atc/steps.go
  atc/steps_test.go
Labels: enhancement

#6834 feat(atc): enhance syslog-drainer to make it more useful
  atc/api/buildserver/eventhandler_test.go
  atc/db/build_event_source.go
  atc/db/build_test.go
  atc/db/pipeline_test.go
  atc/db/team_test.go
  atc/event/parser.go
  atc/syslog/drainer.go
  atc/syslog/drainer_test.go
  atc/syslog/syslog.go
  atc/syslog/syslog_test.go
Labels: enhancement

#6886 Refactor: Pick -> Approve
  atc/worker/placement.go
  atc/worker/placement_test.go
  atc/worker/pool.go
  atc/worker/pool_test.go
  atc/worker/workerfakes/fake_container_placement_strategy.go
Labels: misc, release/no-impact

#6906 re-enable k8s dns proxy test
  topgun/k8s/dns_proxy_test.go
  topgun/tasks/dns-proxy-task.yml
  worker/runtime/cni_network.go
  worker/runtime/cni_network_test.go
  worker/runtime/integration/integration_test.go
  worker/workercmd/dns.go
Labels: misc, release/undocumented

#6902 Fix volume GC query to not include volumes with children
  atc/db/volume_repository.go
  atc/db/volume_repository_test.go
Labels: bug, release/undocumented

#6922 web/wats: replace deprecated waitFor usage
  web/wats/helpers/web.js
  web/wats/test/build.js
  web/wats/test/dashboard.js
  web/wats/test/login.js
  web/wats/test/resource.js
  web/wats/test/smoke.js
Labels: misc

#6918 atc: fix asset leak in api tests
  atc/api/api_suite_test.go
Labels: misc, release/no-impact

#6791 Ensure stdin never errors when using containerd with TTY enabled
  worker/runtime/container.go
  worker/runtime/integration/integration_test.go
  worker/runtime/integration/sample/main.go
  worker/runtime/process.go
  worker/runtime/process_test.go
Labels: bug

#6925 Correct a typo in project documentation
  CONTRIBUTING.md
Labels: misc, release/no-impact

#6873 Use cursor-based pagination for build events
  atc/db/build_event_source.go
Labels: enhancement

#6920 Set autocomplete to off for login form
  skymarshal/dexserver/web/templates/password.html
Labels: bug

#6921 6.7.x - Add autocomplete=off to all form tags
  skymarshal/web/templates/password.html
Labels: bug

#6923 Scan unchecked resource-types
  atc/lidar/scanner.go
  atc/lidar/scanner_test.go
Labels: bug

#6959 [containerd] Ignore "not found" error on process deletion
  worker/runtime/process.go
  worker/runtime/process_test.go
Labels: bug
