Repository concourse/concourse, pull requests merged in 2021-03, with the labels that each got.

#6539 Adjust spacing and padding for elements in pipeline card view in Dashboard
  web/assets/css/dashboard.less
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Grid.elm
  web/elm/src/Dashboard/Grid/Constants.elm
  web/elm/src/Dashboard/Group.elm
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/tests/DashboardGridTests.elm
  web/elm/tests/DashboardInstanceGroupTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/InstanceGroupCardTests.elm
  web/elm/tests/PipelineCardTests.elm
Labels: enhancement

#6598 backport #6197: Prevent retrying on worker error when build is aborted
  atc/exec/retry_error_step.go
  atc/exec/retry_error_step_test.go
Labels: bug

#6603 Check parent resource types
  atc/lidar/scanner.go
  atc/lidar/scanner_test.go
Labels: bug

#6592 containerd: fix mount issues with certain images
  worker/runtime/spec/mounts.go
  worker/runtime/spec/spec_test.go
Labels: bug

#6605 Bump elm-ansi to support 8-bit and 24-bit ANSI colors
  web/elm/elm.json
Labels: bug

#6492 Start non-privileged containers in their own cgroup namespace
  worker/runtime/spec/namespaces.go
Labels: enhancement

#6624 containerd: infer MTU from host's network interface
  integration/docker-compose.yml
  integration/worker/mtu_test.go
  integration/worker/overrides/bridge_mtu.yml
  integration/worker/overrides/custom_mtu.yml
  integration/worker/tasks/assert_mtu.yml
  worker/mtu/mtu.go
  worker/mtu/mtu_test.go
  worker/runtime/cni_network.go
  worker/workercmd/containerd.go
  worker/workercmd/worker_linux.go
Labels: bug

#6643 Bump baggageclaim to v1.11.0
  go.mod
  go.sum
Labels: enhancement

#6621 Show warning for pipelines configured with 'set_pipeline' step
  atc/api/present/pipeline.go
  atc/pipeline.go
  fly/commands/internal/setpipelinehelpers/atc_config.go
  fly/integration/set_pipeline_test.go
Labels: enhancement

#6495 feat(atc): cache streamed volumes and try to get by looking for local cache
  atc/atccmd/command.go
  atc/db/dbfakes/fake_team.go
  atc/db/team.go
  atc/db/team_test.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/metric/emit.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/prometheus.go
  atc/metric/periodic.go
  atc/worker/artifact_destination.go
  atc/worker/artifact_source.go
  atc/worker/artifact_source_test.go
  atc/worker/db_worker_provider.go
  atc/worker/db_worker_provider_test.go
  atc/worker/image/image.go
  atc/worker/pool.go
  atc/worker/pool_test.go
  atc/worker/testhelpers_test.go
  atc/worker/volume.go
  atc/worker/worker.go
  atc/worker/worker_test.go
  atc/worker/workerfakes/fake_artifact_destination.go
  atc/worker/workerfakes/fake_artifact_source.go
  atc/worker/workerfakes/fake_pool.go
  atc/worker/workerfakes/fake_streamable_artifact_source.go
  atc/worker/workerfakes/fake_volume.go
  atc/worker/workerfakes/fake_worker_provider.go
Labels: enhancement

#6659 Revert "feat(atc): cache streamed volumes and try to get by looking for local cache"
  atc/atccmd/command.go
  atc/db/dbfakes/fake_team.go
  atc/db/team.go
  atc/db/team_test.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/metric/emit.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/prometheus.go
  atc/metric/periodic.go
  atc/worker/artifact_destination.go
  atc/worker/artifact_source.go
  atc/worker/artifact_source_test.go
  atc/worker/db_worker_provider.go
  atc/worker/db_worker_provider_test.go
  atc/worker/image/image.go
  atc/worker/pool.go
  atc/worker/pool_test.go
  atc/worker/testhelpers_test.go
  atc/worker/volume.go
  atc/worker/worker.go
  atc/worker/worker_test.go
  atc/worker/workerfakes/fake_artifact_destination.go
  atc/worker/workerfakes/fake_artifact_source.go
  atc/worker/workerfakes/fake_pool.go
  atc/worker/workerfakes/fake_streamable_artifact_source.go
  atc/worker/workerfakes/fake_volume.go
  atc/worker/workerfakes/fake_worker_provider.go
Labels: misc, release/no-impact

#6655 runtime: timeout set to 0 means there is no timeout
  worker/runtime/integration/integration_test.go
  worker/runtime/libcontainerd/client.go
  worker/runtime/libcontainerd/container.go
  worker/runtime/libcontainerd/helper.go
Labels: bug

#6656 feat(atc): add check build metrics.
  atc/builds/tracker.go
  atc/engine/engine.go
  atc/exec/check_step.go
  atc/metric/emit.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/prometheus.go
  atc/metric/metrics.go
  atc/metric/periodic.go
  atc/scheduler/buildstarter.go
Labels: bug, enhancement

#6672 github config updates
  .github/CODEOWNERS
  .github/auto_pr_team.yml
  .github/dependabot.yml
  .github/stale.yml
Labels: misc

#6668 better handling for containerd error message
  worker/runtime/process_killer.go
  worker/runtime/process_killer_test.go
Labels: bug

#6652 runtime: check if swap limits is enabled
  testflight/container_limits_test.go
  worker/runtime/spec/spec.go
  worker/runtime/spec/spec_test.go
Labels: bug

#6700 Add "misc" label to dependabot
  .dockerignore
  .github/dependabot.yml
Labels: misc

#6669 Bump dex to 0.4.0 and remove pkger
  atc/atccmd/command.go
  cmd/concourse/main.go
  cmd/concourse/pkged.go
  go.mod
  go.sum
  skymarshal/dexserver/dexserver.go
  skymarshal/dexserver/web/static/fonts/Inconsolata-Bold.ttf
  skymarshal/dexserver/web/static/fonts/Inconsolata-Regular.ttf
  skymarshal/dexserver/web/static/img/bitbucket-icon.svg
  skymarshal/dexserver/web/static/img/cf-icon.svg
  skymarshal/dexserver/web/static/img/default-icon.svg
  skymarshal/dexserver/web/static/img/github-icon.svg
  skymarshal/dexserver/web/static/img/gitlab-icon.svg
  skymarshal/dexserver/web/static/img/linkedin-icon.svg
  skymarshal/dexserver/web/static/img/microsoft-icon.svg
  skymarshal/dexserver/web/static/img/username-icon.svg
  skymarshal/dexserver/web/static/main.css
  skymarshal/dexserver/web/templates/approval.html
  skymarshal/dexserver/web/templates/device.html
  skymarshal/dexserver/web/templates/device_success.html
  skymarshal/dexserver/web/templates/error.html
  skymarshal/dexserver/web/templates/footer.html
  skymarshal/dexserver/web/templates/header.html
  skymarshal/dexserver/web/templates/login.html
  skymarshal/dexserver/web/templates/oob.html
  skymarshal/dexserver/web/templates/password.html
  skymarshal/dexserver/web/themes/concourse/favicon.png
  skymarshal/dexserver/web/themes/concourse/logo.svg
  skymarshal/dexserver/web/themes/concourse/styles.css
  worker/runtime/libcontainerd/libcontainerdfakes/fake_task.go
Labels: misc

#6716 fix go mod
  go.mod
  go.sum
Labels: misc

#6703 Prevent UI from stalling when you keep the resource page open for a while
  web/elm/src/Resource/Resource.elm
  web/elm/tests/ResourceTests.elm
  web/public/elm-setup.js
Labels: bug

#6717 more lenient context deadline checking for containerd graceful process termination
  worker/runtime/process_killer.go
Labels: misc

#6662 Add ability to navigate to resources page from build page
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Api.elm
  web/elm/src/Build/Output/Models.elm
  web/elm/src/Build/Output/Output.elm
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Concourse.elm
  web/elm/src/Message/Callback.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Pipeline/PinMenu/PinMenu.elm
  web/elm/src/Resource/Models.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/Routes.elm
  web/elm/src/SubPage/SubPage.elm
  web/elm/tests/BuildStepTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/PinMenu/PinMenuTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/RoutesTests.elm
  web/elm/tests/StepTreeTests.elm
  web/elm/tests/SubPageTests.elm
  web/elm/tests/TopBarTests.elm
Labels: enhancement

#6635 Wait for worker matching strategy when scheduling build steps
  atc/atccmd/command.go
  atc/db/dbfakes/fake_worker.go
  atc/db/lock/lock.go
  atc/db/worker.go
  atc/db/worker_test.go
  atc/engine/build_step_delegate.go
  atc/engine/task_delegate.go
  atc/engine/task_delegate_test.go
  atc/event/events.go
  atc/event/parser.go
  atc/event/parser_test.go
  atc/event/types.go
  atc/exec/build_step_delegate.go
  atc/exec/check_step.go
  atc/exec/check_step_test.go
  atc/exec/execfakes/fake_build_step_delegate.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/exec/execfakes/fake_get_delegate.go
  atc/exec/execfakes/fake_put_delegate.go
  atc/exec/execfakes/fake_set_pipeline_step_delegate.go
  atc/exec/execfakes/fake_task_delegate.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/exec/put_step.go
  atc/exec/put_step_test.go
  atc/exec/task_step.go
  atc/exec/task_step_test.go
  atc/metric/emit.go
  atc/metric/emitter/prometheus.go
  atc/metric/emitter/prometheus_test.go
  atc/metric/metrics.go
  atc/metric/periodic.go
  atc/metric/periodic_test.go
  atc/worker/client.go
  atc/worker/client_test.go
  atc/worker/placement.go
  atc/worker/placement_test.go
  atc/worker/pool.go
  atc/worker/pool_test.go
  atc/worker/worker.go
  atc/worker/workerfakes/fake_client.go
  atc/worker/workerfakes/fake_container_placement_strategy.go
  atc/worker/workerfakes/fake_pool.go
  atc/worker/workerfakes/fake_pool_callbacks.go
  atc/worker/workerfakes/fake_worker.go
  fly/eventstream/render.go
  fly/eventstream/render_test.go
  web/elm/src/Build/Output/Output.elm
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Concourse/BuildEvents.elm
Labels: breaking, enhancement

#6739 fix font antialiasing issue due to `less` dependency bump
  web/assets/css/typography.less
Labels: bug, misc

#6754 switch `base_image` build arg to lowercase
  Dockerfile
Labels: misc

#6747 release/6.7.x: check returned error before deferring resp.Body.Close()
  atc/metric/emitter/newrelic.go
Labels: bug

#6746 release/6.7.x: Bump lib/pq to 1.10.0
  go.mod
  go.sum
Labels: bug

#6757 Build image resource caches foreign key constraint to job ids should be on delete cascade
  atc/db/migration/migrations/1616768782_add_job_id_on_delete_cascade_to_build_image_caches.down.sql
  atc/db/migration/migrations/1616768782_add_job_id_on_delete_cascade_to_build_image_caches.up.sql
Labels: bug

#6705 enhance put.inputs detect to ingore prefixed . and ..
  atc/exec/put_inputs.go
  atc/exec/put_step_test.go
  atc/steps.go
Labels: bug

#6760 Don't enforce step timeout during worker selection
  atc/exec/check_step.go
  atc/exec/check_step_test.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/exec/put_step.go
  atc/exec/put_step_test.go
  atc/exec/task_step.go
  atc/exec/task_step_test.go
Labels: bug, misc
