Repository concourse/concourse, pull requests merged in 2021-07, with the labels that each got.

#7238 web: behavior: Fix snake_case method "button_tooltip"
  web/elm/src/Build/Header/Header.elm
Labels: misc

#7236 Left-align job name in build header
  web/elm/src/Build/Header/Views.elm
Labels: misc

#7125 Add page to view all builds/resource versions downstream/upstream from a root resource version
  atc/api/accessor/roles.go
  atc/api/api_suite_test.go
  atc/api/handler.go
  atc/api/info_test.go
  atc/api/infoserver/info.go
  atc/api/resourceserver/versionserver/causality.go
  atc/atccmd/command.go
  atc/auditor/auditor.go
  atc/causality.go
  atc/db/dbfakes/fake_pipeline.go
  atc/db/dbfakes/fake_resource.go
  atc/db/pipeline.go
  atc/db/resource.go
  atc/feature_flags.go
  atc/info.go
  atc/routes.go
  atc/wrappa/api_auth_wrappa.go
  atc/wrappa/reject_archived_wrappa.go
  docker-compose.yml
  fly/rc/target.go
  web/assets/css/production.less
  web/assets/css/svg.less
  web/elm/benchmarks/Benchmarks.elm
  web/elm/elm.json
  web/elm/src/Api/Endpoints.elm
  web/elm/src/Application/Application.elm
  web/elm/src/Application/Models.elm
  web/elm/src/Assets.elm
  web/elm/src/Causality/Causality.elm
  web/elm/src/Causality/DOT.elm
  web/elm/src/Concourse.elm
  web/elm/src/Message/Callback.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/Resource/Styles.elm
  web/elm/src/Routes.elm
  web/elm/src/SubPage/SubPage.elm
  web/elm/src/Views/Styles.elm
  web/elm/src/Views/TopBar.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/CausalityTest.elm
  web/elm/tests/Common.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/Data.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/TopBarTests.elm
  web/public/causality.mjs
  web/public/elm-setup.js
  web/public/graphviz.min.js
  web/public/graphvizlib.wasm
  web/public/images/ic-breadcrumb-causality-downstream.svg
  web/public/images/ic-breadcrumb-causality-upstream.svg
Labels: enhancement

#7218 Apply a minimum rate limit for resource checking
  atc/atccmd/command.go
  atc/db/resource_check_rate_limiter.go
  atc/db/resource_check_rate_limiter_test.go
  atc/engine/check_delegate.go
Labels: bug

#7221 atc/db: prevent creation of duplicate check builds
  atc/db/resource.go
  atc/db/resource_test.go
  atc/db/resource_type.go
  atc/db/resource_type_test.go
Labels: bug

#7249 Fix browser back button after selecting a group
  web/elm/src/Message/Message.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/StrictEvents.elm
Labels: bug

#7247 Use browser cache API for dashboard caching
  web/elm/src/Application/Application.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Storage.elm
  web/elm/src/Message/Subscription.elm
  web/elm/tests/ApplicationTests.elm
  web/elm/tests/DashboardCacheTests.elm
  web/public/elm-setup.js
Labels: enhancement

#7252 Allow interpolation in the across step values
  atc/builds/planner.go
  atc/builds/planner_test.go
  atc/creds/eval.go
  atc/creds/list.go
  atc/creds/list_test.go
  atc/engine/build_step_delegate.go
  atc/engine/build_step_delegate_test.go
  atc/engine/builder.go
  atc/engine/builder_test.go
  atc/event/events.go
  atc/event/parser.go
  atc/event/parser_test.go
  atc/event/types.go
  atc/exec/across_step.go
  atc/exec/across_step_test.go
  atc/exec/build_step_delegate.go
  atc/exec/execfakes/fake_build_step_delegate.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/exec/execfakes/fake_set_pipeline_step_delegate.go
  atc/exec/load_var_step.go
  atc/exec/load_var_step_test.go
  atc/plan.go
  atc/public_plan.go
  atc/public_plan_test.go
  atc/steps.go
  atc/steps_test.go
  testflight/across_test.go
  testflight/fixtures/across.yml
  vars/template.go
  web/elm/src/Build/Output/Output.elm
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Concourse.elm
  web/elm/src/Concourse/BuildEvents.elm
  web/elm/tests/BuildStepTests.elm
  web/elm/tests/Common.elm
  web/elm/tests/StepTreeTests.elm
Labels: enhancement

#7255 `set_pipeline` unpauses previously archived pipelines
  atc/db/build_test.go
  atc/db/team.go
Labels: bug

#7268 Cache the list of workers in memory
  atc/api/accessor/accessorfakes/fake_notifications.go
  atc/api/accessor/teams_cacher.go
  atc/api/accessor/teams_cacher_test.go
  atc/atccmd/command.go
  atc/component/cmocks/Component.go
  atc/component/cmocks/Drainable.go
  atc/component/cmocks/NotificationsBus.go
  atc/component/cmocks/RunFunc.go
  atc/component/cmocks/Runnable.go
  atc/component/cmocks/Schedulable.go
  atc/component/runner.go
  atc/component/runner_test.go
  atc/db/db_suite_test.go
  atc/db/dbtest/builder.go
  atc/db/migration/migrations/1625844436_add_worker_cache_triggers.down.sql
  atc/db/migration/migrations/1625844436_add_worker_cache_triggers.up.sql
  atc/db/notifications_bus.go
  atc/db/notifications_bus_test.go
  atc/db/notifier.go
  atc/db/worker_cache.go
  atc/db/worker_cache_test.go
  atc/db/worker_factory.go
  atc/gc/resource_config_collector_test.go
  atc/gc/volume_collector_test.go
Labels: enhancement

#7276 containerd: Clean up networking files in /tmp
  worker/integration/integration_test.go
  worker/runtime/backend.go
  worker/runtime/cni_network.go
  worker/runtime/cni_network_test.go
  worker/runtime/integration/integration_test.go
  worker/runtime/network.go
  worker/runtime/runtimefakes/fake_network.go
  worker/workercmd/containerd.go
  worker/workercmd/worker_linux.go
Labels: bug

#7272 GC task caches belonging to archived pipelines
  atc/db/dbfakes/fake_task_cache_lifecycle.go
  atc/db/resource_cache_lifecycle.go
  atc/db/task_cache_lifecycle.go
  atc/db/task_cache_lifecycle_test.go
  atc/gc/task_cache_collector.go
  atc/metric/metrics.go
Labels: bug

#7275 Don't include check containers in worker cache
  atc/db/dbtest/builder.go
  atc/db/migration/migrations/1625844436_add_worker_cache_triggers.up.sql
  atc/db/worker_cache.go
  atc/db/worker_cache_test.go
Labels: bug, misc

#7293 [containerd integration] Make host IP parsing more robust
  go.mod
  go.sum
  worker/runtime/integration/integration_test.go
  worker/runtime/integration/suite_test.go
Labels: misc

#7295 Run dependabot at midnight UTC
  .github/dependabot.yml
Labels: misc, release/undocumented

#7288 containerd: split long property values into multiple chunks
  testflight/fixtures/long-metadata.yml
  testflight/regression_test.go
  worker/runtime/backend.go
  worker/runtime/backend_test.go
  worker/runtime/container.go
  worker/runtime/container_test.go
  worker/runtime/integration/integration_test.go
  worker/runtime/properties.go
Labels: bug, misc

#7305 [6.7.x] Bump otel to 0.20.0
  atc/db/build.go
  atc/db/check.go
  atc/db/dbfakes/fake_build.go
  atc/db/dbfakes/fake_check.go
  atc/db/dbfakes/fake_resource_config_version.go
  atc/db/job_test.go
  atc/db/resource_config_version.go
  atc/db/span_context.go
  atc/db/versions_db.go
  atc/exec/check_step_test.go
  atc/exec/exec_suite_test.go
  atc/exec/get_step_test.go
  atc/exec/put_step_test.go
  atc/exec/task_step_test.go
  atc/lidar/checker_test.go
  atc/scheduler/algorithm/group_resolver.go
  atc/scheduler/algorithm/individual_resolver.go
  atc/scheduler/algorithm/pinned_resolver.go
  atc/scheduler/algorithm/suite_test.go
  atc/scheduler/algorithm/table_helpers_test.go
  atc/scheduler/runner.go
  atc/scheduler/scheduler_test.go
  atc/worker/container_spec.go
  go.mod
  go.sum
  tracing/attrs.go
  tracing/jaeger.go
  tracing/noop.go
  tracing/stackdriver.go
  tracing/tracer.go
  tracing/tracer_test.go
  tracing/tracingfakes/fake_provider.go
  tracing/tracingfakes/fake_span.go
  tracing/tracingfakes/fake_tracer.go
Labels: misc, release/undocumented

#7294 Fix prometheus emitter not setting default attributes
  atc/metric/emit.go
  atc/metric/emitter/dogstatsd.go
  atc/metric/emitter/influxdb.go
  atc/metric/emitter/lager.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/newrelic_test.go
  atc/metric/emitter/prometheus.go
  atc/metric/emitter/prometheus_test.go
  atc/metric/metricfakes/fake_emitter_factory.go
Labels: bug, release/undocumented

#7327 Optimize build log collector
  atc/db/pipeline.go
  atc/db/pipeline_test.go
Labels: enhancement

#7334 Optimize build log collector
  atc/db/pipeline.go
  atc/db/pipeline_test.go
Labels: enhancement

#7323 run check builds GC in batch
  atc/db/check_lifecycle.go
  atc/db/check_lifecycle_test.go
  atc/db/dbfakes/fake_check_lifecycle.go
  atc/gc/check_collector.go
Labels: bug

#7310 Properly map `version_from` within `across` substep
  README.md
  atc/builds/planner.go
  atc/builds/planner_test.go
  atc/engine/build_step_delegate.go
  atc/engine/build_step_delegate_test.go
  testflight/across_test.go
  testflight/fixtures/across.yml
Labels: bug, misc

#7338 Enable emitting dogstatsd metrics over uds
  atc/metric/emitter/dogstatsd.go
Labels: enhancement

#7341 Update template
  .github/ISSUE_TEMPLATE/release-major-minor.md
Labels: misc, release/no-impact

#7343 Fix dogstatsd UDS file configuration
  atc/metric/emitter/dogstatsd.go
Labels: bug, misc

#7273 Add audit information for job & pipeline pauses
  atc/api/jobserver/pause_job.go
  atc/api/pipelineserver/pause.go
  atc/api/present/job.go
  atc/api/present/pipeline.go
  atc/db/build_test.go
  atc/db/dbfakes/fake_job.go
  atc/db/dbfakes/fake_pipeline.go
  atc/db/job.go
  atc/db/job_factory.go
  atc/db/job_factory_test.go
  atc/db/job_test.go
  atc/db/migration/migrations/1626194317_add_job_pauses_table.down.sql
  atc/db/migration/migrations/1626194317_add_job_pauses_table.up.sql
  atc/db/migration/migrations/1626194317_add_pipeline_pauses_table.down.sql
  atc/db/migration/migrations/1626194317_add_pipeline_pauses_table.up.sql
  atc/db/pipeline.go
  atc/db/pipeline_test.go
  atc/db/resource_check_rate_limiter_test.go
  atc/db/resource_config_check_session_lifecycle_test.go
  atc/db/team.go
  atc/gc/resource_cache_collector_test.go
  atc/job.go
  atc/pipeline.go
  atc/postgresrunner/join_limit_conn.go
  atc/summary.go
  atc/wrappa/api_auth_wrappa.go
  atc/wrappa/reject_archived_wrappa.go
  fly/commands/fly.go
  fly/commands/paused_jobs.go
  fly/commands/paused_pipelines.go
  go.sum
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Concourse.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Views/Styles.elm
  web/elm/src/Views/TopBar.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/Data.elm
Labels: enhancement

#7347 Don't mount Concourse source directory in `integration` tests
  integration/docker-compose.yml
  integration/worker/overrides/restartable.yml
Labels: misc

#7336 Speed up TSA tests
  atc/worker/gclient/factory.go
  tsa/cmd/tsa/register_test.go
  tsa/cmd/tsa/suite_test.go
Labels: misc

#7307 Propagate groups between subpages of a pipeline
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Application/Application.elm
  web/elm/src/Build/Build.elm
  web/elm/src/Build/Header/Views.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Causality/Causality.elm
  web/elm/src/Dashboard/InstanceGroup.elm
  web/elm/src/Dashboard/Pipeline.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Pipeline/PinMenu/PinMenu.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/Routes.elm
  web/elm/src/Views/TopBar.elm
  web/elm/tests/ApplicationTests.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/PinMenu/PinMenuTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/RoutesTests.elm
  web/elm/tests/SubPageTests.elm
  web/elm/tests/TopBarTests.elm
Labels: enhancement
