Repository concourse/concourse, pull requests merged in 2021-09, with the labels that each got.

#7492 Small team logic refactor - Add team flag to abort-build command
  fly/commands/abort_build.go
  fly/commands/destroy_pipeline.go
  fly/commands/expose_pipeline.go
  fly/commands/get_pipeline.go
  fly/commands/hide_pipeline.go
  fly/commands/hijack.go
  fly/commands/internal/flaghelpers/team_flag.go
  fly/commands/jobs.go
  fly/commands/ordering_pipeline.go
  fly/commands/paused_jobs.go
  fly/commands/set_pipeline.go
  fly/commands/trigger_job.go
  fly/commands/unpause_job.go
  fly/commands/unpause_pipeline.go
  fly/integration/abort_build_test.go
  fly/integration/error_handling_test.go
Labels: enhancement

#7429 Increasing 2px for steps on build log view
  web/elm/src/Build/Styles.elm
  web/elm/tests/BuildTests.elm
Labels: release/no-impact, release/undocumented, misc

#7497 Build page spacing and color theme in general
  web/assets/css/_vars.less
  web/assets/css/build.less
  web/assets/css/layout.less
  web/assets/css/production.less
  web/elm/src/Build/Header/Views.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Build/Styles.elm
  web/elm/src/ColorValues.elm
  web/elm/src/Colors.elm
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/SideBar/Styles.elm
  web/elm/src/Views/Icon.elm
  web/elm/src/Views/LoadingIndicator.elm
  web/elm/tests/BuildStepTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/TopBarTests.elm
  web/wats/helpers/palette.js
  web/wats/test/build.js
  web/wats/test/smoke.js
Labels: enhancement

#7548 Close zstd reader in load var step
  atc/exec/load_var_step.go
  atc/worker/streamer_test.go
  worker/baggageclaim/api/volume_server_test.go
Labels: bug, release/no-impact

#7463 indicate if a pipline is archived in pipeline view
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Build/Build.elm
  web/elm/src/Causality/Causality.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Job/Job.elm
  web/elm/src/NotFound/NotFound.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/Views/Styles.elm
  web/elm/src/Views/TopBar.elm
Labels: enhancement

#7530 atc/gc: make build reaper more robust
  atc/gc/build_log_collector.go
  atc/gc/build_log_collector_test.go
Labels: bug

#7494 Clear resource config scope ID if source field changes
  atc/db/migration/migrations/1630514494_clear_resource_configs_on_update.down.sql
  atc/db/migration/migrations/1630514494_clear_resource_configs_on_update.up.sql
  atc/db/team.go
  atc/db/team_test.go
Labels: bug

#7588 on_error should not run the hook when err is retriable
  atc/exec/on_error.go
  atc/exec/on_error_test.go
Labels: bug

#7591 Bump timeout for volume gc in integration tests
  integration/ops/suite_test.go
Labels: release/no-impact, misc
