Repository concourse/concourse, pull requests merged in 2021-08, with the labels that each got.

#7398 Skip integration downgrade test
  integration/ops/downgrade_test.go
Labels: misc

#7401 Skip integration upgrade test
  integration/ops/upgrade_test.go
Labels: misc

#7360 Bump opentelemetry package to 1.0.0-RC2
  atc/scheduler/algorithm/suite_test.go
  go.mod
  go.sum
  tracing/jaeger.go
  tracing/otlp.go
  tracing/stackdriver.go
  tracing/tracer.go
Labels: release/undocumented, misc

#7427 baggageclaim: prefer overlay over btrfs when using `driver: detect`
  worker/baggageclaim/baggageclaimcmd/driver_linux.go
Labels: breaking

#7370 Don't allow empty identifiers when renaming pipelines/teams
  atc/api/configserver/get.go
  atc/api/configserver/save.go
  atc/api/helpers/helpers.go
  atc/api/pipelines_test.go
  atc/api/pipelineserver/rename.go
  atc/api/teams_test.go
  atc/api/teamserver/rename.go
Labels: bug

#7396 Remove experimental warning for `set_pipeline` and `load_var` steps
  atc/exec/load_var_step.go
  atc/exec/set_pipeline_step.go
Labels: misc

#7369 Fix opening a link to a resource causality page
  atc/api/infoserver/info.go
  atc/feature_flags.go
  web/elm/src/Application/Application.elm
  web/elm/src/Causality/Causality.elm
  web/elm/src/Concourse.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/SubPage/SubPage.elm
  web/elm/tests/ApplicationTests.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/CausalityTest.elm
  web/elm/tests/Common.elm
  web/elm/tests/DashboardArchiveTests.elm
  web/elm/tests/DashboardCacheTests.elm
  web/elm/tests/DashboardGridTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/Data.elm
  web/elm/tests/FlySuccessFeature.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/TopBarTests.elm
  web/index_handler.go
  web/public/index.html
Labels: bug

#7435 Use overlay driver for worker integration test [6.7.x]
  worker/integration/integration_test.go
Labels: misc

#7423 Sanitize prometheus metric labels
  atc/metric/emitter/prometheus.go
  atc/metric/emitter/prometheus_test.go
Labels: bug

#7436 namespace prometheus test to avoid conflict
  atc/metric/emitter/prometheus_test.go
Labels: release/undocumented, misc

#7450 Fix integration upgrade/downgrade tests
  integration/ops/downgrade_test.go
  integration/ops/overrides/fast-gc.yml
  integration/ops/suite_test.go
  integration/ops/upgrade_test.go
Labels: misc

#7449 allow team members to archive pipelines
  atc/api/accessor/roles.go
Labels: breaking

#7438 Optimize pipeline svg rendering
  web/public/graph.mjs
  web/public/index.mjs
Labels: enhancement

#7454 Fix overlapping between inputs and jobs
  web/public/graph.mjs
Labels: bug

#7459 atc: Prevent open redirect to other hosts
  skymarshal/skyserver/skyserver.go
  skymarshal/skyserver/skyserver_test.go
Labels: bug

#7460 6.7.x: Prevent open redirect to other hosts
  skymarshal/skyserver/skyserver.go
  skymarshal/skyserver/skyserver_test.go
Labels: bug

#7461 worker: delete btrfs volume if it exists when using the overlay driver
  worker/baggageclaim/baggageclaimcmd/driver_linux.go
Labels: bug

#7479 fix missing label in metric concourse_steps_waiting
  atc/metric/periodic.go
  atc/metric/periodic_test.go
Labels: bug
