Repository concourse/concourse, pull requests merged in 2021-05, with the labels that each got.

#6854 atc(feat): enhance webhook triggered checks
  atc/db/build.go
  atc/db/build_test.go
  atc/db/dbfakes/fake_build.go
  atc/db/dbfakes/fake_resource_config_scope.go
  atc/db/dbtest/builder.go
  atc/db/migration/migrations/1619180097_add_last_check_succeeded_to_resource_config_scopes.down.sql
  atc/db/migration/migrations/1619180097_add_last_check_succeeded_to_resource_config_scopes.up.sql
  atc/db/resource_config_scope.go
  atc/db/resource_config_scope_test.go
  atc/engine/check_delegate.go
  atc/engine/check_delegate_test.go
  atc/exec/check_step.go
  atc/plan.go
Labels: enhancement

#6947 topgun/k8s: move dns proxy tests to integration
  integration/internal/cmdtest/cmd.go
  integration/worker/dns_test.go
  integration/worker/mtu_test.go
  integration/worker/overrides/add_extra_dns_servers.yml
  integration/worker/overrides/disable_dns_proxy.yml
  integration/worker/overrides/enable_dns_proxy.yml
  integration/worker/tasks/assert_mtu.yml
  integration/worker/tasks/cat_file.yml
  integration/worker/tasks/resolve_web_dns.yml
  topgun/k8s/dns_proxy_test.go
  worker/network/dns.go
  worker/network/mtu.go
  worker/network/mtu_test.go
  worker/workercmd/containerd.go
  worker/workercmd/worker_linux.go
Labels: misc, release/no-impact

#6948 [release/7.2.x] topgun/k8s: move dns proxy tests to integration
  integration/internal/cmdtest/cmd.go
  integration/worker/dns_test.go
  integration/worker/mtu_test.go
  integration/worker/overrides/add_extra_dns_servers.yml
  integration/worker/overrides/disable_dns_proxy.yml
  integration/worker/overrides/enable_dns_proxy.yml
  integration/worker/tasks/assert_mtu.yml
  integration/worker/tasks/cat_file.yml
  integration/worker/tasks/resolve_web_dns.yml
  topgun/k8s/dns_proxy_test.go
  worker/network/dns.go
  worker/network/mtu.go
  worker/network/mtu_test.go
  worker/workercmd/containerd.go
  worker/workercmd/worker_linux.go
Labels: misc, release/no-impact

#6961 Don't check resource-types from paused pipelines
  atc/db/check_factory.go
  atc/db/check_factory_test.go
Labels: misc, release/undocumented

#6971 Using osFlag to fix windows worker error
  fly/integration/ordering_instanced_pipelines_test.go
Labels: misc

#6949 Set Content-Security-Policy and Cache-Control Headers
  atc/atccmd/command.go
  atc/wrappa/security_handler.go
  atc/wrappa/security_handler_test.go
  web/cache_handler.go
Labels: misc

#6967 Add drills environment to major release template
  .github/ISSUE_TEMPLATE/release-major-minor.md
Labels: misc

#6979 [skip-migrations-check] bump `secondary_order` migration
  atc/db/migration/add_secondary_ordering_test.go
  atc/db/migration/migrations/1619180098_add_secondary_order_to_pipelines.down.sql
  atc/db/migration/migrations/1619180098_add_secondary_order_to_pipelines.up.sql
Labels: misc

#6972 contributing: cover governance model, be brief
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: misc

#6660 RE:feat(atc): cache streamed volumes and try to get by looking for local cache
  atc/atccmd/command.go
  atc/db/dbfakes/fake_created_volume.go
  atc/db/dbfakes/fake_team.go
  atc/db/migration/migrations/1619180099_add_worker_name_to_worker_resource_caches.down.sql
  atc/db/migration/migrations/1619180099_add_worker_name_to_worker_resource_caches.up.sql
  atc/db/team.go
  atc/db/team_test.go
  atc/db/volume.go
  atc/db/volume_test.go
  atc/db/worker_base_resource_type.go
  atc/db/worker_resource_cache.go
  atc/db/worker_resource_cache_test.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/metric/emit.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/prometheus.go
  atc/metric/periodic.go
  atc/worker/artifact_destination.go
  atc/worker/artifact_source.go
  atc/worker/artifact_source_test.go
  atc/worker/db_worker_provider.go
  atc/worker/db_worker_provider_test.go
  atc/worker/image/image.go
  atc/worker/image/image_test.go
  atc/worker/pool.go
  atc/worker/pool_test.go
  atc/worker/testhelpers_test.go
  atc/worker/volume.go
  atc/worker/worker.go
  atc/worker/worker_test.go
  atc/worker/workerfakes/fake_artifact_destination.go
  atc/worker/workerfakes/fake_pool.go
  atc/worker/workerfakes/fake_volume.go
  atc/worker/workerfakes/fake_worker_provider.go
  integration/worker/overrides/streamed_resource_cache.yml
  integration/worker/pipelines/streamed_resource_cache.yml
  integration/worker/streamed_resource_cache_test.go
Labels: enhancement

#6982 worker: Set PATH based on UID instead of container's privileged state
  worker/runtime/container.go
  worker/runtime/container_test.go
  worker/runtime/spec/spec.go
  worker/runtime/spec/spec_test.go
Labels: bug

#6970 Using display_user_id field to render username in web interface
  web/elm/src/Concourse.elm
  web/elm/src/Login/Login.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/PauseToggleTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/TopBarTests.elm
  web/elm/tests/UserStateTests.elm
  web/wats/package-lock.json
  web/wats/test/dashboard.js
Labels: enhancement

#7001 Fix bugs related to caching streamed volumes
  atc/atccmd/command.go
  atc/db/migration/migrations/1619180099_add_worker_name_to_worker_resource_caches.up.sql
  atc/db/volume.go
  atc/db/volume_test.go
  atc/db/worker_resource_cache.go
  atc/db/worker_resource_cache_test.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/feature_flags.go
  atc/worker/artifact_destination.go
  atc/worker/artifact_source.go
  atc/worker/artifact_source_test.go
  atc/worker/image/image.go
  atc/worker/testhelpers_test.go
  atc/worker/workerfakes/fake_artifact_destination.go
  atc/worker/workerfakes/fake_volume.go
  integration/internal/dctest/cmd.go
  integration/internal/ypath/ypath.go
  integration/worker/overrides/streamed_resource_cache.yml
  integration/worker/pipelines/streamed_resource_cache.yml
  integration/worker/streamed_resource_cache_test.go
Labels: bug, misc

#7011 Fix Postgres deadlock when frequently setting pipelines
  atc/db/build.go
  atc/db/resource_cache.go
  atc/db/resource_config.go
  atc/db/resource_config_factory.go
  atc/db/team_test.go
Labels: bug

#7024 Fix caching when streamed volume was also streamed
  atc/db/volume.go
  atc/db/volume_test.go
  atc/db/worker_resource_cache.go
  atc/db/worker_resource_cache_test.go
  atc/exec/get_step.go
Labels: bug, misc

#7023 worker/runtime: Don't overwrite $PATH
  worker/runtime/container.go
  worker/runtime/container_test.go
Labels: bug, release/no-impact

#7029 containerd: allow use of non-existent uids
  go.mod
  go.sum
  worker/runtime/rootfs_manager.go
  worker/runtime/rootfs_manager_test.go
Labels: bug

#7040 Upgraded xenial to bionic stemcell
  hack/bosh-topgun
  topgun/deployments/concourse.yml
  topgun/deployments/git-server.yml
  topgun/operations/add-credhub.yml
  topgun/operations/add-empty-credhub.yml
  topgun/operations/add-git-server.yml
  topgun/operations/add-other-worker.yml
  topgun/operations/add-vault.yml
Labels: misc, release/no-impact

#7002 containerd: add flag to allow host access
  worker/runtime/backend.go
  worker/runtime/backend_test.go
  worker/runtime/cni_network.go
  worker/runtime/cni_network_test.go
  worker/runtime/integration/integration_test.go
  worker/runtime/integration/sample/main.go
  worker/runtime/integration/suite_test.go
  worker/runtime/network.go
  worker/runtime/runtimefakes/fake_network.go
  worker/workercmd/containerd.go
  worker/workercmd/worker_linux.go
Labels: breaking, enhancement

#7051 7.3.x: make resource cache streaming opt-in
  atc/atccmd/command.go
  docker-compose.yml
  integration/docker-compose.yml
Labels: misc

#7049 Make caching streamed volumes opt-in
  atc/atccmd/command.go
  docker-compose.yml
  integration/docker-compose.yml
Labels: misc

#7054 Fix capture of failing topgun tests logs
  topgun/common/common.go
Labels: misc, release/no-impact

#7048 bump CoC to 2.0, use @concourse-ci.org emails
  CODE_OF_CONDUCT.md
  SECURITY.md
Labels: misc

#7063 7.3.x: update regex for capturing instances
  topgun/common/common.go
Labels: misc, release/no-impact

#7041 containerd: properly populate /etc/hosts and /etc/hostname
  worker/runtime/backend.go
  worker/runtime/cni_network.go
  worker/runtime/cni_network_test.go
  worker/runtime/file_store.go
  worker/runtime/file_store_test.go
  worker/runtime/integration/integration_test.go
  worker/runtime/network.go
  worker/runtime/runtimefakes/fake_file_store.go
  worker/runtime/runtimefakes/fake_network.go
Labels: bug

#7064 topgun: update regex for capturing instances
  topgun/common/common.go
Labels: misc, release/no-impact

#7058 Cleanup gomod and skip building fly by default in Dockerfile
  .github/ISSUE_TEMPLATE/release-major-minor.md
  Dockerfile
  go.mod
  go.sum
  hack/overrides/with-fly.yml
Labels: misc, release/no-impact

#7078 containerd: update config to v2 format
  worker/workercmd/containerd.go
Labels: misc

#7088 [topgun/k8s] disable container limits fail test
  Dockerfile
  hack/overrides/with-fly.yml
  topgun/k8s/container_limits_test.go
Labels: misc

#7087 [topgun/k8s] disable container limits failure test
  topgun/k8s/container_limits_test.go
Labels: misc

#7003 Fly clear-resource-cache command
  atc/api/accessor/roles.go
  atc/api/handler.go
  atc/api/resources_test.go
  atc/api/resourceserver/clear_resource_cache.go
  atc/auditor/auditor.go
  atc/db/dbfakes/fake_resource.go
  atc/db/resource.go
  atc/db/resource_test.go
  atc/resource_delete_body.go
  atc/responses.go
  atc/routes.go
  atc/wrappa/api_auth_wrappa.go
  atc/wrappa/reject_archived_wrappa.go
  fly/commands/clear_resource_cache.go
  fly/commands/fly.go
  fly/integration/clear_resource_cache_test.go
  go-concourse/concourse/concoursefakes/fake_team.go
  go-concourse/concourse/resource.go
  go-concourse/concourse/resource_test.go
  go-concourse/concourse/team.go
Labels: enhancement

#7089 use `ip` command instead of `ifconfig` in MTU test
  worker/network/mtu_test.go
Labels: misc

#7057 Handle 403 for vault preflight check of V2
  atc/creds/vault/vault_kvhelpers.go
  integration/creds/overrides/vault.yml
  integration/creds/tasks/basic.yml
  integration/creds/vault_test.go
Labels: bug

#7090 atc: across step logs errors
  atc/engine/builder.go
  testflight/build_events_test.go
  testflight/fixtures/erroring_pipeline.yml
Labels: bug, release/undocumented
