Repository concourse/concourse, pull requests merged in 2021-06, with the labels that each got.

#7098 containerd: Mount `/dev/fuse` to privileged containers
  testflight/devices_test.go
  testflight/fixtures/devices.yml
  worker/runtime/spec/devices.go
  worker/runtime/spec/spec.go
Labels: bug

#7114 worker: make containerd the default runtime 🎉
  docker-compose.yml
  worker/workercmd/guardian.go
  worker/workercmd/worker_linux.go
Labels: enhancement

#7120 Fix memory leak in notification bus
  atc/db/notifications_bus.go
  atc/db/notifications_bus_test.go
Labels: bug

#7124 containerd: default to root if /etc/passwd is missing
  testflight/fixtures/clearlinux.yml
  testflight/user_lookup_test.go
  worker/runtime/rootfs_manager.go
Labels: bug

#7127 [release/7.3.x] fix go.sum
  go.sum
Labels: misc

#7126 fix go.sum
  go.sum
Labels: misc

#7108 fix BaseResourceType for streamed volumes
  atc/db/dbtest/builder.go
  atc/db/volume.go
  atc/db/volume_test.go
Labels: bug

#7113 Fix worker restart issue with containerd daemon and beacon
  integration/worker/overrides/broken_containerd_socket.yml
  integration/worker/registration_test.go
  tsa/client.go
  worker/beacon.go
  worker/healthchecker.go
  worker/workercmd/cmd_runner.go
  worker/workercmd/containerd.go
  worker/workercmd/guardian.go
Labels: bug

#7135 Move garden config tests to integration suite
  integration/auth/ldap_test.go
  integration/worker/config/garden.ini
  integration/worker/dns_test.go
  integration/worker/gdn_test.go
  integration/worker/mtu_test.go
  integration/worker/overrides/garden_config.yml
  integration/worker/overrides/garden_max_containers.yml
  integration/worker/overrides/guardian.yml
  integration/worker/streamed_resource_cache_test.go
  topgun/k8s/garden_config_test.go
  worker/workercmd/guardian.go
Labels: bug, misc

#7142 integration: add retries to vault initialization
  integration/internal/cmdtest/cmd.go
  integration/internal/vaulttest/cmd.go
Labels: misc

#7143 integration: fix package name
  integration/worker/registration_test.go
Labels: bug, misc

#7157 [6.7.x]: fix memory leak in notification bus
  atc/db/notifications_bus.go
  atc/db/notifications_bus_test.go
Labels: bug

#7159 Update README to point to GitHub discussions
  README.md
Labels: misc

#7164 [7.3.x] Fix memory leak in notification bus
  atc/db/notifications_bus.go
  atc/db/notifications_bus_test.go
Labels: bug

#7102 atc(fix): fixed a bug in resource check rate limiter.
  atc/db/resource_check_rate_limiter.go
  atc/db/resource_check_rate_limiter_test.go
Labels: bug

#7162 fly: add --team flag to checklist
  fly/commands/checklist.go
  fly/integration/checklist_test.go
  fly/integration/error_handling_test.go
Labels: misc

#7112 Build page shows name of who triggered the build in header line of build page
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Build/Build.elm
  web/elm/src/Build/Header/Header.elm
  web/elm/src/Build/Header/Models.elm
  web/elm/src/Build/Header/Views.elm
  web/elm/src/Build/Models.elm
  web/elm/src/Build/Shortcuts.elm
  web/elm/src/Concourse.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/Common.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/Data.elm
  web/elm/tests/SideBarFeature.elm
Labels: enhancement, web-ui

#7148 containerd: keep tasks running after `concourse worker` restarts gracefully
  integration/docker-compose.yml
  integration/internal/cmdtest/cmd.go
  integration/internal/flytest/cmd.go
  integration/ops/downgrade_test.go
  integration/ops/overrides/named.yml
  integration/ops/upgrade_test.go
  integration/worker/overrides/broken_containerd_socket.yml
  integration/worker/overrides/restartable-entrypoint.sh
  integration/worker/overrides/restartable.yml
  integration/worker/restart_test.go
  integration/worker/tasks/wait.yml
  worker/runtime/container.go
  worker/runtime/container_test.go
  worker/runtime/integration/integration_test.go
  worker/runtime/process.go
  worker/runtime/process_test.go
  worker/workercmd/containerd.go
  worker/workercmd/garden_server_runner.go
  worker/workercmd/houdini.go
Labels: bug

#7144 Fix algorithm considering reruns as new builds
  atc/db/versions_db.go
  atc/db/versions_db_test.go
  atc/scheduler/algorithm/algorithm_test.go
Labels: bug, release/undocumented

#7154 Add teamName to concourse_steps_wait_duration* metrics
  atc/exec/check_step.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/exec/put_step.go
  atc/exec/put_step_test.go
  atc/exec/task_step.go
  atc/metric/emitter/prometheus.go
  atc/metric/emitter/prometheus_test.go
  atc/metric/metrics.go
  atc/worker/container_spec.go
  atc/worker/pool.go
Labels: enhancement

#7179 Fixed build log reaper not respecting when both Days and Builds are set
  atc/gc/build_log_collector.go
  atc/gc/build_log_collector_test.go
Labels: bug

#7184 Reduce number of `JOIN`s in builds query
  atc/db/build.go
  atc/db/build_test.go
  atc/db/dbfakes/fake_build.go
  atc/postgresrunner/join_limit_conn.go
  atc/postgresrunner/join_limit_conn_test.go
  atc/postgresrunner/postgresrunner.go
  atc/postgresrunner/postgresrunner_suite_test.go
Labels: bug, misc

#7211 Treat resource types as checkable in rate limiter
  atc/db/resource_check_rate_limiter.go
  atc/db/resource_check_rate_limiter_test.go
Labels: bug, misc

#7139 Support soft policy enforcement
  atc/api/policychecker/checker.go
  atc/api/policychecker/checker_test.go
  atc/api/policychecker/handler.go
  atc/api/policychecker/handler_test.go
  atc/api/policychecker/policycheckerfakes/fake_policy_checker.go
  atc/engine/build_step_delegate.go
  atc/engine/build_step_delegate_test.go
  atc/engine/delegate_factory.go
  atc/engine/set_pipeline_delegate.go
  atc/engine/set_pipeline_delegate_test.go
  atc/engine/step_factory.go
  atc/exec/build_step_delegate.go
  atc/exec/execfakes/fake_set_pipeline_step_delegate.go
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
  atc/policy/checker.go
  atc/policy/checker_test.go
  atc/policy/opa/opa.go
  atc/policy/opa/opa_test.go
  atc/policy/opa/result.go
  atc/policy/opa/result_test.go
  atc/policy/policyfakes/fake_agent.go
  atc/policy/policyfakes/fake_checker.go
  atc/policy/policyfakes/fake_policy_check_result.go
  go-concourse/concourse/internal/connection.go
  go-concourse/concourse/internal/http_agent.go
  go-concourse/concourse/internal/policy_warn.go
  hack/overrides/opa.yml
Labels: enhancement

#7220 Remove prototype_id from builds table
  atc/db/build.go
  atc/db/check_lifecycle.go
  atc/db/check_lifecycle_test.go
  atc/db/dbfakes/fake_build.go
  atc/db/migration/migrations/1621273969_add_prototypes.down.sql
  atc/db/migration/migrations/1621273969_add_prototypes.up.sql
  atc/db/prototype.go
  atc/db/prototype_test.go
Labels: misc

#7227 Note that all workers need to be on the same network for p2p
  atc/atccmd/command.go
Labels: misc, release/no-impact

#7226 k8s/topgun: use regex to match error message
  topgun/k8s/container_limits_test.go
Labels: misc

#7235 Revert "worker: make containerd the default runtime"
  docker-compose.yml
  worker/workercmd/worker_linux.go
Labels: misc
