Repository concourse/concourse, pull requests merged in 2021-11, with the labels that each got.

#7754 change migrations timestamp to avoid upgrade issues ( CI: skip-migrations-check )
  atc/db/migration/migrations/1625844437_drop_build_event_id_seq.down.sql
  atc/db/migration/migrations/1625844437_drop_build_event_id_seq.up.sql
Labels: bug

#7747 Prefer FLY_HOME over HOME (if set) as the directory for storing .flyrc
  fly/rc/targets.go
  fly/rc/targets_test.go
Labels: enhancement

#7756 Increase color contrast on build page
  web/elm/src/Build/Header/Views.elm
  web/elm/src/Colors.elm
  web/elm/tests/BuildTests.elm
Labels: misc

#7758 Fixes for bugs in 7.4.2
  atc/db/build.go
  atc/db/resource_config.go
Labels: bug

#7730 adding missing prometheus emitters for events
  atc/metric/emitter/emitterfakes/fake_prometheus_garbage_collectable.go
  atc/metric/emitter/prometheus.go
  atc/metric/metrics.go
Labels: enhancement

#7800 remove no needed assertion in topgun runtime
  topgun/runtime/resource_certs_test.go
Labels: misc

#7772 Add team to resource commands and archive pipeline command
  fly/commands/archive_pipeline.go
  fly/commands/check_resource.go
  fly/commands/check_resource_type.go
  fly/commands/resource_versions.go
  fly/commands/resources.go
  fly/integration/archive_pipeline_test.go
  fly/integration/check_resource_test.go
  fly/integration/check_resource_type_test.go
  fly/integration/error_handling_test.go
  fly/integration/resource_versions_test.go
  fly/integration/resources_test.go
Labels: enhancement

#7829 ignore patch release update for aws-sdk-go
  .github/dependabot.yml
Labels: misc

#7840 batch opentelemetry requests
  tracing/tracer.go
Labels: enhancement, release/documented

#7849 ignore gomod patch updateds
  .github/dependabot.yml
Labels: release/no-impact, misc
