Repository concourse/concourse, pull requests merged in 2021-01, with the labels that each got.

#6349 Remove aggregate step
  atc/builds/planner.go
  atc/builds/planner_test.go
  atc/configvalidate/validate_test.go
  atc/engine/builder.go
  atc/engine/builder_test.go
  atc/exec/aggregate.go
  atc/exec/aggregate_test.go
  atc/job_config_test.go
  atc/plan.go
  atc/plan_factory.go
  atc/public_plan.go
  atc/public_plan_test.go
  atc/step_recursor.go
  atc/step_validator.go
  atc/steps.go
  atc/steps_test.go
  fly/commands/internal/executehelpers/builds.go
  fly/integration/execute_multiple_inputs_test.go
  fly/integration/execute_overriding_inputs_test.go
  fly/integration/execute_test.go
  fly/integration/execute_with_outputs_test.go
  go-concourse/concourse/builds_test.go
  go-concourse/concourse/internal/connection_test.go
  go-concourse/concourse/pipelines_test.go
  testflight/fixtures/matrix.yml
  testflight/matrix_test.go
  web/assets/css/modules.less
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Concourse.elm
  web/elm/tests/StepTreeTests.elm
Labels: breaking

#6370 Bump dex to include the XML patch
  go.mod
  go.sum
  skymarshal/dexserver/dexserver.go
Labels: misc

#6329 fly: Add fish auto complete
  fly/commands/completion.go
Labels: enhancement

#6237 Don't enforce timeouts during image fetching
  atc/builds/planner.go
  atc/builds/planner_test.go
  atc/exec/check_step.go
  atc/exec/check_step_test.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/exec/log_error_step.go
  atc/exec/log_error_step_test.go
  atc/exec/maybe_timeout.go
  atc/exec/put_step.go
  atc/exec/put_step_test.go
  atc/exec/task_step.go
  atc/exec/task_step_test.go
  atc/plan.go
  atc/steps.go
  atc/steps_test.go
  atc/worker/client.go
  atc/worker/client_test.go
  atc/worker/workerfakes/fake_client.go
  testflight/resource_check_timeout_test.go
Labels: enhancement

#6392 Deterministic ordering of `?vars` params for instanced pipelines API
  atc/pipeline.go
Labels: bug, misc

#6393 bump baggageclaim to fix nesting again
  go.mod
  go.sum
Labels: bug

#6386 Disable resource checking for individual resources
  atc/api/config_test.go
  atc/api/resources_test.go
  atc/config.go
  atc/config_test.go
  atc/db/check_factory.go
  atc/db/check_factory_test.go
  atc/db/dbfakes/fake_checkable.go
  atc/db/dbfakes/fake_resource.go
  atc/db/dbfakes/fake_resource_type.go
  atc/db/resource.go
  atc/db/resource_test.go
  atc/db/resource_type.go
  atc/db/resource_type_test.go
  atc/lidar/scanner.go
  atc/lidar/scanner_test.go
Labels: enhancement

#6396 Backport #6368 to 6.7.x: fix auth bug
  atc/api/accessor/accessor.go
  atc/api/accessor/accessor_test.go
Labels: bug

#6336 fly(fix): set-pipeline promoted unpause-pipeline command should have --team option.
  fly/commands/internal/setpipelinehelpers/atc_config.go
  fly/commands/internal/setpipelinehelpers/atc_config_test.go
  fly/commands/set_pipeline.go
Labels: bug, fly

#6338 Allow underscore in identifiers
  atc/configvalidate/validate_test.go
  atc/configwarning.go
  atc/configwarning_test.go
Labels: enhancement

#5993 Speed up database queries by adding a `job_id` column to build image resource caches table and adding an index for ordering builds of a job
  atc/db/build.go
  atc/db/migration/migrate_job_id_to_build_image_resource_caches_test.go
  atc/db/migration/migrations/1609958557_add_index_for_ordering_builds.down.sql
  atc/db/migration/migrations/1609958557_add_index_for_ordering_builds.up.sql
  atc/db/migration/migrations/1609958558_add_job_id_to_build_image_resource_caches.down.sql
  atc/db/migration/migrations/1609958558_add_job_id_to_build_image_resource_caches.up.sql
  atc/db/resource_cache_lifecycle.go
Labels: enhancement, needs-more-information

#6406 Backport #6336 to 6.7.x
  fly/commands/internal/setpipelinehelpers/atc_config.go
  fly/commands/internal/setpipelinehelpers/atc_config_test.go
  fly/commands/set_pipeline.go
Labels: bug

#6321 `fly rename-pipeline` can rename an entire instance group
  atc/api/handler.go
  atc/api/pipelines_test.go
  atc/api/pipelineserver/rename.go
  atc/api/team_scoped_handler_factory.go
  atc/api/team_scoped_handler_factory_test.go
  atc/api/teams_test.go
  atc/api/teamserver/destroy.go
  atc/api/teamserver/get.go
  atc/api/teamserver/list_builds.go
  atc/api/teamserver/rename.go
  atc/api/teamserver/set.go
  atc/api/volumes_test.go
  atc/db/dbfakes/fake_pipeline.go
  atc/db/dbfakes/fake_team.go
  atc/db/pipeline.go
  atc/db/pipeline_test.go
  atc/db/team.go
  atc/db/team_test.go
  atc/wrappa/api_auth_wrappa.go
  atc/wrappa/api_auth_wrappa_test.go
  fly/commands/rename_pipeline.go
  fly/integration/rename_pipeline_test.go
  go-concourse/concourse/concoursefakes/fake_team.go
  go-concourse/concourse/pipelines.go
  go-concourse/concourse/pipelines_test.go
  go-concourse/concourse/team.go
Labels: enhancement, misc

#6401 Fix build finished metric for prometheus
  atc/db/build.go
  atc/db/build_test.go
Labels: bug, misc

#6389 Allow underscore in identifiers
  atc/configvalidate/validate_test.go
  atc/configwarning.go
  atc/configwarning_test.go
  web/wats/fixtures/hooks-pipeline.yml
  web/wats/fixtures/pipeline-with-long-output.yml
  web/wats/fixtures/smoke-internet-pipeline.yml
  web/wats/fixtures/states-pipeline.yml
  web/wats/test/smoke.js
Labels: enhancement

#6371 [6.7.x] Bump dex to 2.27.0
  atc/api/accessor/accessor.go
  atc/api/accessor/accessor_factory_test.go
  atc/api/accessor/accessor_test.go
  atc/api/users_test.go
  atc/api/usersserver/get.go
  atc/db/access_token.go
  atc/db/access_token_factory_test.go
  atc/integration/integration_suite_test.go
  cmd/concourse/main.go
  go.mod
  go.sum
  pkged.go
  skymarshal/dexserver/dexserver.go
  skymarshal/skycmd/oauth_flags.go
  skymarshal/skycmd/oidc_flags.go
  skymarshal/storage/storage.go
  skymarshal/token/access_token.go
  skymarshal/web/templates/device.html
  skymarshal/web/templates/device_success.html
Labels: breaking

#6414 Fix archived pipeline check on the resource/job/build page for an instanced pipeline
  web/elm/src/Build/Header/Header.elm
  web/elm/src/Job/Job.elm
  web/elm/src/Resource/Resource.elm
  web/elm/src/Routes.elm
  web/elm/tests/Build/HeaderTests.elm
  web/elm/tests/JobTests.elm
  web/elm/tests/ResourceTests.elm
Labels: bug, misc

#6415 docker: add build arg for base image
  Dockerfile
Labels: misc

#6362 Allow configuring the login and query timeouts for Vault
  atc/atccmd/command.go
  atc/creds/vault/api_client.go
  atc/creds/vault/manager.go
  atc/creds/vault/vault.go
  atc/creds/vault/vault_factory.go
  atc/creds/vault/vault_test.go
Labels: enhancement

#6409 Show instance vars in `set_pipeline` step header
  web/elm/benchmarks/Benchmarks.elm
  web/elm/src/Build/Models.elm
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Build/Styles.elm
  web/elm/src/Concourse.elm
  web/elm/tests/BuildStepTests.elm
  web/elm/tests/BuildTests.elm
  web/elm/tests/StepTreeTests.elm
Labels: bug, misc

#6413 Backport #6362 to 6.7.x: handle slow Vault
  atc/atccmd/command.go
  atc/creds/vault/api_client.go
  atc/creds/vault/manager.go
  atc/creds/vault/vault.go
  atc/creds/vault/vault_factory.go
  atc/creds/vault/vault_test.go
Labels: enhancement

#6442 Add team groups to Dex response for Bitbucket connector
  skymarshal/skycmd/bitbucketcloud_flags.go
Labels: bug, regression

#6444 Add team groups to Dex response for Bitbucket connector
  skymarshal/skycmd/bitbucketcloud_flags.go
Labels: bug, regression

#6426 Add a flag to migrate to the latest db version
  atc/atccmd/command.go
Labels: enhancement

#6410 Ensure task, set_pipeline, load_var steps have names
  atc/api/config_test.go
  atc/api/configserver/save.go
  atc/api/pipelines_test.go
  atc/api/pipelineserver/rename.go
  atc/api/teams_test.go
  atc/api/teamserver/rename.go
  atc/api/teamserver/set.go
  atc/configvalidate/validate.go
  atc/configvalidate/validate_test.go
  atc/configwarning.go
  atc/configwarning_test.go
  atc/step_validator.go
  fly/commands/internal/flaghelpers/pipeline_flag.go
  fly/commands/set_pipeline.go
  fly/commands/set_team.go
Labels: bug

#6436 Proposing fix for OIDC groups
  skymarshal/skycmd/oidc_flags.go
Labels: bug, regression

#6443 make it clear on oidc scopes configuration
  skymarshal/skycmd/oidc_flags.go
Labels: misc

#6449 Remove --force in k8s-topgun test
  topgun/k8s/k8s_suite_test.go
Labels: misc

#6448 Fix OIDC connector not fetching groups claim
  skymarshal/skycmd/oidc_flags.go
Labels: bug

#6115 atc: behavior: Implement support for Vault KV v2 backends
  atc/creds/vault/api_client.go
  atc/creds/vault/vault_kvhelpers.go
  atc/creds/vault/vault_test.go
  go.mod
  go.sum
Labels: enhancement

#6450 Optimize fly windows tests
  fly/commands/sync.go
  fly/commands/version.go
  fly/integration/execute_with_outputs_test.go
  fly/integration/sync_test.go
  fly/integration/version_test.go
  fly/rc/target.go
Labels: misc

#6433 Enhance search bar filtering and allow filtering by instance group
  web/elm/src/Application/Application.elm
  web/elm/src/Concourse.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Filter.elm
  web/elm/src/Dashboard/FilterBuilder.elm
  web/elm/src/Dashboard/Footer.elm
  web/elm/src/Dashboard/InstanceGroup.elm
  web/elm/src/Dashboard/Models.elm
  web/elm/src/Dashboard/SearchBar.elm
  web/elm/src/Routes.elm
  web/elm/src/SideBar/InstanceGroup.elm
  web/elm/src/SideBar/SideBar.elm
  web/elm/src/SideBar/Team.elm
  web/elm/src/SubPage/SubPage.elm
  web/elm/src/Views/TopBar.elm
  web/elm/tests/ApplicationTests.elm
  web/elm/tests/Common.elm
  web/elm/tests/DashboardArchiveTests.elm
  web/elm/tests/DashboardInstanceGroupTests.elm
  web/elm/tests/DashboardSearchBarTests.elm
  web/elm/tests/DashboardSearchTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/InstanceGroupCardTests.elm
  web/elm/tests/PipelineCardTests.elm
  web/elm/tests/ResourceTests.elm
  web/elm/tests/RoutesTests.elm
  web/elm/tests/SideBarFeature.elm
  web/elm/tests/TopBarTests.elm
  web/elm/tests/WelcomeCardTests.elm
Labels: enhancement

#6412 db: lidar checks put-only resources with failed checks
  atc/db/check_factory.go
  atc/db/check_factory_test.go
  atc/db/resource.go
Labels: enhancement

#6457 Fix an ATC crash caused by parallel `load_var` steps
  vars/build_vars.go
Labels: bug

#6461 Fix an ATC crash caused by parallel `load_var` steps
  atc/exec/build_vars.go
Labels: bug

#6481 Skip Vault tests in Topgun
  topgun/core/vault_test.go
Labels: misc

#6480 backport pkger fix to 6.7.x
  cmd/concourse/main.go
  cmd/concourse/pkged.go
  pkged.go
Labels: bug

#6482 move pkged.go to cmd/concourse/
  cmd/concourse/main.go
  cmd/concourse/pkged.go
  pkged.go
Labels: misc

#6483 runtime: add test coverage for container.Stop()
  worker/runtime/container_test.go
Labels: misc
