Repository concourse/concourse, pull requests merged in 2022-02, with the labels that each got.

#7874 Optimize limit active tasks strategy logic
  atc/db/dbfakes/fake_worker.go
  atc/db/worker.go
  atc/db/worker_test.go
  atc/worker/gardenruntime/gardenruntimetest/worker.go
  atc/worker/placement.go
  atc/worker/placement_test.go
Labels: misc

#7922 Do not send check build events to syslog drainer
  atc/db/build_factory.go
  atc/db/build_factory_test.go
Labels: release/documented, misc

#7978 GC builds based on chronological order
  atc/db/build_factory.go
  atc/db/dbfakes/fake_job.go
  atc/db/job.go
  atc/db/job_test.go
  atc/db/pipeline.go
  atc/db/team.go
  atc/gc/build_log_collector.go
  atc/gc/build_log_collector_test.go
Labels: bug, release/documented

#8032 bump golang crypto lib
  go.mod
  go.sum
Labels: release/no-impact, misc

#7989 gc task cache from paused pipeline
  atc/db/dbtest/builder.go
  atc/db/task_cache_lifecycle.go
  atc/db/task_cache_lifecycle_test.go
Labels: enhancement, release/documented

#8069 Render nested across steps
  web/elm/src/Build/StepTree/Models.elm
Labels: bug, release/documented

#8050 bump concourse dex by upstream v2.31.0
  go.mod
  go.sum
  skymarshal/dexserver/dexserver.go
  skymarshal/dexserver/dexserver_test.go
Labels: bug, release/documented

#8081 bump worker version to 2.4
  versions.go
Labels: release/undocumented, misc

#8082 Fix syntax error in down migration file
  atc/db/migration/migrations/1625844436_add_worker_cache_triggers.down.sql
Labels: bug, release/documented

#8098 worker: Fix log line in stream out
  worker/baggageclaim/volume/repository.go
Labels: bug, logging, release/no-impact

#8061 Ignore cached input from volume-locality's consideration
  atc/engine/build_step_delegate.go
  atc/engine/build_step_delegate_test.go
  atc/engine/task_delegate_test.go
  atc/exec/artifact_input_step.go
  atc/exec/artifact_input_step_test.go
  atc/exec/artifact_output_step.go
  atc/exec/artifact_output_step_test.go
  atc/exec/build/repository.go
  atc/exec/build/repository_test.go
  atc/exec/get_step.go
  atc/exec/get_step_test.go
  atc/exec/load_var_step.go
  atc/exec/load_var_step_test.go
  atc/exec/put_inputs.go
  atc/exec/put_step_test.go
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
  atc/exec/task_config_source.go
  atc/exec/task_config_source_test.go
  atc/exec/task_step.go
  atc/exec/task_step_test.go
  atc/metric/emitter/prometheus.go
  atc/runtime/types.go
  atc/worker/placement.go
  atc/worker/placement_test.go
Labels: enhancement, release/documented

#8128 Allow text whitespace to be preserved in step metadata
  web/elm/src/Build/Styles.elm
Labels: enhancement, release/documented

#8063 Enhance volume-locality strategy
  atc/db/dbfakes/fake_volume_repository.go
  atc/db/volume_repository.go
  atc/worker/placement.go
  atc/worker/placement_test.go
Labels: enhancement
