Repository concourse/concourse, pull requests merged in 2022-08, with the labels that each got.

#8500 Fix a bad SQL for check gc.
  atc/db/check_lifecycle.go
Labels: bug

#8504 Reduce redundant job schedule
  atc/db/build_test.go
  atc/db/resource_config_scope.go
  atc/db/resource_config_scope_test.go
Labels: enhancement

#8528 Use pq.Array to avoid hitting parameter limits
  atc/db/pipeline.go
  atc/db/pipeline_test.go
Labels: bug

#8511 Add renovate rule for k8s client-go lib
  .github/renovate.json
Labels: misc
