Repository concourse/concourse, pull requests merged in 2022-05, with the labels that each got.

#8323 Follow credhub-cli impl to determin find result
  atc/creds/credhub/credhub.go
Labels: bug

#8183 Add no-input-strategy and let get/check use it.
  atc/atccmd/command.go
  atc/engine/step_factory.go
  atc/exec/check_step.go
  atc/exec/check_step_test.go
  atc/worker/placement.go
  atc/worker/placement_test.go
  atc/worker/pool_test.go
Labels: enhancement

#8306 Inherite env proxy configure when tls enabled
  atc/atccmd/command.go
Labels: bug, release/documented

#8002 Fix #7468: Reset resource config IDs on save
  atc/db/build_test.go
  atc/db/team.go
  atc/db/team_test.go
Labels: bug

#8322 Depop avoid duplicating parallel volume streams
  atc/db/lock/lock.go
  atc/engine/build_step_delegate.go
  atc/engine/build_step_delegate_test.go
  atc/event/events.go
  atc/event/parser.go
  atc/event/types.go
  atc/exec/build_step_delegate.go
  atc/exec/execfakes/fake_build_step_delegate.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/exec/execfakes/fake_get_delegate.go
  atc/exec/execfakes/fake_put_delegate.go
  atc/exec/execfakes/fake_set_pipeline_step_delegate.go
  atc/exec/execfakes/fake_task_delegate.go
  atc/exec/get_step.go
  atc/exec/put_step.go
  atc/exec/task_step.go
  atc/runtime/types.go
  atc/syslog/drainer.go
  atc/worker/gardenruntime/gardenruntimetest/baggageclaim.go
  atc/worker/gardenruntime/gardenruntimetest/worker.go
  atc/worker/gardenruntime/image.go
  atc/worker/gardenruntime/worker.go
  atc/worker/gardenruntime/worker_test.go
  fly/eventstream/render.go
  fly/eventstream/render_test.go
  web/elm/src/Build/Output/Output.elm
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Concourse/BuildEvents.elm
Labels: enhancement

#8324 Bump vault api and add srv lookup flag
  atc/creds/vault/api_client.go
  atc/creds/vault/manager.go
  atc/creds/vault/manager_test.go
  atc/creds/vault/vault_test.go
  go.mod
  go.sum
Labels: misc

#8343 Fix fly integration test in window OS
  fly/integration/clear_versions_test.go
Labels: bug, misc

#8344 fix fly integration test in window OS
  fly/integration/clear_versions_test.go
Labels: misc

#8342 Force checks on nested resource types when manually triggered build
  atc/api/jobserver/create_build.go
  atc/builds/planner.go
  atc/builds/planner_test.go
  atc/engine/task_delegate.go
  atc/engine/task_delegate_test.go
  atc/exec/execfakes/fake_task_delegate.go
  atc/exec/task_step.go
  atc/exec/task_step_test.go
  atc/plan.go
  atc/scheduler/buildstarter.go
  atc/scheduler/buildstarter_test.go
  atc/scheduler/schedulerfakes/fake_build_planner.go
Labels: enhancement

#8354 update togun tests due to pr #8342
  topgun/both/resource_types_test.go
Labels: misc

#8362 Fix default username prompt for local logins
  skymarshal/dexserver/web/templates/password.html
Labels: bug

#8353 Introduce OIDC get user info flag
  skymarshal/skycmd/oidc_flags.go
Labels: bug

#8363 don't force resource type check on get step
  atc/builds/planner.go
  atc/builds/planner_test.go
Labels: misc

#8365 completely revert change in topgun resource types test
  topgun/both/resource_types_test.go
Labels: misc

#8366 update topgun resource types test to match behaviour
  topgun/both/resource_types_test.go
Labels: misc

#8271 fix #8268 acrossStep handling for more then 3 vars
  atc/exec/across_step.go
  atc/exec/across_step_test.go
Labels: bug

#8184 optimize worker selection
  atc/worker/pool.go
Labels: enhancement

#7955 do not cache secrets indefinitely
  atc/creds/vault/api_client.go
  atc/creds/vault/vault.go
  atc/creds/vault/vault_test.go
Labels: bug, breaking
