Repository concourse/concourse, pull requests merged in 2022-01, with the labels that each got.

#7886 fix fly hijack due to containerd runc update
  fly/commands/internal/hijacker/hijacker.go
Labels: misc

#7895 atc/db: Refactor pipeline lifecycle
  atc/db/pipeline.go
  atc/db/pipeline_lifecycle.go
  atc/db/pipeline_lifecycle_test.go
Labels: misc

#7860 Fix down migration for build event sequences
  atc/db/migration/migrations/1625844437_drop_build_event_id_seq.down.sql
Labels: bug, release/documented

#7913 Porting down migration improvements for build event sequences
  atc/db/migration/migrations/1630515499_drop_build_event_id_seq.down.sql
Labels: bug

#7926 bump to go 1.17 in go.mod and add goproxy in dockerfile
  Dockerfile
  go.mod
  go.sum
Labels: release/no-impact, misc

#7928 shared (top level) secrets in AWS secrets manager
  atc/api/info_test.go
  atc/creds/secretsmanager/manager.go
  atc/creds/secretsmanager/manager_test.go
  atc/creds/secretsmanager/secretsmanager_test.go
Labels: enhancement

#7932 Remove unused gc job dropped metric
  atc/metric/metrics.go
Labels: misc

#7933 (AWS Secrets Manager) should treat marked for deletion as deleted
  atc/creds/secretsmanager/secretsmanager.go
  atc/creds/secretsmanager/secretsmanager_test.go
Labels: bug

#7897 aws secretsmanager can be used from var_sources
  atc/configvalidate/validate.go
  atc/creds/secretsmanager/manager.go
  atc/creds/secretsmanager/manager_factory.go
Labels: enhancement

#7965 Avoid stale prometheus worker metrics when using multiple web nodes
  atc/metric/emitter/emitterfakes/fake_prometheus_garbage_collectable.go
  atc/metric/emitter/prometheus.go
Labels: bug

#7920 worker: Only delete btrfs mounts if *.img exists
  worker/baggageclaim/baggageclaimcmd/driver_linux.go
Labels: bug

#7942 fixed a bug of p2p streaming for handling huge volumes.
  go.sum
  worker/baggageclaim/api/volume_server.go
  worker/baggageclaim/api/volume_server_test.go
  worker/baggageclaim/client/client.go
  worker/baggageclaim/client_test.go
  worker/baggageclaim/volume/repository.go
Labels: bug, release/documented

#7971 fix windows baggageclaim test
  worker/baggageclaim/api/volume_server_test.go
Labels: misc

#7987 run task caches collector when atc starts
  atc/atccmd/command.go
  atc/component.go
Labels: bug, release/documented
