Repository concourse/concourse, pull requests merged in 2022-03, with the labels that each got.

#8048 fix bug of nested check
  atc/engine/check_delegate.go
  atc/engine/check_delegate_test.go
  atc/exec/check_step.go
  atc/exec/check_step_test.go
  atc/plan.go
Labels: bug

#8142 Force get and check to use "fewest-build-containers" strategy.
  atc/atccmd/command.go
  atc/engine/step_factory.go
  atc/worker/placement.go
Labels: enhancement

#8092 Render build page correctly for legacy aggregate step
  web/assets/css/modules.less
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/src/Concourse.elm
  web/elm/tests/StepTreeTests.elm
Labels: bug, release/documented

#8137 Automatic pipeline archiver accidentally archives child pipelines during a build run
  atc/db/pipeline_lifecycle.go
  atc/db/pipeline_lifecycle_test.go
Labels: release/no-impact, misc

#8149 Fix topgun resource types test failure
  topgun/both/resource_types_test.go
  topgun/pipelines/custom-types.yml
Labels: misc

#8171 add --team to fly watch
  fly/commands/watch.go
  fly/integration/error_handling_test.go
  fly/integration/watch_test.go
Labels: enhancement

#8179 Automatic pipeline archiver archiving child pipelines when parent job has a failed/errored build
  atc/db/pipeline_lifecycle.go
  atc/db/pipeline_lifecycle_test.go
Labels: bug

#8200 Fix automatic pipeline archive bug
  atc/db/pipeline_lifecycle.go
  atc/db/pipeline_lifecycle_test.go
Labels: bug

#8203 Backport allow go 1.18 darwin error message in unit tests
  fly/integration/login_insecure_test.go
Labels: misc

#8202 Allow go 1.18 darwin error message in unit test
  fly/integration/login_insecure_test.go
Labels: misc

#8015 Show var source error on resource and build page
  atc/db/build_in_memory_check.go
  atc/db/build_in_memory_check_test.go
  atc/db/migration/migrations/1645735232_add_in_memory_build_status_to_resources.down.sql
  atc/db/migration/migrations/1645735232_add_in_memory_build_status_to_resources.up.sql
  atc/db/resource.go
  atc/db/resource_test.go
  web/elm/src/Build/StepTree/Models.elm
  web/elm/src/Build/StepTree/StepTree.elm
  web/elm/tests/StepTreeTests.elm
Labels: bug, release/documented
