Repository concourse/concourse, pull requests merged in 2022-11, with the labels that each got.

#8609 Bump runtimes deps 6.8
  atc/db/worker_test.go
  atc/scheduler/algorithm/suite_test.go
  go.mod
  go.sum
  skymarshal/skycmd/cf_flags.go
  skymarshal/skycmd/oidc_flags.go
  topgun/k8s/container_limits_test.go
  tracing/jaeger.go
  tracing/stackdriver.go
  tracing/tracer.go
  worker/runtime/backend.go
  worker/runtime/runtimefakes/fake_cni.go
Labels: misc

#8611 Container limit tests fix for v6.8.0
  topgun/k8s/container_limits_test.go
Labels: misc

#8612 add buildvcs=false to go build in integration tests v6.8.x
  fly/integration/suite_test.go
  worker/baggageclaim/integration/baggageclaim/suite_test.go
  worker/baggageclaim/integration/fs_mounter/suite_test.go
Labels: misc

#8620 Fixed a bug of leaking resource cofig scope ids.
  atc/db/resource_config.go
  atc/db/resource_config_test.go
Labels: bug

#8626 Remove rerun_of int->bigint migrations
  atc/db/migration/migrations/1653924132_int_to_bigint.down.sql
  atc/db/migration/migrations/1653924132_int_to_bigint.up.sql
Labels: misc

#8613 Performance optimize on accessor.
  atc/api/accessor/accessor.go
Labels: enhancement

#8494 Add --check-container-placement-strategy.
  atc/atccmd/command.go
  atc/engine/step_factory.go
  atc/exec/check_step.go
  atc/exec/check_step_test.go
  atc/worker/placement.go
  atc/worker/placement_test.go
  atc/worker/pool_test.go
Labels: enhancement

#8588 stream: Adding new NextEventRaw method
  go-concourse/concourse/events.go
  go-concourse/concourse/eventstream/stream.go
Labels: enhancement

#8387 load_var to support var interpolate
  atc/creds/load_var_plan.go
  atc/creds/load_var_plan_test.go
  atc/exec/load_var_step.go
Labels: enhancement

#8634 fix across step states bug
  web/elm/src/Build/StepTree/Models.elm
Labels: bug
