Repository concourse/concourse, pull requests merged in 2022-07, with the labels that each got.

#8463 Port 8453
  atc/db/component.go
  atc/db/component_test.go
Labels: enhancement, release/no-impact

#8468 add missed lock metrics.
  atc/metric/metrics.go
Labels: bug, release/no-impact

#8433 Turn off connection tracker by default and provide an option to turn on.
  atc/atccmd/command.go
  atc/db/connection_tracker.go
  atc/db/open.go
Labels: bug

#8461 Enhance Vault API client to auto retry upon rate limit.
  atc/creds/vault/api_client.go
  go.mod
  go.sum
Labels: enhancement

#8467 Don’t use ‘here’ as link text
  web/elm/src/Dashboard/Dashboard.elm
Labels: misc

#8485 remove "check build started/finished" metrics.
  atc/engine/engine.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/prometheus.go
  atc/metric/metrics.go
Labels: enhancement

#8495 Rotate vault certs for dev
  hack/vault/certs/concourse.crt
  hack/vault/certs/concourse.csr
  hack/vault/certs/concourse.key
  hack/vault/certs/vault-ca.crl
  hack/vault/certs/vault-ca.crt
  hack/vault/certs/vault-ca.key
  hack/vault/certs/vault.crt
  hack/vault/certs/vault.csr
  hack/vault/certs/vault.key
Labels: misc

#8493 check build should not auto retry.
  atc/engine/engine.go
  atc/engine/engine_test.go
Labels: bug

#8481 Enhance Vault API client to auto retry upon rate limit.
  atc/creds/vault/api_client.go
  go.mod
  go.sum
Labels: enhancement, release/no-impact

#8480 Turn off connection tracker by default and provide an option to turn on.
  atc/atccmd/command.go
  atc/db/connection_tracker.go
  atc/db/open.go
Labels: enhancement, release/no-impact

#8506 Fix json syntax error to enable Renovate bot
  .github/renovate.json
Labels: misc
