Repository concourse/concourse, pull requests merged in 2022-10, with the labels that each got.

#8578 rotate vault certs for dev
  hack/vault/certs/concourse.crt
  hack/vault/certs/concourse.csr
  hack/vault/certs/concourse.key
  hack/vault/certs/vault-ca.crl
  hack/vault/certs/vault-ca.crt
  hack/vault/certs/vault-ca.key
  hack/vault/certs/vault.crt
  hack/vault/certs/vault.csr
  hack/vault/certs/vault.key
Labels: misc

#8566 Fix team_name overwritten bug
  atc/api/auth/check_pipeline_access_handler.go
  atc/api/pipelineserver/reject_archived_handler_factory.go
  atc/api/pipelineserver/scoped_handler_factory.go
  atc/api/pipelineserver/scoped_handler_factory_test.go
  atc/api/policychecker/checker.go
  atc/api/policychecker/checker_test.go
  atc/api/team_scoped_handler_factory.go
  atc/api/teamserver/set.go
Labels: bug

#8580 fix team_name overwritten bug
  atc/api/auth/check_pipeline_access_handler.go
  atc/api/pipelineserver/reject_archived_handler_factory.go
  atc/api/pipelineserver/scoped_handler_factory.go
  atc/api/pipelineserver/scoped_handler_factory_test.go
  atc/api/policychecker/checker.go
  atc/api/policychecker/checker_test.go
  atc/api/team_scoped_handler_factory.go
  atc/api/teamserver/set.go
Labels: bug

#8579 Bump dex for release v7.8.x
  go.mod
  go.sum
Labels: misc

#8584 atc/db/lock: preallocate memory
  atc/db/lock/lock.go
Labels: enhancement

#8577 New pipelines without build should be paused automatically with a configurable interval.
  atc/db/pipeline_pauser.go
Labels: enhancement

#8590 refactor dns package and test
  integration/internal/cmdtest/cmd.go
  integration/worker/dns_test.go
  integration/worker/overrides/add_extra_dns_servers.yml
  integration/worker/overrides/disable_dns_proxy.yml
  integration/worker/overrides/enable_dns_proxy.yml
  integration/worker/tasks/cat_file.yml
  integration/worker/tasks/resolve_web_dns.yml
  topgun/k8s/dns_proxy_test.go
  worker/network/dns.go
  worker/workercmd/worker_linux.go
Labels: misc

#8594 Fix bug in testflight suite env var assignment
  testflight/suite_test.go
Labels: bug, ci

#8598 Update path for example pipeline
  CONTRIBUTING.md
Labels: misc

#8601 Revert PR #8504 reduce-redundant-schedule
  atc/db/build_test.go
  atc/db/resource_config_scope.go
  atc/db/resource_config_scope_test.go
Labels: bug

#8606 Change id of table resource_config_scopes to bigint
  atc/db/migration/migrations/1666743327_alter_id_on_resource_config_scopes_bigint.down.sql
  atc/db/migration/migrations/1666743327_alter_id_on_resource_config_scopes_bigint.up.sql
Labels: enhancement
