Repository concourse/concourse, pull requests merged in 2023-01, with the labels that each got.

#8486 Fixed a bug where invalidated worker resource caches are not GC-ed
  atc/db/dbfakes/fake_created_volume.go
  atc/db/dbfakes/fake_resource_cache_lifecycle.go
  atc/db/dbfakes/fake_team.go
  atc/db/dbfakes/fake_volume_repository.go
  atc/db/migration/migrations/1666754000_add_invalid_since_to_worker_resource_caches.down.sql
  atc/db/migration/migrations/1666754000_add_invalid_since_to_worker_resource_caches.up.sql
  atc/db/resource_cache_lifecycle.go
  atc/db/resource_cache_lifecycle_test.go
  atc/db/resource_test.go
  atc/db/team.go
  atc/db/team_test.go
  atc/db/volume.go
  atc/db/volume_repository.go
  atc/db/volume_repository_test.go
  atc/db/volume_test.go
  atc/db/worker_resource_cache.go
  atc/db/worker_resource_caches_test.go
  atc/engine/build_step_delegate.go
  atc/exec/build_step_delegate.go
  atc/exec/execfakes/fake_build_step_delegate.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/exec/execfakes/fake_get_delegate.go
  atc/exec/execfakes/fake_pool.go
  atc/exec/execfakes/fake_put_delegate.go
  atc/exec/execfakes/fake_set_pipeline_step_delegate.go
  atc/exec/execfakes/fake_task_delegate.go
  atc/exec/get_step.go
  atc/exec/put_step.go
  atc/exec/step.go
  atc/exec/task_step.go
  atc/gc/resource_cache_collector.go
  atc/runtime/runtimetest/volume.go
  atc/runtime/types.go
  atc/worker/gardenruntime/volume.go
  atc/worker/gardenruntime/worker.go
  atc/worker/gardenruntime/worker_test.go
  atc/worker/placement_test.go
  atc/worker/pool.go
  atc/worker/pool_test.go
  atc/worker/streamer.go
  atc/worker/streamer_test.go
Labels: bug

#8665 security golang dep bumps
  go.mod
  go.sum
Labels: misc

#8666 Bump dex to latest
  go.mod
  go.sum
  skymarshal/skycmd/cf_flags.go
  skymarshal/skycmd/oidc_flags.go
Labels: misc

#8670 Fix baggageclaim and container limit tests in k8s-topgun
  topgun/k8s/baggageclaim_drivers_test.go
  topgun/k8s/container_limits_test.go
Labels: misc

#8044 add seccomp profile, hooks dir override for containerd
  worker/runtime/backend.go
  worker/runtime/backend_test.go
  worker/runtime/spec/seccomp.go
  worker/runtime/spec/spec.go
  worker/runtime/spec/spec_test.go
  worker/workercmd/containerd.go
  worker/workercmd/worker_linux.go
Labels: enhancement
