Repository concourse/concourse, pull requests merged in 2023-07, with the labels that each got.

#8786 chore: unnecessary use of fmt.Sprintf or fmt.Sprint
  atc/db/check_factory_test.go
  fly/integration/clear_versions_test.go
  fly/integration/disable_resource_version_test.go
  fly/integration/enable_resource_version_test.go
  fly/integration/pin_resource_test.go
  go-concourse/concourse/builds_test.go
  go-concourse/concourse/jobs_test.go
  go-concourse/concourse/pipelines_test.go
  topgun/both/volume_gc_test.go
Labels: misc

#8678 atc/db: fix dropped error
  atc/db/resource.go
Labels: bug

#8736 Optimize db notify.
  atc/atccmd/command.go
  atc/component.go
  atc/db/build.go
  atc/db/build_being_watched_marker.go
  atc/db/build_being_watched_marker_test.go
  atc/db/build_event_source.go
  atc/db/build_in_memory_check.go
  atc/db/build_test.go
  atc/db/check_factory.go
  atc/db/dbfakes/fake_check_factory.go
  atc/db/notifications_bus.go
  atc/lidar/scanner.go
Labels: enhancement
