Repository concourse/concourse, pull requests merged in 2023-10, with the labels that each got.

#8809 make cc.xml endpoint public, and only list public pipelines
  atc/api/cc_test.go
  atc/api/ccserver/get.go
  atc/wrappa/api_auth_wrappa.go
Labels: enhancement

#8832 Fix data race in emmiter and pool unit tests
  atc/metric/emitter/newrelic_test.go
  atc/worker/pool_test.go
  integration/pauser/images/postgres.Dockerfile
Labels: misc

#8834 Fix integration flaky ops parallel upgrade/downgrade tests
  integration/ops/downgrade_test.go
  integration/ops/overrides/named-downgrade.yml
  integration/ops/overrides/named-upgrade.yml
  integration/ops/upgrade_test.go
Labels: misc

#8838 Fix integration flaky ops test
  integration/ops/downgrade_test.go
  integration/ops/overrides/named-downgrade.yml
  integration/ops/overrides/named.yml
  integration/ops/upgrade_test.go
Labels: misc

#8826 Emitting "latest_completed_build_status" gauge from prometheus
  atc/db/dbfakes/fake_job.go
  atc/db/job.go
  atc/db/job_test.go
  atc/engine/engine.go
  atc/metric/emit.go
  atc/metric/emitter/prometheus.go
  atc/metric/emitter/prometheus_test.go
  atc/metric/metrics.go
Labels: enhancement

#8841 Fix fly builds cmd with --team flag
  fly/commands/builds.go
  fly/integration/builds_test.go
Labels: bug

#8850 Backport 7.11
  .github/renovate.json
  atc/metric/emitter/prometheus.go
  fly/commands/builds.go
  fly/commands/execute.go
  fly/commands/internal/executehelpers/downloads.go
  fly/commands/internal/executehelpers/inputs.go
  fly/commands/internal/executehelpers/uploads.go
  fly/commands/sync.go
  fly/integration/builds_test.go
  fly/ui/progress/progress.go
  go.mod
  go.sum
  topgun/k8s/k8s_suite_test.go
Labels: misc
