Repository concourse/concourse, pull requests merged in 2023-05, with the labels that each got.

#8709 Add a drift based number of goroutines to component scheduler.
  atc/atccmd/command.go
  atc/db/component.go
  atc/db/component_factory.go
  atc/db/component_test.go
  atc/db/db_suite_test.go
  atc/db/dbfakes/fake_component_rand.go
  atc/db/dbfakes/fake_goroutine_counter.go
  atc/db/resource_cache.go
  atc/util/util_suite_test.go
  go.mod
  go.sum
Labels: enhancement

#8740 Increase timeout for bosh topgun
  atc/db/notifications_bus_test.go
  topgun/common/common.go
Labels: misc

#8746 Fixed a race condition in component factory.
  atc/atccmd/command.go
  atc/db/component_factory.go
Labels: bug, release/no-impact

#8751 Bump ifrit to fix ATC gracefully terminate issue.
  go.mod
  go.sum
Labels: bug
