Repository concourse/concourse, pull requests merged in 2023-09, with the labels that each got.

#8806 Fixes cf authentication fails on 7.9.1 #8696
  atc/api/accessor/accessor.go
  atc/api/accessor/accessor_test.go
  skymarshal/dexserver/dexserver.go
  skymarshal/skycmd/cf_flags.go
  skymarshal/skycmd/flags.go
Labels: bug

#8810 Bump imdario/mergo to v1.0.0
  go.mod
  go.sum
  worker/runtime/spec/spec.go
Labels: misc

#8811 bump concourse/retryhttp to v1.2.4
  go.mod
  go.sum
Labels: release/undocumented, misc

#8812 bump concourse/flag to v2.0.2
  go.mod
  go.sum
Labels: release/undocumented, misc

#8799 Fix 404 links to blog posts
  README.md
Labels: misc

#8813 bump txn2/txeh to v1.5.4
  go.mod
  go.sum
  worker/runtime/file_store.go
Labels: release/undocumented, misc

#8822 Topgun gc_interval to gc.interval
  topgun/operations/fast-gc.yml
  topgun/operations/no-gc.yml
Labels: misc
