Repository concourse/concourse, pull requests merged in 2024-11, with the labels that each got.

#9022 merging main back into master
  LICENSE.md
  NOTICE.md
  docker-compose.yml
  go-concourse/LICENSE
  go.mod
  go.sum
  integration/docker-compose.yml
  package.json
  skymarshal/NOTICE
  testflight/LICENSE
  testflight/container_limits_test.go
  topgun/k8s/dns_proxy_test.go
  topgun/k8s/k8s_suite_test.go
  topgun/k8s/kubernetes_creds_mgmt_test.go
  tsa/cmd/tsa/suite_test.go
  web/wats/package.json
  web/wats/yarn.lock
  worker/workercmd/garden_server_runner.go
  yarn.lock
Labels: release/undocumented

#9024 Revert "bump go dependencies"
  go.mod
  go.sum
Labels: release/undocumented

#9028 fix: topgun k8s container limits test supports cgroups v1 and v2
  topgun/k8s/container_limits_test.go
Labels: release/undocumented, misc

#9010 Split go-concourse client tests
  go-concourse/concourse/internal/connection.go
  go-concourse/concourse/internal/connection_test.go
  go-concourse/concourse/internal/http_agent_test.go
  go-concourse/concourse/internal/internalfakes/fake_connection.go
Labels: misc

#9011 go-concourse:connection client prints response body to the end user
  go-concourse/concourse/internal/connection.go
  go-concourse/concourse/internal/connection_test.go
Labels: enhancement
