Repository concourse/concourse, pull requests merged in 2024-04, with the labels that each got.

#8856 `fly`: add `background` option to `execute` command
  fly/commands/execute.go
  testflight/flying_test.go
Labels: enhancement

#8381 Add resource type check interval
  atc/atccmd/command.go
  atc/builds/planner_test.go
  atc/db/check_factory.go
  atc/db/check_factory_test.go
  atc/db/db_suite_test.go
  atc/resourcecheck.go
Labels: enhancement

#8933 Add `--team` flag to `clear-task-cache` command
  fly/commands/clear_task_cache.go
  fly/integration/clear_task_cache_test.go
  fly/integration/error_handling_test.go
Labels: enhancement

#8946 Fix integration test failure due to deprecated docker-compose
  go.mod
  go.sum
  integration/auth/overrides/ldap.yml
  integration/creds/overrides/vault-token.yml
  integration/creds/overrides/vault.yml
  integration/docker-compose.yml
  integration/internal/dctest/cmd.go
  integration/ops/downgrade_test.go
  integration/ops/overrides/fast-gc.yml
  integration/ops/overrides/latest.yml
  integration/ops/overrides/named.yml
  integration/ops/suite_test.go
  integration/ops/upgrade_test.go
  integration/overrides/expose.yml
  integration/pauser/overrides/five-days-ago.yml
  integration/pauser/overrides/pauser-config.yml
  integration/pauser/overrides/short-pauser-interval.yml
  integration/worker/overrides/add_extra_dns_servers.yml
  integration/worker/overrides/bridge_mtu.yml
  integration/worker/overrides/broken_containerd_socket.yml
  integration/worker/overrides/custom_mtu.yml
  integration/worker/overrides/disable_dns_proxy.yml
  integration/worker/overrides/empty_tag.yml
  integration/worker/overrides/enable_dns_proxy.yml
  integration/worker/overrides/garden_config.yml
  integration/worker/overrides/garden_max_containers.yml
  integration/worker/overrides/guardian.yml
  integration/worker/overrides/restartable.yml
  integration/worker/registration_test.go
Labels: misc

#8948 chore: fix function name in comment
  atc/exec/set_pipeline_step.go
  worker/runtime/integration/integration_test.go
  worker/runtime/killer.go
Labels: release/undocumented, misc

#8940 Add --team flag to rename-pipeline command
  fly/commands/rename_pipeline.go
  fly/integration/error_handling_test.go
  fly/integration/rename_pipeline_test.go
Labels: enhancement
