Repository concourse/concourse, pull requests merged in 2024-02, with the labels that each got.

#8904 Rotate dev vault certs
  hack/vault/certs/README.md
  hack/vault/certs/concourse.crt
  hack/vault/certs/concourse.csr
  hack/vault/certs/extfile-concourse.cnf
  hack/vault/certs/extfile-vault.cnf
  hack/vault/certs/vault-ca.crt
  hack/vault/certs/vault-ca.srl
  hack/vault/certs/vault.crt
  hack/vault/certs/vault.csr
Labels: misc

#8909 Rebase master 7.11.2
  go.mod
  go.sum
  hack/vault/certs/README.md
  hack/vault/certs/concourse.crt
  hack/vault/certs/concourse.csr
  hack/vault/certs/extfile-concourse.cnf
  hack/vault/certs/extfile-vault.cnf
  hack/vault/certs/vault-ca.crt
  hack/vault/certs/vault-ca.srl
  hack/vault/certs/vault.crt
  hack/vault/certs/vault.csr
Labels: security, misc

#8801 Implement support for IPv6 networking in tasks
  docker-compose.yml
  worker/runtime/cni_network.go
  worker/runtime/cni_network_test.go
  worker/workercmd/containerd.go
  worker/workercmd/worker_linux.go
Labels: enhancement

#8899 Load vault client token from file
  atc/creds/vault/api_client.go
  atc/creds/vault/manager.go
  atc/creds/vault/manager_test.go
  hack/vault/init
  integration/creds/overrides/vault-token.yml
  integration/creds/vault_test.go
  integration/internal/flytest/cmd.go
Labels: enhancement, go
