Repository concourse/concourse, pull requests merged in 2025-01, with the labels that each got.

#9009 Correct policy-checker test suite names
  atc/api/policychecker/policychecker_suite_test.go
  atc/policy/opa/agent_suite_test.go
Labels: misc

#9012 improve the error message given to the end user when setting the pipeline
  fly/integration/set_pipeline_test.go
  go-concourse/concourse/configs.go
  go-concourse/concourse/configs_test.go
Labels: enhancement

#9013 Log policy checker error messages
  atc/api/policychecker/handler.go
  atc/api/policychecker/handler_test.go
  atc/policy/opa/opa.go
  atc/policy/opa/opa_test.go
  atc/policy/opa/result.go
Labels: enhancement

#9051 8529/fix chrome login
  fly/commands/login.go
  fly/integration/login_test.go
  package.json
  yarn.lock
Labels: bug

#9021 Replace md5 with sha256 algorithm
  atc/db/build.go
  atc/db/build_test.go
  atc/db/dbtest/builder.go
  atc/db/job.go
  atc/db/job_test.go
  atc/db/migration/migrations/1728989566_switch_md5_to_sha256.down.sql
  atc/db/migration/migrations/1728989566_switch_md5_to_sha256.up.sql
  atc/db/pipeline.go
  atc/db/pipeline_test.go
  atc/db/resource.go
  atc/db/resource_cache_factory.go
  atc/db/resource_cache_factory_test.go
  atc/db/resource_cache_lifecycle.go
  atc/db/resource_cache_lifecycle_test.go
  atc/db/resource_config_scope.go
  atc/db/versions_db.go
  atc/db/versions_db_test.go
  atc/gc/resource_cache_collector_test.go
  atc/scheduler/algorithm/firstoccurrence_test.go
  atc/scheduler/algorithm/migration_test.go
  atc/scheduler/algorithm/table_helpers_test.go
  web/index_handler.go
Labels: enhancement

#9059 Bump Dex and other dependencies
  atc/hijack_payload.go
  atc/runtime/types.go
  atc/worker/gardenruntime/gclient/retryable_garden_connection_test.go
  fly/commands/hijack.go
  fly/commands/internal/hijacker/hijacker.go
  go.mod
  go.sum
  skymarshal/dexserver/dexserver.go
  skymarshal/dexserver/dexserver_test.go
  skymarshal/storage/storage.go
  worker/workercmd/houdini.go
Labels: dependencies, misc
