Repository concourse/concourse, pull requests merged in 2025-07, with the labels that each got.

#9224 Improve idtoken credential provider compatibility (with AWS and Azure)
  atc/api/idtokenserver/openid_discovery.go
  atc/creds/idtoken/lifecycle.go
Labels: bug

#9146 fix(container): optimize executable detection with pre-compiled regexps
  worker/runtime/container.go
  worker/runtime/resolvconf_parser.go
Labels: misc, ignore-for-release

#9148 refactor: replace map+RWMutex with sync.Map in artifact repository for better concurrency
  atc/exec/build/repository.go
  atc/exec/build/repository_test.go
Labels: misc

#9155 Replace urljoiner dependency with standard library URL handling
  fly/integration/set_pipeline_test.go
  go.mod
  go.sum
Labels: misc, ignore-for-release

#9157 Replace manual mutex+map with sync.Map for connection tracking
  atc/db/connection_tracker.go
Labels: misc, ignore-for-release

#9161 refactor: beingWatchedBuildEventChannelMap to use sync.Map
  atc/db/build_being_watched_marker.go
Labels: misc

#9163 Improve error handling in DestroyVolume unmount operation
  worker/baggageclaim/volume/driver/overlay_linux.go
Labels: misc, ignore-for-release

#9166 refactor: simplify hasPermission method in accessor
  atc/api/accessor/accessor.go
Labels: misc

#9169 Optimize SSE build event streaming
  atc/api/buildserver/eventhandler.go
Labels: misc

#9230 Increase containerd runner ready state timeout
  integration/worker/registration_test.go
  worker/workercmd/containerd.go
Labels: misc

#9231 Bump containerd libraries to v2
  go.mod
  go.sum
  worker/runtime/backend.go
  worker/runtime/backend_test.go
  worker/runtime/cni_network.go
  worker/runtime/container.go
  worker/runtime/container_test.go
  worker/runtime/integration/integration_test.go
  worker/runtime/killer.go
  worker/runtime/killer_test.go
  worker/runtime/libcontainerd/client.go
  worker/runtime/libcontainerd/container.go
  worker/runtime/libcontainerd/libcontainerdfakes/fake_client.go
  worker/runtime/libcontainerd/libcontainerdfakes/fake_container.go
  worker/runtime/libcontainerd/libcontainerdfakes/fake_io.go
  worker/runtime/libcontainerd/libcontainerdfakes/fake_process.go
  worker/runtime/libcontainerd/libcontainerdfakes/fake_task.go
  worker/runtime/network.go
  worker/runtime/process.go
  worker/runtime/process_killer.go
  worker/runtime/process_killer_test.go
  worker/runtime/process_test.go
  worker/runtime/properties.go
  worker/runtime/rootfs_manager.go
  worker/runtime/runtimefakes/fake_killer.go
  worker/runtime/runtimefakes/fake_network.go
  worker/runtime/runtimefakes/fake_process_killer.go
  worker/runtime/spec/spec.go
  worker/runtime/spec/spec_test.go
  worker/workercmd/containerd.go
Labels: misc

#9235 runtime: remove guardian as a runtime option for linux/arm64
  worker/workercmd/worker_linux.go
  worker/workercmd/worker_linux_amd64.go
  worker/workercmd/worker_linux_arm64.go
Labels: misc

#9234 runtime/containerd: ensure logs are not dropped when web node re-attaches to running containers
  integration/docker-compose.yml
  integration/internal/flytest/cmd.go
  integration/ops/overrides/ha-web-nodes.yml
  integration/ops/overrides/nginx.conf
  integration/ops/pipelines/stream-logs.yml
  integration/ops/restarting_web_nodes_test.go
  worker/runtime/backend.go
  worker/runtime/backend_test.go
  worker/runtime/container.go
  worker/runtime/container_test.go
  worker/runtime/io_manager.go
  worker/runtime/io_manager_test.go
  worker/runtime/runtimefakes/fake_io.go
  worker/runtime/runtimefakes/fake_iomanager.go
  worker/runtime/suite_test.go
Labels: bug

#9240 Add /download-fly page for downloading the fly cli
  web/assets/css/download-fly.less
  web/assets/css/footer.less
  web/assets/css/main.less
  web/elm/elm.json
  web/elm/src/Assets.elm
  web/elm/src/Concourse/Cli.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Dashboard/Footer.elm
  web/elm/src/Dashboard/Styles.elm
  web/elm/src/Dashboard/Text.elm
  web/elm/src/DownloadFly/DownloadFly.elm
  web/elm/src/DownloadFly/Model.elm
  web/elm/src/Message/Effects.elm
  web/elm/src/Message/Message.elm
  web/elm/src/Message/Subscription.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Pipeline/Styles.elm
  web/elm/src/Routes.elm
  web/elm/src/SubPage/SubPage.elm
  web/elm/src/Views/Styles.elm
  web/elm/src/Views/TopBar.elm
  web/elm/tests/AssetsTests.elm
  web/elm/tests/CliTests.elm
  web/elm/tests/DashboardInstanceGroupTests.elm
  web/elm/tests/DashboardTests.elm
  web/elm/tests/DownloadFlyTests.elm
  web/elm/tests/PipelineTests.elm
  web/elm/tests/WelcomeCardTests.elm
  web/public/elm-setup.js
  web/public/images/apple-logo.svg
  web/public/images/console.svg
  web/public/images/file-document.svg
  web/public/images/linux-logo.svg
  web/public/images/windows-logo-white-ic.svg
  web/public/images/windows-logo.svg
Labels: enhancement

#9247 update web dependencies
  package-lock.json
  web/wats/package-lock.json
  web/wats/yarn.lock
  yarn.lock
Labels: misc
