Repository concourse/concourse, pull requests merged in 2025-02, with the labels that each got.

#9061 Properly close process IO
  worker/runtime/process.go
  worker/runtime/process_test.go
Labels: bug

#9071 Fix double locking in volume promise
  worker/baggageclaim/volume/promise.go
Labels: misc

#9070 Update gzhttp library
  atc/wrappa/compression_wrappa.go
  go.mod
  go.sum
  web/cache_handler.go
Labels: misc

#9068 Remove CONCOURSE_POSTGRES_BINARY_PARAMETERS flag
  go.mod
  go.sum
Labels: misc

#9072 Use filepath.Walkdir
  atc/api/handler.go
  atc/builds/buildsfakes/fake_engine.go
  atc/builds/buildsfakes/fake_runnable.go
  atc/builds/tracker.go
  atc/component/cmocks/Component.go
  atc/component/cmocks/Drainable.go
  atc/component/cmocks/NotificationsBus.go
  atc/component/cmocks/RunFunc.go
  atc/component/cmocks/Runnable.go
  atc/component/cmocks/Schedulable.go
  atc/exec/execfakes/fake_build_step_delegate.go
  atc/exec/execfakes/fake_check_delegate.go
  atc/exec/execfakes/fake_get_delegate.go
  atc/exec/execfakes/fake_pool.go
  atc/exec/execfakes/fake_put_delegate.go
  atc/exec/execfakes/fake_set_pipeline_step_delegate.go
  atc/exec/execfakes/fake_task_config_source.go
  atc/exec/execfakes/fake_task_delegate.go
  atc/exec/get_step.go
  atc/exec/step.go
  go-archive/tarfs/compress.go
  go-archive/tgzfs/compress.go
  worker/baggageclaim/client.go
  worker/baggageclaim/uidgid/namespace.go
  worker/baggageclaim/uidgid/translator.go
  worker/baggageclaim/uidgid/uidgidfakes/fake_namespacer.go
  worker/baggageclaim/uidgid/uidgidfakes/fake_translator.go
  worker/baggageclaim/volume/driver.go
  worker/baggageclaim/volume/filesystem.go
  worker/baggageclaim/volume/locker.go
  worker/baggageclaim/volume/repository.go
  worker/baggageclaim/volume/strategy.go
  worker/baggageclaim/volume/stream.go
  worker/runtime/integration/integration_test.go
  worker/runtime/libcontainerd/libcontainerdfakes/fake_container.go
  worker/runtime/libcontainerd/libcontainerdfakes/fake_task.go
Labels: misc

#9074 Go 1.24.0
  atc/postgresrunner/join_limit_conn.go
  atc/postgresrunner/postgresrunner.go
  atc/step_validator.go
  fly/commands/prune_worker.go
  fly/commands/rerun_build.go
  fly/commands/trigger_job.go
  fly/ui/formatting.go
  fly/ui/table.go
  go-concourse/concourse/pipelines.go
  go.mod
Labels: release/undocumented, misc

#9076 Add support for Strict-Transport-Security header
  atc/atccmd/command.go
  atc/wrappa/security_handler.go
  atc/wrappa/security_handler_test.go
Labels: misc

#9077 baggageclaim: Fix StreamIn dir handling and response body leak
  worker/baggageclaim/volume/repository.go
Labels: misc

#9017 Introduce privileged-mode
  worker/baggageclaim/baggageclaimcmd/baggageclaimcmd_suite_test.go
  worker/baggageclaim/baggageclaimcmd/command.go
  worker/baggageclaim/baggageclaimcmd/command_test.go
  worker/baggageclaim/cmd/baggageclaim/main.go
  worker/runtime/backend.go
  worker/runtime/spec/capabilities.go
  worker/runtime/spec/devices.go
  worker/runtime/spec/mounts.go
  worker/runtime/spec/namespaces.go
  worker/runtime/spec/seccomp.go
  worker/runtime/spec/spec.go
  worker/runtime/spec/spec_test.go
  worker/workercmd/containerd.go
  worker/workercmd/worker.go
  worker/workercmd/worker_linux.go
Labels: enhancement

#9078 atc: exec: ignore task input/output paths that reference parent directories
  atc/exec/task_step.go
  atc/exec/task_step_test.go
Labels: enhancement

#9049 make sure to drop item from secret cache after default duration if calculated duration is equal or less than 0
  atc/creds/cached_secrets.go
  atc/creds/cached_secrets_test.go
Labels: bug

#9079 Only pass PrivilegedMode to baggageclaim for linux workers
  worker/baggageclaim/baggageclaimcmd/command.go
  worker/baggageclaim/baggageclaimcmd/command_test.go
  worker/baggageclaim/cmd/baggageclaim/main.go
  worker/workercmd/worker.go
  worker/workercmd/worker_linux.go
  worker/workercmd/worker_nonlinux.go
Labels: release/undocumented, misc

#9081 fix the policy-checker-handler logger session name
  atc/api/policychecker/handler.go
Labels: bug

#9082 Fix bug in maxValidFromFile using hardcoded path
  worker/runtime/user_namespace.go
Labels: bug

#9083 Use github.com/google/uuid to generate UUIDv4
  atc/db/dbtest/builder.go
  atc/db/volume.go
  atc/db/volume_repository.go
  atc/db/worker.go
  atc/metric/emitter/newrelic.go
  atc/metric/emitter/newrelic_test.go
  atc/worker/gardenruntime/gardenruntimetest/garden.go
  atc/worker/gardenruntime/worker.go
  go.mod
  go.sum
  testflight/image_resource_caching_test.go
  testflight/input_overriding_test.go
  testflight/matrix_test.go
  testflight/pinned_version_check_test.go
  testflight/rerun_build_test.go
  testflight/resource_cache_test.go
  testflight/resource_check_test.go
  testflight/resource_config_versions_test.go
  testflight/resource_containers_gc_test.go
  testflight/resource_reconfigure_test.go
  testflight/resource_type_check_test.go
  testflight/resource_type_privileged_test.go
  testflight/resource_type_test.go
  testflight/resource_version_test.go
  testflight/serial_groups_test.go
  testflight/suite_test.go
  testflight/trigger_test.go
  worker/baggageclaim/api/volume_server.go
  worker/runtime/container.go
  worker/runtime/file_store.go
  worker/runtime/integration/suite_test.go
Labels: bug

#9084 worker runtime: concurrent process killing
  worker/runtime/killer.go
Labels: enhancement
