Repository concourse/concourse, pull requests merged in 2025-03, with the labels that each got.

#9093 CI: only run baggageclaimcmd test on linux
  worker/baggageclaim/baggageclaimcmd/command_linux_test.go
Labels: bug, release/undocumented

#9096 web: Small refactors
  atc/atccmd/command.go
  atc/configvalidate/validate.go
  atc/db/base_resource_type.go
  atc/db/container_repository.go
  atc/db/job.go
  atc/db/job_factory.go
  atc/db/log_conn.go
  atc/db/log_dbconn.go
  atc/db/task_cache_lifecycle.go
  atc/runtime/types.go
  atc/scheduler/algorithm/group_resolver.go
  web/handler.go
  web/index_handler.go
Labels: misc

#9097 fly: improve performance of fly watch
  fly/eventstream/timestamped_writer.go
  fly/eventstream/timestamped_writer_test.go
Labels: enhancement

#9098 web: Update frontend graphics dependencies
  web/assets/css/typography.less
  web/elm/src/Dashboard/Footer.elm
  web/public/causality.mjs
  web/public/clipboard.min.js
  web/public/d3.v355.min.js
  web/public/d3.v7.min.js
  web/public/fonts/Inconsolata-Black.ttf
  web/public/fonts/Inconsolata-Black.woff2
  web/public/fonts/Inconsolata-Bold.ttf
  web/public/fonts/Inconsolata-Bold.woff2
  web/public/fonts/Inconsolata-Regular.ttf
  web/public/fonts/Inconsolata-Regular.woff2
  web/public/graphviz.min.js
  web/public/graphvizlib.wasm
  web/public/images/favicon-maskable-x1024.png
  web/public/images/favicon-maskable-x192.png
  web/public/images/favicon-maskable-x384.png
  web/public/images/favicon-maskable-x512.png
  web/public/index.html
  web/public/index.mjs
  web/public/manifest.json
  web/public/manifest.webmanifest
  web/public/mdi-svg.min.js
  web/public_handler.go
Labels: misc

#9094 Mount /sys/fs/cgroup as cgroup2 type if supported
  go.mod
  go.sum
  worker/runtime/spec/mounts.go
  worker/runtime/spec/spec_test.go
Labels: enhancement

#9100 Gracefully recover from containerd TaskNotFound errors
  worker/runtime/container.go
  worker/runtime/container_test.go
  worker/runtime/integration/integration_test.go
Labels: bug

#9101 worker: split linux and non-linux features
  atc/builds/tracker_test.go
  worker/baggageclaim/baggageclaimcmd/command.go
  worker/baggageclaim/baggageclaimcmd/command_linux.go
  worker/baggageclaim/baggageclaimcmd/command_nonlinux.go
  worker/runtime/backend.go
  worker/runtime/backend_test.go
  worker/runtime/cni_network.go
  worker/runtime/container.go
  worker/runtime/errors.go
  worker/runtime/file_store.go
  worker/runtime/killer.go
  worker/runtime/network.go
  worker/runtime/process.go
  worker/runtime/process_killer.go
  worker/runtime/properties.go
  worker/runtime/resolvconf_parser.go
  worker/runtime/rootfs_manager.go
  worker/runtime/spec/capabilities.go
  worker/runtime/spec/devices.go
  worker/runtime/spec/mounts.go
  worker/runtime/spec/namespaces.go
  worker/runtime/spec/seccomp.go
  worker/runtime/spec/spec.go
  worker/runtime/spec/spec_nonlinux.go
  worker/runtime/timeout_lock.go
  worker/runtime/user_namespace.go
  worker/workercmd/containerd.go
  worker/workercmd/worker_nonlinux.go
Labels: release/undocumented, misc

#9103 web: avoid duplicate in-memory checks
  atc/builds/tracker.go
  atc/builds/tracker_test.go
  atc/db/lock/in_mem.go
Labels: bug

#9102 Fix `--team` flag in `order-pipelines` command
  fly/commands/ordering_pipeline.go
  fly/integration/error_handling_test.go
  fly/integration/ordering_pipelines_test.go
Labels: bug

#9107 Add `--team` flag to `containers` command
  fly/commands/containers.go
  fly/integration/containers_test.go
  fly/integration/error_handling_test.go
Labels: enhancement

#9108 feat: increase footer hide delay from 4 to 8 seconds
  web/elm/src/Dashboard/Footer.elm
  web/elm/tests/DashboardTests.elm
Labels: misc

#9109 Fix: Preserve existing browser session during `fly login`
  web/public/elm-setup.js
Labels: bug

#9111 Add ESC key shortcut to hide keyboard help
  web/elm/src/Build/Shortcuts.elm
Labels: misc

#9113 Fix fish shell completion generation
  fly/commands/completion.go
Labels: bug

#9114 Use math/rand/v2
  atc/atccmd/command.go
  atc/db/migration/migration_test.go
  atc/integration/team_migration_test.go
  atc/worker/placement.go
  atc/worker/pool.go
  topgun/k8s/k8s_suite_test.go
  tsa/client.go
  tsa/random_atc_endpoint_picker.go
  worker/baggageclaim/integration/baggageclaim/suite_test.go
Labels: misc

#9115 Fix race condition in NotificationsBus
  atc/db/notifications_bus.go
Labels: misc

#9133 Revert "Merge pull request #9021 from IvanChalukov/master" - skip-migrations-check
  atc/db/build.go
  atc/db/build_test.go
  atc/db/dbtest/builder.go
  atc/db/job.go
  atc/db/job_test.go
  atc/db/migration/migrations/1728989566_switch_md5_to_sha256.down.sql
  atc/db/migration/migrations/1728989566_switch_md5_to_sha256.up.sql
  atc/db/pipeline.go
  atc/db/pipeline_test.go
  atc/db/resource.go
  atc/db/resource_cache_factory.go
  atc/db/resource_cache_factory_test.go
  atc/db/resource_cache_lifecycle.go
  atc/db/resource_cache_lifecycle_test.go
  atc/db/resource_config_scope.go
  atc/db/versions_db.go
  atc/db/versions_db_test.go
  atc/gc/resource_cache_collector_test.go
  atc/scheduler/algorithm/firstoccurrence_test.go
  atc/scheduler/algorithm/migration_test.go
  atc/scheduler/algorithm/table_helpers_test.go
Labels: release/undocumented, misc

#9117 Support custom pipeline background image styling
  atc/config.go
  web/elm/src/Concourse.elm
  web/elm/src/Dashboard/Dashboard.elm
  web/elm/src/Pipeline/Pipeline.elm
  web/elm/src/Pipeline/Styles.elm
  web/elm/tests/Data.elm
  web/elm/tests/PipelineTests.elm
Labels: enhancement

#9126 Remove unused 'visited' field from varsTracker struct
  vars/template.go
Labels: misc

#9121 Remove 'set_pipeline' experimental warnings
  atc/exec/set_pipeline_step.go
  atc/exec/set_pipeline_step_test.go
Labels: misc

#9149 Pre release deps update
  CONTRIBUTING.md
  atc/metric/emitter/newrelic_test.go
  go.mod
  go.sum
  skymarshal/dexserver/dexserver.go
  skymarshal/dexserver/dexserver_test.go
  tracing/tracer_test.go
  worker/container_sweeper_test.go
  worker/integration/integration_test.go
  worker/integration/suite_test.go
  worker/runtime/cni_network_test.go
  worker/runtime/container_test.go
  worker/runtime/file_store_test.go
  worker/runtime/killer_test.go
  worker/runtime/process_killer_test.go
  worker/runtime/process_test.go
  worker/runtime/resolvconf_parser_test.go
  worker/runtime/rootfs_manager_test.go
  worker/runtime/runtime_nonlinux.go
  worker/runtime/spec/spec_test.go
  worker/runtime/spec/suite_test.go
  worker/runtime/suite_test.go
  worker/runtime/timeout_lock_test.go
  worker/runtime/user_namespace_test.go
Labels: release/undocumented, misc

#9150 Update yarn from v1 to v4
  .gitignore
  .yarnrc.yml
  package.json
  web/elm/benchmarks/benchmark.js
  web/wats/helpers/fly.js
  web/wats/helpers/palette.js
  web/wats/helpers/suite.js
  web/wats/helpers/web.js
  web/wats/package-lock.json
  web/wats/package.json
  web/wats/test/build.js
  web/wats/test/dashboard.js
  web/wats/test/login.js
  web/wats/test/resource.js
  web/wats/test/smoke.js
  web/wats/yarn.lock
  webpack.config.js
  yarn.lock
Labels: release/undocumented, misc

#9164 bump pgx to latest patch
  go.mod
  go.sum
Labels: release/undocumented, misc
