Repository concourse/concourse, pull requests merged in 2025-04, with the labels that each got.

#9171 Re-add the original Concourse MDI icon to mdi-svg.min.js after the upgrade to 7.4.47 removed it.
  hack/concourse-ci-mdi.svg
  hack/update-mdi-svg
  web/public/mdi-svg.min.js
Labels: misc

#9173 runtime: Seccomp update
  worker/runtime/spec/seccomp.go
  worker/runtime/spec/spec_test.go
Labels: enhancement

#9116 docs: document computeDrift() more clearly
  atc/db/component.go
Labels: release/undocumented, misc

#9118 refactor: More granular locking in WorkerCache
  atc/db/worker_cache.go
Labels: misc

#9119 atc: allow identifiers to start with numbers
  atc/api/config_test.go
  atc/api/pipelines_test.go
  atc/api/teams_test.go
  atc/configwarning.go
  atc/configwarning_test.go
Labels: enhancement
